### PR TITLE
feature: #908: Reduce overall number of storage transactions

### PR DESCRIPTION
**Pull request by IgorKupreychik**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: all files reviewed, 8 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 11 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRluC5r8c5U4fBPLuec:-NRluC5r8c5U4fBPLued:b93j07z) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L11)):*
> ```Smalltalk
>     public interface IBlobDownloader
>     {
>         Task<T> Download<T>(string container, string filename);
> ```

now we have multiple methods on the interface, it worth explaining what each does and what they return via doccomments
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 95 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRlv3120LxQBMGF5U25:-NRlv3120LxQBMGF5U26:b-xgeccn) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L95)):*
> ```Smalltalk
>             using (logger.RunTimed("Uploading match prediction requests"))
>             {
>                 var matchPredictionRequestFileNames = await matchPredictionRequestBlobClient.UploadBatchRequests(matchingResultsNotification.SearchRequestId, matchPredictionInputs.ToList());
> ```

do we need to enumerate `matchPredictionInputs` here?
___
*[`Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs` line 32 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRlvc4Y3N5TQXVvMmAS:-NRlvc4Y3N5TQXVvMmAT:bxkwv83) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs#L32)):*
> ```Smalltalk
>         }
> 
>         public async Task<List<string>> UploadBatchRequests(string searchRequestId, IEnumerable<MultipleDonorMatchProbabilityInput> batchRequests)
> ```

This has nothing to do with your changes, but while you are here, can you please rename this to `UploadMatchProbabilityRequests` cuz overuse of the word "Batch" in the codebase is now getting very confusing! :laughing: 

and also pls rename the second param to `requests`



_Code quote:_
```Smalltalk
UploadBatchRequests
```
___
*[`Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs` line 34 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRlw0kI7JRyyU3fB3N2:-NRlw0kI7JRyyU3fB3N3:bxmaocq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs#L34)):*
> ```Smalltalk
>         public async Task<List<string>> UploadBatchRequests(string searchRequestId, IEnumerable<MultipleDonorMatchProbabilityInput> batchRequests)
>         {
>             var batchRequestsWithNames = batchRequests.Select(r => new KeyValuePair<string, MultipleDonorMatchProbabilityInput>($"{searchRequestId}/{r.MatchProbabilityRequestId}.json", r)).ToDictionary();
> ```

as above, please rename var to `requestsWithNames`
___
*[`Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs` line 36 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRlwij22ivG3ir3AMQC:-NRlwij22ivG3ir3AMQD:b-fju06j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs#L36)):*
> ```Smalltalk
>             var batchRequestsWithNames = batchRequests.Select(r => new KeyValuePair<string, MultipleDonorMatchProbabilityInput>($"{searchRequestId}/{r.MatchProbabilityRequestId}.json", r)).ToDictionary();
>             await blobUploader.UploadMultiple(container, batchRequestsWithNames);
>             return batchRequestsWithNames.Select(f => f.Key).ToList();
> ```

can simplify return object to `IEnumerable` and remove enumeration step



_Code quote:_
```Smalltalk
.ToList();
```
___
*[`Atlas.Functions/Services/BlobStorageClients/MatchPredictionResultsDownloader.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRlxJoQEGWbOMRm1HGy:-NRlxJoQEGWbOMRm1HGz:b-jkcshy) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.Functions/Services/BlobStorageClients/MatchPredictionResultsDownloader.cs#L15)):*
> ```Smalltalk
>     }
> 
>     internal class MatchPredictionResultsDownloader : IMatchPredictionResultsDownloader
> ```

do we need this class, all it's doing is calling the blob downloader, can we call it directly in the caller service and inject settings via DI?
___
*[`Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs` line 71 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRn26cTEX-l-3Skrebj:-NRn26cTEX-l-3Skrebk:brjxl79) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs#L71)):*
> ```Smalltalk
>                         var result = await matchProbabilityService.CalculateMatchProbability(matchProbabilityInput);
>                         var matchProbabilityInputFileNames = await resultUploader.UploadSearchDonorResults(searchRequestId, matchProbabilityInput.Donor.DonorIds, result);
>                         fileNames = EnumerableExtensions.ToDictionary(fileNames.Merge(matchProbabilityInputFileNames));
> ```

does `fileNames.Merge(matchProbabilityInputFileNames).ToDictionary()` not work?

but also, the output of .Merge is an IDictionary, so why does it need converting?



_Code quote:_
```Smalltalk
EnumerableExtensions.ToDictionary
```
___
*[`Atlas.MatchPrediction/ExternalInterface/ResultsUpload/MatchProbabilityResultUploader.cs` line 23 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRm9vYm4Z_3I1TkdNnr:-NRm9vYm4Z_3I1TkdNns:b-g23gef) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.MatchPrediction/ExternalInterface/ResultsUpload/MatchProbabilityResultUploader.cs#L23)):*
> ```Smalltalk
>         }
> 
>         public async Task UploadResult(string fileName, MatchProbabilityResponse matchProbabilityResponse)
> ```

is this still used?

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs` line 71 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRn26cTEX-l-3Skrebj:-NRq7VfA8GGcK_X4Uqgr:b-whj99g) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs#L71)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

does `fileNames.Merge(matchProbabilityInputFileNames).ToDictionary()` not work?

but also, the output of .Merge is an IDictionary, so why does it need converting?
</blockquote></details>

Good point. Actually, I do exactly the same call here, but in a bit different way (calling it as a regular method, not as an extension).
During development it was an extra using (which implements .Batch()) which made ToDictionary() ambiguous, that's why I initially implemented it this way (to explicitly specify the namespace we need to use ToDictionary() from). Then this extra using was removed (since we decided not to use Batch() here), but I forgot to change the line with ToDictionary(). Will fix it.

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction/ExternalInterface/ResultsUpload/MatchProbabilityResultUploader.cs` line 23 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRm9vYm4Z_3I1TkdNnr:-NRq9fJV6gD7X59pMh1b:b-81up61) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.MatchPrediction/ExternalInterface/ResultsUpload/MatchProbabilityResultUploader.cs#L23)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

is this still used?
</blockquote></details>

Yes, it's used by MatchPredictionRequestResultUploader class (Atlas.MatchPrediction)

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs` line 71 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRn26cTEX-l-3Skrebj:-NRqJLsfAiHsNsa4LPI3:b4v32e7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/77ae1b3c2b8eb44b8a35876c9d951d1fc519c171/Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithm.cs#L71)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

Good point. Actually, I do exactly the same call here, but in a bit different way (calling it as a regular method, not as an extension).
During development it was an extra using (which implements .Batch()) which made ToDictionary() ambiguous, that's why I initially implemented it this way (to explicitly specify the namespace we need to use ToDictionary() from). Then this extra using was removed (since we decided not to use Batch() here), but I forgot to change the line with ToDictionary(). Will fix it.
</blockquote></details>

"but also, the output of .Merge is an IDictionary, so why does it need converting?"
fileNames is a Dictionary<int, string>, it's not possible to implicitly convert IDictionary<int, string> to Dictionary<int, stirng> (compiler is complaining), that's why we need to convert it explicitly by calling ToDictionary()

**Review by zabeen — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: all files reviewed, 5 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 30 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRqtXsG2p4-ym8GDro7:-NRqtXsG2p4-ym8GDro8:b83wfah) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9da46b58205b49932d54a14df9d1db92b00f3393/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L30)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Dowload files from all the locations specified in <paramref name="locations"/ from blob container <paramref name="container"/>
> ```

typo, missing close bracket



_Code quote:_
```Smalltalk
<paramref name="locations"/ from
```
___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 39 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRqtpICD_a5YwrT2EWl:-NRqtpICD_a5YwrT2EWm:buvq683) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9da46b58205b49932d54a14df9d1db92b00f3393/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L39)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Downloads all files within the folder <paramref name="folderName"/> from blob container <paramref name="container"/> file by file (i.e. it serializes and keeps in memory data from one file only)
> ```

typo: deserializes



_Code quote:_
```Smalltalk
serializes
```
___
*[`Atlas.Functions/Startup.cs` line 94 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRqusV6BfW74Eg_Rjvf:-NRqusV6BfW74Eg_Rjvg:ba7gcl9) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9da46b58205b49932d54a14df9d1db92b00f3393/Atlas.Functions/Startup.cs#L94)):*
> ```Smalltalk
>                 var options = sp.GetService<IOptions<Settings.AzureStorageSettings>>();
>                 var connectionString = options.Value.MatchPredictionConnectionString;
>                 var downloader = new BlobDownloader(connectionString, logger);
> ```

Optional

You could keep the original interface of `IMatchPredictionResultsDownloader`(without the concrete class) and have it inheriting from `IBlobDownloader`, then

```
            services.AddScoped<IMatchPredictionResultsDownloader, BlobDownloader>(sp =>
            {
                var connectionString = options.Value.MatchPredictionConnectionString;
                var logger = sp.GetService<ILogger>();
                return new BlobDownloader(connectionString, logger);
            });
```
Results combiner would simplify to:
`services.AddScoped<IResultsCombiner, ResultsCombiner>();` (and of course update the constructor for ResultsCombiner to use the more specific interface)

not sure how critical this change is! Hence left it as optional.

**Review by zabeen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

**Comment by IgorKupreychik** [comment]
*[`Atlas.Functions/Startup.cs` line 94 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRqusV6BfW74Eg_Rjvf:-NRqzbkEAz78RFuDniev:bhr1p3m) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9da46b58205b49932d54a14df9d1db92b00f3393/Atlas.Functions/Startup.cs#L94)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Optional

You could keep the original interface of `IMatchPredictionResultsDownloader`(without the concrete class) and have it inheriting from `IBlobDownloader`, then

```
            services.AddScoped<IMatchPredictionResultsDownloader, BlobDownloader>(sp =>
            {
                var connectionString = options.Value.MatchPredictionConnectionString;
                var logger = sp.GetService<ILogger>();
                return new BlobDownloader(connectionString, logger);
            });
```
Results combiner would simplify to:
`services.AddScoped<IResultsCombiner, ResultsCombiner>();` (and of course update the constructor for ResultsCombiner to use the more specific interface)

not sure how critical this change is! Hence left it as optional. 
</blockquote></details>

I know that technically it's possible to do so, but wouldn't it introduce more confusion? I'd prefer to keep it as is...

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

___
*[`Atlas.Functions/Startup.cs` line 94 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927#-NRqusV6BfW74Eg_Rjvf:-NRr5KkyE5WOSx-3JGSR:b4c9lyr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9da46b58205b49932d54a14df9d1db92b00f3393/Atlas.Functions/Startup.cs#L94)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

I know that technically it's possible to do so, but wouldn't it introduce more confusion? I'd prefer to keep it as is...
</blockquote></details>

:thumbsup:

**Review by zabeen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
