### PR TITLE
feature: CBT-3345: Update health check functions to be the same as in…

### PR DESCRIPTION
**Pull request by pchenery**
… Matching Algorithm

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381)* status: all files reviewed, 6 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.DonorImport.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEX74u5d1etigIW4hm:-OCEX74u5d1etigIW4hn:b-v6257z) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.DonorImport.Functions/Functions/HealthCheckFunctions.cs#L15)):*
> ```Smalltalk
>         private readonly HealthCheckService healthCheckService;
> 
>         public HealthCheckFunctions(HealthCheckService healthCheckService)
> ```

This will fail, because you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
___
*[`Atlas.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXmvX9qvhV3eTxAEv:-OCEXmvX9qvhV3eTxAEw:b-72xybe) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.Functions/Functions/HealthCheckFunctions.cs#L15)):*
> ```Smalltalk
>         private readonly HealthCheckService healthCheckService;
> 
>         public HealthCheckFunctions(HealthCheckService healthCheckService)
> ```

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
___
*[`Atlas.MatchPrediction.Test.Verification/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXsUCCpdqFd7RPx6u:-OCEXsUCCpdqFd7RPx6v:b-72xybe) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.MatchPrediction.Test.Verification/Functions/HealthCheckFunctions.cs#L15)):*
> ```Smalltalk
>         private readonly HealthCheckService healthCheckService;
> 
>         public HealthCheckFunctions(HealthCheckService healthCheckService)
> ```

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
___
*[`Atlas.Functions.PublicApi/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXpjnCWg_2GrGhLv-:-OCEXpjnCWg_2GrGhLv0:b-72xybe) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.Functions.PublicApi/Functions/HealthCheckFunctions.cs#L15)):*
> ```Smalltalk
>         private readonly HealthCheckService healthCheckService;
> 
>         public HealthCheckFunctions(HealthCheckService healthCheckService)
> ```

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
___
*[`Atlas.MatchPrediction.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXr_x18va1pDcmDFe:-OCEXr_x18va1pDcmDFf:b-72xybe) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.MatchPrediction.Functions/Functions/HealthCheckFunctions.cs#L15)):*
> ```Smalltalk
>         private readonly HealthCheckService healthCheckService;
> 
>         public HealthCheckFunctions(HealthCheckService healthCheckService)
> ```

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
___
*[`Atlas.RepeatSearch.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXv_G5L22LKAl9dLg:-OCEXv_G5L22LKAl9dLh:b-72xybe) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.RepeatSearch.Functions/Functions/HealthCheckFunctions.cs#L15)):*
> ```Smalltalk
>         private readonly HealthCheckService healthCheckService;
> 
>         public HealthCheckFunctions(HealthCheckService healthCheckService)
> ```

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381)* status: all files reviewed, 6 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEX74u5d1etigIW4hm:-OCEjC1t8EG0xTVkTl0L:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.DonorImport.Functions/Functions/HealthCheckFunctions.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This will fail, because you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
</blockquote></details>

Done.
___
*[`Atlas.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXmvX9qvhV3eTxAEv:-OCEjRkj5NThcuMN1MDG:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.Functions/Functions/HealthCheckFunctions.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
</blockquote></details>

Done.
___
*[`Atlas.Functions.PublicApi/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXpjnCWg_2GrGhLv-:-OCEjSzR0dMGw5kV_Obw:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.Functions.PublicApi/Functions/HealthCheckFunctions.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
</blockquote></details>

Done.
___
*[`Atlas.MatchPrediction.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXr_x18va1pDcmDFe:-OCEjYuDCqXC70C2aNVq:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.MatchPrediction.Functions/Functions/HealthCheckFunctions.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
</blockquote></details>

Done.
___
*[`Atlas.MatchPrediction.Test.Verification/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXsUCCpdqFd7RPx6u:-OCEjceq4y7-f8oAgpBk:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.MatchPrediction.Test.Verification/Functions/HealthCheckFunctions.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch.Functions/Functions/HealthCheckFunctions.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCEXv_G5L22LKAl9dLg:-OCEjdq69KvQz69RrT4t:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/67f9962b2434bac4c9e444accb29c5c833f6877d/Atlas.RepeatSearch.Functions/Functions/HealthCheckFunctions.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same - you also need to register the health check service in DI - see:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Functions/Startup.cs#L21
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCIG9ErEbmyCDiTozMd:-OCIG9ErEbmyCDiTozMe:b1tt1hp) (no related file):*
Let's also register health check in terraform - see:

```
health_check_path                 = "/api/HealthCheck"
health_check_eviction_time_in_min = 10
```

https://github.com/Anthony-Nolan/Atlas/blob/master/terraform/core/modules/matching_algorithm/matching_algorithm_function.tf#L108

Let's make sure that all the functions:
1) now have the endpoint
2) have health check enabled in terraform

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1381#-OCIG9ErEbmyCDiTozMd:-OCIeDgx4FfdQ4HJ-vKM:b6q6xmw) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's also register health check in terraform - see:

```
health_check_path                 = "/api/HealthCheck"
health_check_eviction_time_in_min = 10
```

https://github.com/Anthony-Nolan/Atlas/blob/master/terraform/core/modules/matching_algorithm/matching_algorithm_function.tf#L108

Let's make sure that all the functions:
1) now have the endpoint
2) have health check enabled in terraform
</blockquote></details>

Haven't updated/created any terraform for MatchPrediction.Test.Verification

**Pull request merged**
