### PR TITLE
feature: #819: migration to Azure.Messaging..ServiceBus

### PR DESCRIPTION
**Pull request by SergeyEzh**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 52 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Clients/ServiceBus/SearchServiceBusClient.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343#-O2iL97iAqpM2QGi1Bvl:-O2iL97iAqpM2QGi1Bvm:b-mqhiik) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/33a59b6257ed6343da3ddb0758ddf744550a7f5c/Atlas.MatchingAlgorithm/Clients/ServiceBus/SearchServiceBusClient.cs#L68)):*
> ```Smalltalk
>             message.MessageId = Guid.NewGuid().ToString();
> 
>             await using var client = topicClientFactory.BuildTopicClient(resultsNotificationTopicName);// new TopicClient(connectionString, resultsNotificationTopicName);
> ```

do we need this commented out code?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343#-O2iXwhtBmcRd0bSy4XB:-O2iXwhtBmcRd0bSy4XC:b-hhvina) (no related file):*
Please fix the System Tests failures

https://dev.azure.com/anthony-nolan-nova/Atlas/_build?definitionId=55

___

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343#-O2iXwhtBmcRd0bSy4XB:-O33JAeoDBXzNqvyL3nC:b-7hdcrh) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please fix the System Tests failures

https://dev.azure.com/anthony-nolan-nova/Atlas/_build?definitionId=55
</blockquote></details>

Need to re-run the tests and check that they succeed before the merge

___
___
*[`Atlas.DonorImport.Test.Integration/DependencyInjection/DependencyInjection.cs` line 39 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343#-O33J0KPCI0FFX7ZjNrd:-O33J0KPCI0FFX7ZjNre:b-hlfhc6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/82adce0cf1f2dc47dfa4f1d2abfa9e4f811b972d/Atlas.DonorImport.Test.Integration/DependencyInjection/DependencyInjection.cs#L39)):*
> ```Smalltalk
>         {
>             scope?.DisposeAsync().AsTask().Wait();
>             scope = BackingProvider.CreateAsyncScope(); //.CreateScope();
> ```

Do we need the commented-out code?

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343)* status: 53 of 54 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @pchenery)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343#-O2iXwhtBmcRd0bSy4XB:-O37n2NcB98xSBujBFAx:bjskud9) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Need to re-run the tests and check that they succeed before the merge
</blockquote></details>

https://dev.azure.com/anthony-nolan-nova/Atlas/_build/results?buildId=51188&view=results - Everything seems to be ok

___
___
*[`Atlas.MatchingAlgorithm/Clients/ServiceBus/SearchServiceBusClient.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343#-O2iL97iAqpM2QGi1Bvl:-O37npQrCVOvY3crUi2R:bd8d1hf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/33a59b6257ed6343da3ddb0758ddf744550a7f5c/Atlas.MatchingAlgorithm/Clients/ServiceBus/SearchServiceBusClient.cs#L68)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

do we need this commented out code?
</blockquote></details>

no, thanks

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1343)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
