### PR TITLE
#905 Update to a missing donor prevents processing of other records in import file

### PR DESCRIPTION
**Pull request by disaev-nmdp**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)* status: all files reviewed, 4 unresolved discussions (waiting on @disaev-nmdp and @IgorKupreychik)

___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 12 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhsxPGDx2azH_TfRvm:-NRhsxPH2g-94npRW92Y:b1zkg79) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L12)):*
> ```Smalltalk
>     internal class SearchableDonorValidator : AbstractValidator<DonorUpdate>
>     {
>         public SearchableDonorValidator(SearchableDonorValidatorContext context)
> ```

nice solution! :)



_Code quote:_
```Smalltalk
SearchableDonorValidatorContext context
```
___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 25 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhpb_x3Si8Zm8Xsb6j:-NRhpb_x3Si8Zm8Xsb6k:bijtba3) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L25)):*
> ```Smalltalk
>                 RuleFor(d => d.RecordId)
>                     .Must(context.ExternalDonorCodes.Contains)
>                     .WithMessage("Donor with {PropertyName} '{PropertyValue}' is not presented in the database.");
> ```

typo: change "presented" to "present"
___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 99 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhvSbR0QOWGJyDd3UN:-NRhvSbR0QOWGJyDd3UO:b-9zvfq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L99)):*
> ```Smalltalk
>                 .WithMessage($"Optional locus {locus}, {hlaFieldType}: Field1 cannot be empty when Field2 is provided");
>         }
>     }
> ```

we need to also throw validation error when trying to create a donor that already exists, i.e., when changeType is Create then context.ExternalDonorCodes cannot contain d.RecordId
___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs` line 233 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhsZ762hJOyMs3gqfx:-NRhsZ7757shY4eELkZh:b-1v1mgd) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs#L233)):*
> ```Smalltalk
>             var badEditBuilder = donorEditBuilderForInitialDonors.With(update => update.RecordId, "Unknown");
> 
>             var goodDonorEditUpdates = donorEditBuilderForInitialDonors.Build(4).ToArray();
> ```

You can set this using a const int, e.g., `goodDonorUpdateCount` and then use in the assert step



_Code quote:_
```Smalltalk
4
```
___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs` line 247 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhsDh098N4G570Q80h:-NRhsDh098N4G570Q80i:bwdpx5e) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs#L247)):*
> ```Smalltalk
> 
>             var updatesCountAfterImport = await updatesInspectionRepository.Count();
>             updatesCountAfterImport.Should().BeGreaterThan(updatesCountBeforeImport);
> ```

we know how many "good" donors should be imported so we can be more specific with our assert, i.e., updatesCountAfterImport.Should().Be(updatesCountBeforeImport + goodDonorUpdateCount)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)* status: all files reviewed, 4 unresolved discussions (waiting on @disaev-nmdp and @IgorKupreychik)

___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 99 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhvSbR0QOWGJyDd3UN:-NRhvkKK0xSOoT1YroHh:b-pjsv2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L99)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

we need to also throw validation error when trying to create a donor that already exists, i.e., when changeType is Create then context.ExternalDonorCodes cannot contain d.RecordId
</blockquote></details>

this will mean extra unit tests for this validator and amending existing unit/integration tests related to creation

**Review by disaev-nmdp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da, @IgorKupreychik, and @zabeen)

___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 99 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhvSbR0QOWGJyDd3UN:-NS5Xn3v-1kVIkFePn9T:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L99)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

this will mean extra unit tests for this validator and amending existing unit/integration tests related to creation
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs` line 233 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhsZ762hJOyMs3gqfx:-NS5XqER9cCS0dCe5RCF:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs#L233)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

You can set this using a const int, e.g., `goodDonorUpdateCount` and then use in the assert step
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs` line 247 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NRhsDh098N4G570Q80h:-NS5XrNP4cZ81TFKKkTL:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fe65da0c63aca5d41d50f42d36da3a886e7f20f7/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs#L247)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

we know how many "good" donors should be imported so we can be more specific with our assert, i.e., updatesCountAfterImport.Should().Be(updatesCountBeforeImport + goodDonorUpdateCount)
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)* status: all files reviewed, 10 unresolved discussions (waiting on @disaev-nmdp, @IgorKupreychik, and @zabeen)

___
*[`README_DonorImport.md` line 100 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5eaRoBxiHbaQj7jy3:-NS5eaRoBxiHbaQj7jy4:b-c5spdv) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L100)):*
> ```Markdown
> The three operations - create, update and delete - will cause problems if the files are processed in an incorrect order. The following table explains the outcomes we expect.
> 
> [^1]: Invalid donor opertation is logged, rest file is continue to be processed.
> ```

`Invalid donor opertation is logged, rest file is continue to be processed.` -> `Invalid donor opertation is logged, and processing continues for the rest of the file.`
___
*[`README_DonorImport.md` line 106 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5eOdv4pVPp5xMRWUe:-NS5eOdv4pVPp5xMRWUf:bj9kvnc) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L106)):*
> ```Markdown
> | Create  | Create | AI logged[^1]         | AI logged[^1]                 | The first create will work correctly, then throw an error on the second import, not changing the data  |
> | Create  | Update | Updated donor         | AI logged[^1], then out of date donor | This will not throw an error and the donor will be out of date.                        |
> | Create  | Upsert | Updated donor         | Error                         | The first upsert operation will create donor correctly, then throw an error on the attempt to create the same donor, not changing the data |
> ```

Here wouldn't we have also AI logged, instead of Error?
___
*[`README_DonorImport.md` line 107 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5f6H-AmjP1wH1IxQk:-NS5f6H-AmjP1wH1IxQl:b-tqpbbb) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L107)):*
> ```Markdown
> | Create  | Update | Updated donor         | AI logged[^1], then out of date donor | This will not throw an error and the donor will be out of date.                        |
> | Create  | Upsert | Updated donor         | Error                         | The first upsert operation will create donor correctly, then throw an error on the attempt to create the same donor, not changing the data |
> | Create  | Delete | No change             | Error, then out of date donor | Error attempting to delete non-existing donor, then will create donor in the database that shouldn't be there   |
> ```

Is Error expected in case "Delete" is before "Create"?
___
*[`README_DonorImport.md` line 114 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5fSgT7jJVFReM5kWn:-NS5fSgT7jJVFReM5kWo:b-k91hxx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L114)):*
> ```Markdown
> | Update  | Delete | No donor              | No donor                      | No Donor in either case so this is fine                                                                |
> | Upsert  | Create | Create then AI logged[^1]     | Create then discard changes   |                                                                                                |
> | Upsert*  | Create | Update then error     | Error then update             | *Where donor already existed                    |
> ```

Are errors expected here?
___
*[`README_DonorImport.md` line 121 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5fYQX-bp-f076X-nV:-NS5fYQX-bp-f076X-nW:b-k91hxx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L121)):*
> ```Markdown
> | Delete  | Update | No donor, AI logged[^1] | Donor updated and deleted, no error            | In this and the case below this is fine as should be deleted                                           |
> | Delete  | Upsert | New donor       | Donor updated and not deleted, no error            | In this and the case below this is fine as should be deleted                                           |
> | Delete  | Delete | No donor, error       | No donor, no error            |                                                                                                        |
> ```

Are errors expected here?
___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 32 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5cBFr1l6r5bRmaXpB:-NS5cBFsAIHEYApHQ_7L:b-sh931h) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L32)):*
> ```Smalltalk
>                 RuleFor(d => d.RecordId)
>                     .Must(id => !context.ExternalDonorCodes.Contains(id))
>                     .WithMessage("Donor with {PropertyName} '{PropertyValue}' already presents in the database.");
> ```

`Donor with {PropertyName} '{PropertyValue}' is already present in the database.`
___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs` line 1057 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5fmnKABJSOJZHN_J4:-NS5fmnKABJSOJZHN_J5:b-wlxydq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L1057)):*
> ```Smalltalk
>             
>             // import File 2, Error, still no Donor
>             await donorFileImporter.ImportDonorFile(deleteFile2);
> ```

here there's no notification sent, and no AI logged as well - is it expected?

**Review by disaev-nmdp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)* status: 7 of 10 files reviewed, 10 unresolved discussions (waiting on @daria-sorokina-da, @IgorKupreychik, and @zabeen)

___
*[`README_DonorImport.md` line 100 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5eaRoBxiHbaQj7jy3:-NS6mOqUD6wnBuBZAAvW:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L100)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

`Invalid donor opertation is logged, rest file is continue to be processed.` -> `Invalid donor opertation is logged, and processing continues for the rest of the file.`
</blockquote></details>

Done.
___
*[`README_DonorImport.md` line 106 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5eOdv4pVPp5xMRWUe:-NS6mPoC9D7Ehltrwxhx:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L106)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Here wouldn't we have also AI logged, instead of Error?
</blockquote></details>

Done.
___
*[`README_DonorImport.md` line 107 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5f6H-AmjP1wH1IxQk:-NS6mULf3qB6u17hQwUB:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L107)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Is Error expected in case "Delete" is before "Create"?
</blockquote></details>

Done.
___
*[`README_DonorImport.md` line 114 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5fSgT7jJVFReM5kWn:-NS6mVXw1ayNlfej1OpP:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L114)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Are errors expected here?
</blockquote></details>

Done.
___
*[`README_DonorImport.md` line 121 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5fYQX-bp-f076X-nV:-NS6mX6Z1eAHN1p3Ve_g:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/README_DonorImport.md#L121)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Are errors expected here?
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Validators/SearchableDonorValidator.cs` line 32 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5cBFr1l6r5bRmaXpB:-NS6mYGP-GHerczJToYN:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/Atlas.DonorImport/Validators/SearchableDonorValidator.cs#L32)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

`Donor with {PropertyName} '{PropertyValue}' is already present in the database.`
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs` line 1057 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926#-NS5fmnKABJSOJZHN_J4:-NS6eVkL1UT_EYLcII-5:b-bg69r2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/292b29d20875f7de51483341ee8d57048551cdbc/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L1057)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

here there's no notification sent, and no AI logged as well - is it expected?
</blockquote></details>

Yes, there was an initial error

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik and @zabeen)

**Pull request merged**
