### PR TITLE
feature: #1231: added debug endpoint to query ai data for HLA expansi…

### PR DESCRIPTION
**Pull request by SergeyEzh**
…on faillures

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: all files reviewed, 3 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Functions/Startup.cs` line 54 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NrkXfka1_-B9TtkBVll:-NrkXfka1_-B9TtkBVlm:b-bplabr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/66ed8d99d9e8cb728bf483d243c41ac36bc51430/Atlas.MatchingAlgorithm.Functions/Startup.cs#L54)):*
> ```Smalltalk
>                 ConnectionStringReader("DonorSql"));
> 
>             RegisterLogQueryClient(builder.Services, builder.GetContext().Configuration);
> ```

this should be called within `builder.Services.RegisterDebugServices` method

so you can move `RegisterLogQueryClient` method to ServiceConfiguration and pass in "AzureManagement:Authentication" settings via `OptionReaderFor<AzureAuthenticationSettings>`



_Code quote:_
```Smalltalk
RegisterLogQueryClient(builder.Services, builder.GetContext().Configuration);
```
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs` line 152 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NrkW4s0-w8bVCetpdqD:-NrkW4s0-w8bVCetpdqE:b7ams4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/66ed8d99d9e8cb728bf483d243c41ac36bc51430/Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs#L152)):*
> ```Smalltalk
>         }
> 
>         [FunctionName(nameof(GetHlaExpansionFailures))]
> ```

please move this function to the `Debug.DonorFunctions` class because the query finds donors that have failed to be imported due to expansion failure
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs` line 180 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NrkX1Qe-XH_uQxrC1OG:-NrkX1Qe-XH_uQxrC1OH:b8w89w2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/66ed8d99d9e8cb728bf483d243c41ac36bc51430/Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs#L180)):*
> ```Smalltalk
> 
>                 output.Add(outputRow);
>             }
> ```

pls move all this logic and `HlaExpansionFailuresQuery` to a new class in `Atlas.MatchingAlgorithm.Services.Debug` namespace



_Code quote:_
```Smalltalk
            var response = await logsQueryClient.QueryWorkspaceAsync(azureMonitoringSettings.WorkspaceId, HlaExpansionFailuresQuery, new QueryTimeRange(TimeSpan.FromDays(daysToQuery ?? 14)));
            var result = response.Value;
            var output = new JArray();

            foreach (var row in result.Table.Rows)
            {
                var outputRow = new JObject();

                foreach (var (name, value) in result.Table.Columns.Select(col => (name: col.Name, value: row[col.Name])))
                {
                    outputRow.Add(
                        name,
                        value is BinaryData binaryData ? JToken.FromObject(binaryData.ToString()) : JToken.FromObject(value));
                }


                output.Add(outputRow);
            }
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm.Functions/Startup.cs` line 54 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NrkXfka1_-B9TtkBVll:-Ns8jgmO7ju7Tj0bfiNw:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/66ed8d99d9e8cb728bf483d243c41ac36bc51430/Atlas.MatchingAlgorithm.Functions/Startup.cs#L54)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

this should be called within `builder.Services.RegisterDebugServices` method

so you can move `RegisterLogQueryClient` method to ServiceConfiguration and pass in "AzureManagement:Authentication" settings via `OptionReaderFor<AzureAuthenticationSettings>`
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs` line 152 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NrkW4s0-w8bVCetpdqD:-Ns8jkD63dmSlIOK3gjL:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/66ed8d99d9e8cb728bf483d243c41ac36bc51430/Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs#L152)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please move this function to the `Debug.DonorFunctions` class because the query finds donors that have failed to be imported due to expansion failure
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs` line 180 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NrkX1Qe-XH_uQxrC1OG:-Ns8jkYpE4wImhFdF7gb:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/66ed8d99d9e8cb728bf483d243c41ac36bc51430/Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs#L180)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

pls move all this logic and `HlaExpansionFailuresQuery` to a new class in `Atlas.MatchingAlgorithm.Services.Debug` namespace
</blockquote></details>

Done.

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: all files reviewed, 7 unresolved discussions (waiting on @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA4rIW5tUATz8vTb0B:-NsA4rIW5tUATz8vTb0C:by2uz28) (no related file):*
Sorry, I missed this off the ticket, but last thing is, please add a new method to `MatchingAlgorithmFunctionsClient` in `Debug.Client` project to call the new query endpoint

___
___
*[`Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs` line 7 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA2nB4CDax0ViLYWeN:-NsA2nB4CDax0ViLYWeO:boavu6a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs#L7)):*
> ```Smalltalk
> using System.Threading.Tasks;
> 
> namespace Atlas.Debug.Client.Models.HlaExpansionFailures
> ```

Please rename this part of namespace to `ApplicationInsights`



_Code quote:_
```Smalltalk
HlaExpansionFailures
```
___
*[`Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs` line 14 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA2wcn3rImmSY3m5YF:-NsA2wcn3rImmSY3m5YG:b8nu834) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs#L14)):*
> ```Smalltalk
>         public string ExceptionType { set; get; }
>         public IEnumerable<string> ExternalDonorCodes { set; get; }
>         public long DonorCount { set; get; }
> ```

does it need to be a `long`? `int` should be sufficient



_Code quote:_
```Smalltalk
long
```
___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 178 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA39Z02tuWIYpnXxLl:-NsA39Z02tuWIYpnXxLm:bdhhggv) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L178)):*
> ```Smalltalk
>             });
> 
>             services.AddAzureClients(clientBuilder =>
> ```

please add short comment to say this is used to authenticate query to App.Insights API
___
*[`Atlas.MatchingAlgorithm/Services/Debug/HlaExpansionFailuresService.cs` line 56 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA3ViP5kf0fbmot_Dc:-NsA3ViP5kf0fbmot_Dd:b-ru5dzz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm/Services/Debug/HlaExpansionFailuresService.cs#L56)):*
> ```Smalltalk
>         public async Task<IEnumerable<HlaExpansionFailure>> Query(int daysToQuery)
>         {
>             var response = await logsQueryClient.QueryWorkspaceAsync(azureMonitoringSettings.WorkspaceId, HlaExpansionFailuresQuery, new QueryTimeRange(TimeSpan.FromDays(daysToQuery)));
> ```

style: put each arg on its own line



_Code quote:_
```Smalltalk
azureMonitoringSettings.WorkspaceId, HlaExpansionFailuresQuery, new QueryTimeRange(TimeSpan.FromDays(daysToQuery))
```
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 60 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA1m606N6bcTZGwcsP:-NsA1m606N6bcTZGwcsQ:b-j80opq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L60)):*
> ```Smalltalk
>                 AuthorizationLevel.Function,
>                 "get",
>                 Route = $"{RouteConstants.DebugRoutePrefix}/{nameof(GetHlaExpansionFailures)}/" + "{daysToQuery?}"
> ```

please remove the "get" from this portion of the route



_Code quote:_
```Smalltalk
{nameof(GetHlaExpansionFailures)}
```
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 73 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA25X44NXrUf3DvWv4:-NsA25X44NXrUf3DvWv5:babd8oj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L73)):*
> ```Smalltalk
>                 StatusCode = StatusCodes.Status200OK,
>                 ContentType = ContentType.ApplicationJson.ToString()
>             };
> ```

could use the more simple `JsonResult`, as we do on other debug endpoints



_Code quote:_
```Smalltalk
            return new ContentResult
            {
                Content = JToken.FromObject(output).ToString(), // Serializing in human friendly way
                StatusCode = StatusCodes.Status200OK,
                ContentType = ContentType.ApplicationJson.ToString()
            };
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: all files reviewed, 7 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs` line 7 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA2nB4CDax0ViLYWeN:-NsDFd_l7gAdC9582Ife:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs#L7)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Please rename this part of namespace to `ApplicationInsights`
</blockquote></details>

Done.
___
*[`Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs` line 14 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA2wcn3rImmSY3m5YF:-NsD7Jhi3DCZyHN8H8P5:b-uut2eq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs#L14)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

does it need to be a `long`? `int` should be sufficient
</blockquote></details>

It comes as long from azure, I didn't want to convert original value. Do you want convert it?
___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 178 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA39Z02tuWIYpnXxLl:-NsDIHMGAOnZ-civLwYq:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L178)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please add short comment to say this is used to authenticate query to App.Insights API
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm/Services/Debug/HlaExpansionFailuresService.cs` line 56 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA3ViP5kf0fbmot_Dc:-NsDIV1l-x-ssTI_X0N6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm/Services/Debug/HlaExpansionFailuresService.cs#L56)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

style: put each arg on its own line
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 73 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA25X44NXrUf3DvWv4:-NsDF-MVCB9E7q28WScv:b-5dy3cp) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L73)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

could use the more simple `JsonResult`, as we do on other debug endpoints
</blockquote></details>

I thought we needed formatter json here, like this: 

and not like this:

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: all files reviewed, 2 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 73 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA25X44NXrUf3DvWv4:-NsD_uSE8NCYNjAOIIE9:b-vwatdt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L73)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

I thought we needed formatter json here, like this: 

and not like this:

</blockquote></details>

I don't think formatting here is important - just the model used
___
*[`Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs` line 14 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA2wcn3rImmSY3m5YF:-NsD_ZWlEiSDVcyLOAMt:b-ky07kn) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.Debug.Client.Models/HlaExpansionFailures/HlaExpansionFailure.cs#L14)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

It comes as long from azure, I didn't want to convert original value. Do you want convert it?
</blockquote></details>

ok, leave as `long` then

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: all files reviewed, 3 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 56 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsDabAv06cdxTlcFJD4:-NsDabAv06cdxTlcFJD5:b-k50avm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5a3ed11d8675f64040577e203577d046ca5ec81e/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L56)):*
> ```Smalltalk
> 
>         [FunctionName(nameof(HlaExpansionFailures))]
>         public async Task<IActionResult> HlaExpansionFailures(
> ```

Please add `[ProducesResponseType(...` for swagger documentation

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA4rIW5tUATz8vTb0B:-NsDvX0g9Y-DGpBRUZRF:bg6v4qb) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Sorry, I missed this off the ticket, but last thing is, please add a new method to `MatchingAlgorithmFunctionsClient` in `Debug.Client` project to call the new query endpoint
</blockquote></details>

Done.

BTW, it would be useful to add test project to repository for testing debug clients. It could save time when we adding new method to client and need to quickly check if it works.

___
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 60 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA1m606N6bcTZGwcsP:-NsDwFvXAXzkpxO1h-vF:bx2nvqf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L60)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please remove the "get" from this portion of the route
</blockquote></details>

Was done in previous commit
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 73 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA25X44NXrUf3DvWv4:-NsDwJiE6_cA3jRnEuZ5:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7f7655d2a24ff3c6fce94378a97f178bd1d445a5/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L73)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I don't think formatting here is important - just the model used
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs` line 56 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsDabAv06cdxTlcFJD4:-NsDwLGtAKx8fboK6_f6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5a3ed11d8675f64040577e203577d046ca5ec81e/Atlas.MatchingAlgorithm.Functions/Functions/Debug/DonorFunctions.cs#L56)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Please add `[ProducesResponseType(...` for swagger documentation
</blockquote></details>

Done.

**Review by zabeen — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-NsA4rIW5tUATz8vTb0B:-NsE1tXI4j68YRTWCrR-:b-wbi29d) (no related file):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Done.

BTW, it would be useful to add test project to repository for testing debug clients. It could save time when we adding new method to client and need to quickly check if it works.
</blockquote></details>

I have something like on a local branch - I'll push up a PR and tag you

___

**Review by SergeyEzh — COMMENTED** [review]
@zabeen, I've rebased the branch to fix conflicts with master. Please take a peek. 

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248#-:-NsE6iZWB43GlyG22IGh:bnzhoy4)* status: 15 of 18 files reviewed, all discussions resolved (waiting on @zabeen)

**Review by zabeen — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1248)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
