### PR TITLE
feature: #805: Add match prediction request endpoint to match predict…

### PR DESCRIPTION
**Pull request by zabeen**
…ion API.

Early PR for first part of changes need to be able to run validation dataset through Atlas. Please see github issue for context.

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/808)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/808)* status: all files reviewed, 6 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithmValidator.cs` line 7 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzv4av-U2RgMuelF0g:-NBzv4av-U2RgMuelF0h:b-dz26a4) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithmValidator.cs#L7)):*
> ```Smalltalk
> namespace Atlas.MatchPrediction.ExternalInterface
> {
>     public interface IMatchPredictionValidator
> ```

Could you please add doccomments to these methods and specify the difference between the methods?
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/IdentifiedMatchPredictionRequest.cs` line 5 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzvReT8CAQ3dr2SMxs:-NBzvReT8CAQ3dr2SMxt:bduybmk) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/Models/IdentifiedMatchPredictionRequest.cs#L5)):*
> ```Smalltalk
> namespace Atlas.MatchPrediction.ExternalInterface.Models
> {
>     public class IdentifiedMatchPredictionRequest
> ```

Please add doccomments
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/MatchPredictionInitiationResponse.cs` line 3 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzvWhL3xfjgFnpxC6y:-NBzvWhL3xfjgFnpxC6z:bduybmk) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/Models/MatchPredictionInitiationResponse.cs#L3)):*
> ```Smalltalk
> namespace Atlas.MatchPrediction.ExternalInterface.Models
> {
>     public class MatchPredictionInitiationResponse
> ```

Please add doccomments
___
*[`terraform/core/modules/match_prediction/servicebus.tf` line 34 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NC--LUGAzNckXcDySmN:-NC--LUGAzNckXcDySmO:b-9x1q2f) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/terraform/core/modules/match_prediction/servicebus.tf#L34)):*
> ```HCL
>   dead_lettering_on_message_expiration = false
> }
> ```

extra new line
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs` line 22 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzvhcP6_VTvFdF4_Ou:-NBzvhcP6_VTvFdF4_Ov:bpp7skr) ([raw file](https://github.com/anthony-nolan/atlas/blob/682d443229a94d7c80c5e60441a67d8e9b5a21db/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs#L22)):*
> ```Smalltalk
>         /// Can actually represent multiple donors, provided they all share phenotypes and metadata 
>         /// </summary>
>         public DonorInput DonorInput { get; set; }
> ```

Why are we renaming this field? As I understand this is not just one Donor
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs` line 73 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzw4Wq0CwL3BO4tVXr:-NBzw4Wq0CwL3BO4tVXs:b-atfvo) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs#L73)):*
> ```Smalltalk
>     }
> 
>     public class IdentifiedMatchProbabilityRequest : MatchProbabilityRequest
> ```

please add doccomments to this class.
Is it correct that the only difference between IdentifiedMatchProbabilityRequest and MatchProbabilityRequest, is that IdentifiedMatchProbabilityRequest is run for a search?

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/808)* status: 25 of 28 files reviewed, 6 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.MatchPrediction/ExternalInterface/Models/IdentifiedMatchPredictionRequest.cs` line 5 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzvReT8CAQ3dr2SMxs:-NC-PN2AD92kBVeZQhWx:b-fr9j1i) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/Models/IdentifiedMatchPredictionRequest.cs#L5)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please add doccomments
</blockquote></details>

not sure this needs doccomments as `Identified...` is a model naming pattern used elsewhere in codebase for any input model where an ID has been assigned
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/MatchPredictionInitiationResponse.cs` line 3 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzvWhL3xfjgFnpxC6y:-NC-Pe4L5Bt1revQMVZ5:b8b0nfn) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/Models/MatchPredictionInitiationResponse.cs#L3)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please add doccomments
</blockquote></details>

again, following naming convention of `...InitiationResponse` used elsewhere in codebase
___
*[`terraform/core/modules/match_prediction/servicebus.tf` line 34 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NC--LUGAzNckXcDySmN:-NC-YNQa24HVwd_kk2Lg:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/terraform/core/modules/match_prediction/servicebus.tf#L34)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

extra new line
</blockquote></details>

Done.
___
*[`Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithmValidator.cs` line 7 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzv4av-U2RgMuelF0g:-NC-PAQd2GGFFGAOPv0L:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/MatchPredictionAlgorithmValidator.cs#L7)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Could you please add doccomments to these methods and specify the difference between the methods?
</blockquote></details>

Done.
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs` line 22 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzvhcP6_VTvFdF4_Ou:-NC-PkiKDXuoYXObNd1O:b-zgeego) ([raw file](https://github.com/anthony-nolan/atlas/blob/682d443229a94d7c80c5e60441a67d8e9b5a21db/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs#L22)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Why are we renaming this field? As I understand this is not just one Donor
</blockquote></details>

There is a second model just below this one where this prop is replaced with a List of the same type, and that prop is named `Donors`:

```
public class MultipleDonorMatchProbabilityInput : IdentifiedMatchProbabilityRequest
    {

        ...

        public List<DonorInput> Donors { get; set; }
```

So `Donor` is consistent with `Donors`. I will edit the comment to make it clearer.
___
*[`Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs` line 73 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/808#-NBzw4Wq0CwL3BO4tVXr:-NC-SRvnD4cXuYQkVD_a:b-s1x4lk) ([raw file](https://github.com/anthony-nolan/atlas/blob/5fc7345592b05cd8dc1ef45b85b5ffe55a3f0c5c/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityRequest.cs#L73)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

please add doccomments to this class.
Is it correct that the only difference between IdentifiedMatchProbabilityRequest and MatchProbabilityRequest, is that IdentifiedMatchProbabilityRequest is run for a search?
</blockquote></details>

yes; I wanted to make a new base class that didn't have the IDs used in main search, to allow for a cleaner "match prediction only" input model

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/808)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
