### PR TITLE
fix: #1186: don't update donor import file history on DuplicateDonorF…

### PR DESCRIPTION
**Pull request by SergeyEzh**
…ileImportException & test fix

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: all files reviewed, 4 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9K6p-IHIPU2lRFA6:-Nss9K6p-IHIPU2lRFA7:b-xvm801) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L162)):*
> ```Smalltalk
>         }
> 
>         private async Task NotifyOnFailure(DonorImportFile file, string message, string description)
> ```

Suggest rename to `FailImportAndNotify`



_Code quote:_
```Smalltalk
NotifyOnFailure
```
___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 168 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9pTo9eMBTVe4z3Aa:-Nss95KIE4VnYbLavEyn:b-38ta42) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L168)):*
> ```Smalltalk
>         }
> 
>         private async Task LogFileErrorAndSendAlert(DonorImportFile file, string message, string description, bool updateDonorImportHistory = true)
> ```

this param is not being used?



_Code quote:_
```Smalltalk
bool updateDonorImportHistory = true
```
___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 168 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-NssA2BDAGV-L_47_dcm:-NssA2BDAGV-L_47_dcn:bmdyrtr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L168)):*
> ```Smalltalk
>         }
> 
>         private async Task LogFileErrorAndSendAlert(DonorImportFile file, string message, string description, bool updateDonorImportHistory = true)
> ```

Rename method to `RegisterImportAsPermenantlyFailed`



_Code quote:_
```Smalltalk
LogFileErrorAndSendAlert
```
___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 172 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9bbq9h9Vjnj6ilu2:-Nss9bbq9h9Vjnj6ilu3:b-ubb7hq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L172)):*
> ```Smalltalk
>             await donorImportFileHistoryService.RegisterFailedDonorImportWithPermanentError(file);
>             logger.SendTrace(message, LogLevel.Warn);
>             await notificationSender.SendAlert(message, description, Priority.Medium, nameof(ImportDonorFile));
> ```

this line should be moved to method `SendFailedImportMessage` - and then rename that method to `SendFailureMessages`, so it will cover sending of both the import message and alert message



_Code quote:_
```Smalltalk
await notificationSender.SendAlert(message, description, Priority.Medium, nameof(ImportDonorFile));
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9K6p-IHIPU2lRFA6:-NssDnp_1fMkZL_iks52:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L162)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Suggest rename to `FailImportAndNotify`
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 168 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9pTo9eMBTVe4z3Aa:-NssDoio4bnsV9NWQvxz:bsyh9wr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L168)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

this param is not being used?
</blockquote></details>

Removed. It survived during cleanup
___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 168 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-NssA2BDAGV-L_47_dcm:-NssExGD1-J_IjOegmSg:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L168)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Rename method to `RegisterImportAsPermenantlyFailed`
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 172 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9bbq9h9Vjnj6ilu2:-NssGWET4QhbgP9NOGoQ:b-4iyrh4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L172)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

this line should be moved to method `SendFailedImportMessage` - and then rename that method to `SendFailureMessages`, so it will cover sending of both the import message and alert message
</blockquote></details>

It will change logic in `catch` block for general exception. Currently it doesn't send an alert, it will with requested change. 

Is it acceptable? 
Do we need send an alert in out current case (`DuplicateDonorFileImportException`)

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 172 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9bbq9h9Vjnj6ilu2:-NssIybo0T-A7UFYKg9I:bs7k64w) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L172)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

It will change logic in `catch` block for general exception. Currently it doesn't send an alert, it will with requested change. 

Is it acceptable? 
Do we need send an alert in out current case (`DuplicateDonorFileImportException`)
</blockquote></details>

yes, alert should be sent out on duplicate exception - that was happening before, and should continue.

as for general exception...in this case, the exception is thrown leading to message replay. If the failures are caused by a transient issue, like a sleeping db, we don't want 4 or 5 alert messages going out for something that eventually resolves itself... So I would say we should continue to _not_ send an alert out for a general exception.

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 172 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-Nss9bbq9h9Vjnj6ilu2:-NssKk1H4BTghT65OpRL:b-hzw77k) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/24d48b5092a84ac2d6beb95ea68f7187d88e7002/Atlas.DonorImport/Services/DonorFileImporter.cs#L172)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

yes, alert should be sent out on duplicate exception - that was happening before, and should continue.

as for general exception...in this case, the exception is thrown leading to message replay. If the failures are caused by a transient issue, like a sleeping db, we don't want 4 or 5 alert messages going out for something that eventually resolves itself... So I would say we should continue to _not_ send an alert out for a general exception.
</blockquote></details>

Having written all that out, I don't think it's the end of the world if an alert doesn't get sent out for duplicate exception, because the user will be notified of the failure via import result message. So the failure will be identified, but a support agent won't be notified of it - which I think is ok.

**Review by zabeen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 139 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-NssLVFX3pQMZ5Se6LuB:-NssLVFX3pQMZ5Se6LuC:b-3va97o) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/488e12ad9c8b8f7bd63027af41057cf4b13ab7ab/Atlas.DonorImport/Services/DonorFileImporter.cs#L139)):*
> ```Smalltalk
>             catch (DuplicateDonorFileImportException e)
>             {
>                 await SendFailedImportMessage(file.FileLocation, e.Message);
> ```

it's worth adding a comment here to say we are intentionally not failing the import

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 139 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-NssLVFX3pQMZ5Se6LuB:-NssLwdnC8wupvbgRTm7:bwl4qc6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/488e12ad9c8b8f7bd63027af41057cf4b13ab7ab/Atlas.DonorImport/Services/DonorFileImporter.cs#L139)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

it's worth adding a comment here to say we are intentionally not failing the import
</blockquote></details>

Do you think so? There's bunch `catch` blocks doing the same (I mean not failing the import). This one just wasn't working because exception was thrown from outside of `try` block

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 139 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-NssLVFX3pQMZ5Se6LuB:-NssMpKMAY6dyVFAsmD-:bwucn55) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/488e12ad9c8b8f7bd63027af41057cf4b13ab7ab/Atlas.DonorImport/Services/DonorFileImporter.cs#L139)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Do you think so? There's bunch `catch` blocks doing the same (I mean not failing the import). This one just wasn't working because exception was thrown from outside of `try` block
</blockquote></details>

only this block and the general block are not using `FailImportAndNotify` - so I think it's worth explaining briefly why it's the outlier, i.e., as no new record was created in this instance, there is no import record to fail

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.DonorImport/Services/DonorFileImporter.cs` line 139 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259#-NssLVFX3pQMZ5Se6LuB:-NssSSxOA5SrbVg85JLA:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/488e12ad9c8b8f7bd63027af41057cf4b13ab7ab/Atlas.DonorImport/Services/DonorFileImporter.cs#L139)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

only this block and the general block are not using `FailImportAndNotify` - so I think it's worth explaining briefly why it's the outlier, i.e., as no new record was created in this instance, there is no import record to fail
</blockquote></details>

Done.

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
