### PR TITLE
#958 Document the exact meaning of existing search times

### PR DESCRIPTION
**Pull request by disaev-nmdp**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969)* status: all files reviewed, 1 unresolved discussion (waiting on @disaev-nmdp)

___
*[`Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs` line 17 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969#-NVe8aPl8vTtpovu4CRV:-NVe8aPl8vTtpovu4CRW:bwwqb33) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6f2e8399f1cb512d1717b81ccc7725770b11196/Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs#L17)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Total time taken to run the match prediction algorithm for all results
> ```

am I correct, this only covers the time taken to process all match prediction requests - it does not cover any orchestration, such as downloading matching results, or persisting the final merged results?

**Review by disaev-nmdp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs` line 17 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969#-NVe8aPl8vTtpovu4CRV:-NVnIa6KAu7-LE98xrzX:bvpr8mh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6f2e8399f1cb512d1717b81ccc7725770b11196/Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

am I correct, this only covers the time taken to process all match prediction requests - it does not cover any orchestration, such as downloading matching results, or persisting the final merged results?
</blockquote></details>

Correct, timer start time is right after match prediction batches were prepared and before RunMatchPredictionAlgorithm is run,. Timer finish time is the very end of RunMatchPredictionAlgorithm function. It does not include  any orhcestration time

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969)* status: all files reviewed, 1 unresolved discussion (waiting on @disaev-nmdp)

___
*[`Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs` line 17 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969#-NVe8aPl8vTtpovu4CRV:-NW1n-1v70FGbJM4u6b_:b-5fkfpf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6f2e8399f1cb512d1717b81ccc7725770b11196/Atlas.Client.Models/Search/Results/ResultSet/SearchResultSet.cs#L17)):*
<details><summary><i>Previously, disaev-nmdp wrote…</i></summary><blockquote>

Correct, timer start time is right after match prediction batches were prepared and before RunMatchPredictionAlgorithm is run,. Timer finish time is the very end of RunMatchPredictionAlgorithm function. It does not include  any orhcestration time
</blockquote></details>

Thanks, please then update comment to "Total time taken to process all match prediction requests for all results - excludes any orchestration time that takes place before or after this step"

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/969)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @disaev-nmdp)

**Pull request merged**
