### PR TITLE
feature: #1052: Migration to Azure.Data.Tables

### PR DESCRIPTION
**Pull request by SergeyEzh**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361#-O4tHjoY1PD1GVvjxXgy:-O4tHjoY1PD1GVvjxXgz:b-amwjdr) (no related file):*
Started the system tests, will merge this PR if they pass

___

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361#-O4tHs9JDrepEFLStj31:-O4tHs9JDrepEFLStj32:b-vx1oax) (no related file):*
The target for this PR should be rc/3.0.0

___

**Review by daria-sorokina-da — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361#-O4tHjoY1PD1GVvjxXgy:-O4tR26LAtT7a7oWaDaN:bb6un1j) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Started the system tests, will merge this PR if they pass
</blockquote></details>

Done

___

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @pchenery)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361#-O4tHs9JDrepEFLStj31:-O5DbUiE-MPkWPtTQf0c:b-bmvrvs) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

The target for this PR should be rc/3.0.0
</blockquote></details>

re targeted

___

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361#-O4tHs9JDrepEFLStj31:-O5Dcpmp2TyJt16eM9CA:bnrkuvk) (no related file):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

re targeted
</blockquote></details>

Just re-targeting will not help as the base branch is incorrect.
Please create a new branch, and cherry-pick the needed commits

___

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @pchenery)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361#-O4tHs9JDrepEFLStj31:-O5Dg8rfE5s7RIRa2L3E:bjip5ub) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Just re-targeting will not help as the base branch is incorrect.
Please create a new branch, and cherry-pick the needed commits
</blockquote></details>

rebased this one. check, it should be good now.

___

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1361)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
