### PR TITLE
feature: CBT-2499: Extend message response model with last sequence n…

### PR DESCRIPTION
**Pull request by pchenery**
…umber

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.Common/Debugging/ServiceBusPeeker.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346#-O3DKBpTCMkwCaR6w1qT:-O3DKBpTCMkwCaR6w1qU:buhbher) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/62e3ac4faa3f460df49e9a538cad50479dfeaf23/Atlas.Common/Debugging/ServiceBusPeeker.cs#L68)):*
> ```Smalltalk
>                 MessageCount = messages.Count,
>                 PeekedMessages = messages,
>                 LastSequenceNumber = fromSequenceNumber - 1
> ```

This should be the sequence number of the last message that you peeked - smth like `batch.LastOrDefault()?.SystemProperties.SequenceNumber`

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.Common/Debugging/ServiceBusPeeker.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346#-O3DKBpTCMkwCaR6w1qT:-O3DKs2g3od3-sl-qBGU:b-qufnu) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/62e3ac4faa3f460df49e9a538cad50479dfeaf23/Atlas.Common/Debugging/ServiceBusPeeker.cs#L68)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This should be the sequence number of the last message that you peeked - smth like `batch.LastOrDefault()?.SystemProperties.SequenceNumber`
</blockquote></details>

Agreed, tried to do something like that but batch is not in scope at that point so wasn't sure whether to move it out of the loop or not. Obviously happy to do that if you'd prefer?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.Common/Debugging/ServiceBusPeeker.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346#-O3DKBpTCMkwCaR6w1qT:-O3DYk-79jz0N8zQSb3S:b2iq91o) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/62e3ac4faa3f460df49e9a538cad50479dfeaf23/Atlas.Common/Debugging/ServiceBusPeeker.cs#L68)):*
<details><summary><i>Previously, pchenery wrote…</i></summary><blockquote>

Agreed, tried to do something like that but batch is not in scope at that point so wasn't sure whether to move it out of the loop or not. Obviously happy to do that if you'd prefer?
</blockquote></details>

ah, sorry - read it once again - I think it's ok then, just hard to read.
what I suggest doing:
```
            var messages = new List<T>();
            long? lastSequenceNumber = null;
            var fromSequenceNumber = peekRequest.FromSequenceNumber;

            // The message receiver Peek method has an undocumented upper message count limit
            // So, keep fetching until desired total message count reached or no new messages returned
            while (messages.Count < peekRequest.MessageCount)
            {
                var messageCount = peekRequest.MessageCount - messages.Count;
                var batch = await messageReceiver.PeekBySequenceNumberAsync(fromSequenceNumber, messageCount);

                if (!batch.Any())
                {
                    break;
                }

                messages.AddRange(batch.Select(GetServiceBusMessage));
                lastSequenceNumber = batch.Select(m => m.SystemProperties.SequenceNumber).MaxBy(i => i);
                fromSequenceNumber = lastSequenceNumber + 1;
            }

            return new PeekServiceBusMessagesResponse<T>
            {
                MessageCount = messages.Count,
                PeekedMessages = messages,
                LastSequenceNumber = lastSequenceNumber 
            };

```

This will make the code much easier to understand

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.Common/Debugging/ServiceBusPeeker.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346#-O3DKBpTCMkwCaR6w1qT:-O3Dbie99r-dOuZM_v9L:b-ucfknh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/62e3ac4faa3f460df49e9a538cad50479dfeaf23/Atlas.Common/Debugging/ServiceBusPeeker.cs#L68)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

ah, sorry - read it once again - I think it's ok then, just hard to read.
what I suggest doing:
```
            var messages = new List<T>();
            long? lastSequenceNumber = null;
            var fromSequenceNumber = peekRequest.FromSequenceNumber;

            // The message receiver Peek method has an undocumented upper message count limit
            // So, keep fetching until desired total message count reached or no new messages returned
            while (messages.Count < peekRequest.MessageCount)
            {
                var messageCount = peekRequest.MessageCount - messages.Count;
                var batch = await messageReceiver.PeekBySequenceNumberAsync(fromSequenceNumber, messageCount);

                if (!batch.Any())
                {
                    break;
                }

                messages.AddRange(batch.Select(GetServiceBusMessage));
                lastSequenceNumber = batch.Select(m => m.SystemProperties.SequenceNumber).MaxBy(i => i);
                fromSequenceNumber = lastSequenceNumber + 1;
            }

            return new PeekServiceBusMessagesResponse<T>
            {
                MessageCount = messages.Count,
                PeekedMessages = messages,
                LastSequenceNumber = lastSequenceNumber 
            };

```

This will make the code much easier to understand
</blockquote></details>

Thanks!

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1346)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
