### PR TITLE
Stop automatically assigning mismatch grade and count to expressing vs. null allele case

### PR DESCRIPTION
**Pull request by zabeen**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1153)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
Instead, assign new "neutral" match grade of `Expressing vs. Null` and treat locus as homozygous when calculating match count during scoring.

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1153#-:-Nls5orU3GMla4ZsdUKr:b-e6wf2u)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @daria-sorokina-da)

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1153)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @daria-sorokina-da)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1153#-Nls6BU43Cz6qUcP_Mcj):*
FYI, not a typo, it is for a tech debt ticket in backlog with this ID



_Code quote:_
```
1014:
```

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
