### PR TITLE
822 donor import messaging

### PR DESCRIPTION
**Pull request by zabeen**
Please read https://github.com/Anthony-Nolan/Atlas/issues/822 for bug details and HLD. I went with solution 3, as it seemed the most robust and clean approach,

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: 0 of 40 files reviewed, 1 unresolved discussion

___
*[`Atlas.DonorImport.Test.Integration/IntegrationTests/Import/TransactionScopeErrorTests.cs` line 18 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NEw9OAwCKiLevC7Cj0L:-NEw9OAwCKiLevC7Cj0M:b8j5mvf) ([raw file](https://github.com/anthony-nolan/atlas/blob/82b66176378b5c2092fe501869319c891ef12abc/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/TransactionScopeErrorTests.cs#L18)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// These tests exist to test a specific interaction with service bus clients and transaction scope.
> ```

service bus client no longer being called during donor import, so these tests are now not needed

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NF8Stxu9ub5TUBzNPBz:b-5czsip) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
> currently the donors are processed in two databases - A and B. Should we track that as well

The donor management function on matching algorithm already tracks changes to donors, so no change needed.


> Instead of deleting, let's add a flag

I don't mind updating instead of deleting, but my only concern is that the table will just grow and grow, and the index will also grow, at some point querying/update speed may be impacted; especially when considering WMDA use case where they have many more donors than AN, and they update much more frequently (every time a member registry uploads a donor file).

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NF8XTyj-Fkmr0IS98ME:bx23v48) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

> currently the donors are processed in two databases - A and B. Should we track that as well
The donor management function on matching algorithm already tracks changes to donors, so no change needed.


> Instead of deleting, let's add a flag
I don't mind updating instead of deleting, but my only concern is that the table will just grow and grow, and the index will also grow, at some point querying/update speed may be impacted; especially when considering WMDA use case where they have many more donors than AN, and they update much more frequently (every time a member registry uploads a donor file).

</blockquote></details>

Even though rows are deleted, the messages are being published to a topic, and so a copy will remain on the `audit` sub, so there will be a trail remaining for debug/support purposes.
___
*[`terraform/core/modules/donor_import/function.tf` line 32 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF7wGb9CnhAFQ71xlCN:-NF8V3qbBE4SLfQjxnKH:b-dfd59t) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/terraform/core/modules/donor_import/function.tf#L32)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This setting has been renamed in code, so it needs to be renamed in the terraform, right?
</blockquote></details>

ah, yes, thanks! Great catch! :) Done

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: 34 of 42 files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Qpd-1yBVCfcvxem:-NF8agbQ55PtTJPQZMZC:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Can we have DonorId in this table as well in case we need to debug the data flow? 
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NFD__dtAuIXuryGDvMC:bo67usv) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Even though rows are deleted, the messages are being published to a topic, and so a copy will remain on the `audit` sub, so there will be a trail remaining for debug/support purposes.
</blockquote></details>

I think it's quite hard to navigate/search the audit sub, and also we need to set a reasonable TTL for it, so we definitely don't want to use audit sub for data storage

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NFDo8CY8GjbLNdBmtVJ:b6a4foe) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think it's quite hard to navigate/search the audit sub, and also we need to set a reasonable TTL for it, so we definitely don't want to use audit sub for data storage
</blockquote></details>

So if we go with the update approach, how best to deal with the fact that the table will only grow, possibly by 10s of thousands of rows a day (WMDA use case)? A filtered index will probably keep the index size small, filtering by those updates where `IsPublished` is `false`,

should I have a second method that deletes rows older than 30days? Or maybe longer?

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NFDpXJ51RktjBhKrucF:b-cqfgg5) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

So if we go with the update approach, how best to deal with the fact that the table will only grow, possibly by 10s of thousands of rows a day (WMDA use case)? A filtered index will probably keep the index size small, filtering by those updates where `IsPublished` is `false`,

should I have a second method that deletes rows older than 30days? Or maybe longer?
</blockquote></details>

date cutoff could be configurable, I guess

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NFE426r2PVQRQMjBHs1:b-wqv84b) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

date cutoff could be configurable, I guess
</blockquote></details>

Yes, let's do that
1) add DateTime AddedDateUtc
2) add bool IsPublished
3) add DateTime? PublishedDateUtc
4) add index by IsPublished to retrieve items which are false
5) add index by AddedDateUtc
6) add a scheduled job (once a day) to clean up data older than X days (configurable). If configuration setting is NULL, we do not clean up the data (default - 30 days)

This way we will be able to research any "missing donors" issues in case they occur.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: 24 of 58 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 17 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NF83Zh4-Rsp14lZrt_6:-NFK2k4I0QsldHtlSpCN:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/7c590b2b69b9e2727cb9cdf53cf6e473d3f84d77/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L17)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Yes, let's do that
1) add DateTime AddedDateUtc
2) add bool IsPublished
3) add DateTime? PublishedDateUtc
4) add index by IsPublished to retrieve items which are false
5) add index by AddedDateUtc
6) add a scheduled job (once a day) to clean up data older than X days (configurable). If configuration setting is NULL, we do not clean up the data (default - 30 days)

This way we will be able to research any "missing donors" issues in case they occur.
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 38 of 38 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 2 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NFNSwQi83rVhRZimWQQ:-NFNSwQi83rVhRZimWQR:bp84jpw) (no related file):*
Could you please check that all new configuration settings got into https://github.com/Anthony-Nolan/Atlas/blob/master/README_Configuration.md

___
___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 41 at r3](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NFNRKJz01KFo0BZyLJP:-NFNRKJz01KFo0BZyLJQ:b-5ak646) ([raw file](https://github.com/anthony-nolan/atlas/blob/6baab38bf7a948c0211c3a09fb98ea7927dd0495/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L41)):*
> ```Smalltalk
>             model.Property(x => x.CreatedOn).HasDefaultValueSql("GETUTCDATE()");
> 
>             model
> ```

I suppose we also need an index on IsPublished, PublishedOn for deletion

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: 60 of 64 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs` line 41 at r3](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NFNRKJz01KFo0BZyLJP:-NFOhzkX5QjED9VIBA77:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6baab38bf7a948c0211c3a09fb98ea7927dd0495/Atlas.DonorImport.Data/Models/PublishableDonorUpdate.cs#L41)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I suppose we also need an index on IsPublished, PublishedOn for deletion
</blockquote></details>

Done.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: 60 of 64 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/823#-NFNSwQi83rVhRZimWQQ:-NFOs2-l4QV0tCFC_w0a:b-896fix) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Could you please check that all new configuration settings got into https://github.com/Anthony-Nolan/Atlas/blob/master/README_Configuration.md
</blockquote></details>

Done.

___

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
