### PR TITLE
Run all apps on one plan

### PR DESCRIPTION
**Pull request by zabeen**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1269)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1269)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`terraform/core/variables.tf` line 378 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1269#-NuUxtCS5tC1KvKfmMsA:-NuUxtCS5tC1KvKfmMsB:b-igopeg) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0b81c0d3d4a22affbeb574f9e36605deff481801/terraform/core/variables.tf#L378)):*
> ```HCL
> }
> 
> variable "SERVICE_PLAN_SKU" {
> ```

FYI: removed this unused var

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Review by SergeyEzh — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by alikhanmda — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
