### PR TITLE
feature: #931: Change logic for processing matching results - process…

### PR DESCRIPTION
**Pull request by IgorKupreychik**
… matching results blobs one by one instead of processing all together

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933)* status: all files reviewed, 6 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/SearchResultsBlobStorageClient.cs` line 34 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFqc0IAEUfhhE5xj-k:-NSFqc0J4O8SjoW2CpEO:bowp3io) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Common/AzureStorage/Blob/SearchResultsBlobStorageClient.cs#L34)):*
> ```Smalltalk
>         public async Task UploadResults<T>(T results, string blobContainerName, string fileName)
>         {
>             // Results will not be serialised if results are being batched
> ```

I don't understand this comment - what does it mean?
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 129 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFxuZ0EIBFpwlPd2SK:-NSFxuZ0EIBFpwlPd2SL:b-377gmc) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L129)):*
> ```Smalltalk
> 
>             resultSet.BlobStorageContainerName = resultSet.IsRepeatSearchSet ? azureStorageSettings.RepeatSearchResultsBlobContainer : azureStorageSettings.SearchResultsBlobContainer;
>             resultSet.BatchedResult = matchingResultsNotification.ResultsBatched && azureStorageSettings.ResultsShouldBeBatched;
> ```

The flag value here does not match the value that's passed in ProcessSearchResults. I think we should only look at azureStorageSettings.ResultsShouldBeBatched at this stage - it does not matter whether the results on previous stages were batched or not
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 131 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFxa320zxJuk2KSUzT:-NSFxa320zxJuk2KSUzU:b-dpckir) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L131)):*
> ```Smalltalk
>             resultSet.BatchedResult = matchingResultsNotification.ResultsBatched && azureStorageSettings.ResultsShouldBeBatched;
> 
>             resultSet.Results ??= await logger.RunTimedAsync("Combining search results", async () =>
> ```

resultSet.Results will always be null on this step - wouldn't it? Then do we need `??=`?
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFzojv4_qLlj_WT5rW:-NSFzojv4_qLlj_WT5rX:b-8qxndq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L162)):*
> ```Smalltalk
>             var batchNumber = 0;
> 
>             await foreach (var matchingResults in matchingResultsDownloader.DownloadResults(isRepeatSearch, batchFolder))
> ```

What if matching results are not batched - will this code still work? Previously, matchingResultsDownloader.Download could download results from single blob as well as from a folder
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 169 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSG-Vjj2JNqpHYWdZcr:-NSG-Vjj2JNqpHYWdZcs:bdw3589) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L169)):*
> ```Smalltalk
>                 );
> 
>                 var currentSearchResults = await resultsCombiner.CombineResults(searchRequestId, matchingResults, donorInfo, matchPredictionResultLocations.Where(l => donorIds.Contains(l.Key)).ToDictionary());
> ```

Could you please create a separate variable for readability?

`var currentMatchPredictionResultLocations = matchPredictionResultLocations.Where(l => donorIds.Contains(l.Key)).ToDictionary();`
___
*[`Atlas.Functions/Settings/AzureStorageSettings.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSG0ry87iO5CmatqqCk:-NSG0ry87iO5CmatqqCl:b-nusgew) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/Settings/AzureStorageSettings.cs#L15)):*
> ```Smalltalk
>         public string MatchPredictionResultsBlobContainer { get; set; }
> 
>         public bool ResultsShouldBeBatched { get; set; }
> ```

Let's call it ShouldBatchResults to match other similar settings

**Comment by IgorKupreychik** [comment]
*[`Atlas.Common/AzureStorage/Blob/SearchResultsBlobStorageClient.cs` line 34 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFqc0IAEUfhhE5xj-k:-NSG3TouCnwAm9DZpkwK:bz67t5c) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Common/AzureStorage/Blob/SearchResultsBlobStorageClient.cs#L34)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I don't understand this comment - what does it mean?
</blockquote></details>

When results are being batched, the field 'Result' of the object results will not be serialized. Zabeen asked to add this comment, if you think it doesn't make sense - please let me know and I'll remove it.

**Comment by IgorKupreychik** [comment]
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 131 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFxa320zxJuk2KSUzT:-NSG4RLF94Bv0O8diL6c:b-h47usp) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L131)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

resultSet.Results will always be null on this step - wouldn't it? Then do we need `??=`?
</blockquote></details>

If Results were not batched - then it won't be null

**Comment by IgorKupreychik** [comment]
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFzojv4_qLlj_WT5rW:-NSG4iw1-PUd-9nHBgGT:b-hg6dyo) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L162)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What if matching results are not batched - will this code still work? Previously, matchingResultsDownloader.Download could download results from single blob as well as from a folder
</blockquote></details>

It won't be even called in this case, results will be downloaded as part of matchingResultsSummary object

**Comment by IgorKupreychik** [comment]
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 129 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933#-NSFxuZ0EIBFpwlPd2SK:-NSG57TR70rlv8UUeVSv:b-5af9s) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/198e7accc280ebd41820688c993b4c1461d80d89/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L129)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

The flag value here does not match the value that's passed in ProcessSearchResults. I think we should only look at azureStorageSettings.ResultsShouldBeBatched at this stage - it does not matter whether the results on previous stages were batched or not
</blockquote></details>

If results on previous stage weren't batched - we won't be able to batch them here (regardless of the value of azureStorageSettings.ResultsShouldBeBatched)

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
