### PR TITLE
feature: CBT-2878: Fix url for matching funtion scoring client

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.MatchingAlgorithm/Clients/Scoring/MatchingAlgorithmScoringFunctionsClient.cs` line 23 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385#-OCm_5699cmn1eIjQbos:-OCm_56A1x3XSYSHmbHA:b-ubqpn1) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9e38b1b2d48ffdd39218effcb4e5f6c08404c72f/Atlas.MatchingAlgorithm/Clients/Scoring/MatchingAlgorithmScoringFunctionsClient.cs#L23)):*
> ```Smalltalk
>         public async Task<ScoringResult> Score(DonorHlaScoringRequest request)
>         {
>             return await PostRequest<DonorHlaScoringRequest, ScoringResult>("Score", request);
> ```

What about this one? Shouldn't we add "API" here as well?

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.MatchingAlgorithm/Clients/Scoring/MatchingAlgorithmScoringFunctionsClient.cs` line 23 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385#-OCm_5699cmn1eIjQbos:-OCma9t16RS9TUSTYUmg:bfo2kx3) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9e38b1b2d48ffdd39218effcb4e5f6c08404c72f/Atlas.MatchingAlgorithm/Clients/Scoring/MatchingAlgorithmScoringFunctionsClient.cs#L23)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Sorry, "api"
</blockquote></details>

definitely, sorry

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)* status: 0 of 1 files reviewed, all discussions resolved

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
