### PR TITLE
chore: Add ability to specify additional subscriptions for search-results-ready Service Bus topic

### PR DESCRIPTION
**Pull request by daria-sorokina-da**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025)

### CODE REVIEW

**Review by daria-sorokina-da — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025)* status: 0 of 3 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025#-NalNBU-D4SV7B5uUT03:-NalNBU-D4SV7B5uUT04:b-127k3z) (no related file):*
Fixing the build

___

**Review by daria-sorokina-da — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025)* status: 0 of 3 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025#-NalNBU-D4SV7B5uUT03:-NalNkJADcUbQ0E3gA0-:bb6un1j) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Fixing the build
</blockquote></details>

Done

___

**Review by IgorKupreychik — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025#-:-NapTN_hAyYl_qStPFuB:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @luken-an, @seanmobrien, and @zabeen)

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @luken-an, @seanmobrien, and @zabeen)

**Pull request merged**
