### PR TITLE
feature: #805: run batches of queued match prediction requests via ne…

### PR DESCRIPTION
**Pull request by zabeen**
…w match prediction function.

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 48 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`terraform/core/modules/match_prediction/variables_release.tf` line 24 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCxrAyy-HwkHAB2k9G9:-NCxqok94850jXPBQNbB:b-18t5t9) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/modules/match_prediction/variables_release.tf#L24)):*
> ```HCL
> }
> 
> variable "SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS" {
> ```

This variable would differ on DEV/UAT and LIVE?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: all files reviewed, 2 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCxs68rBFF9ozqLpUqW:-NCxs68rBFF9ozqLpUqX:b97mot1) (no related file):*
Please add info about all new feature flags into https://github.com/Anthony-Nolan/Atlas/blob/master/README_Configuration.md

___

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: all files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @zabeen)

___
*[`terraform/core/modules/match_prediction/variables_release.tf` line 24 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCxrAyy-HwkHAB2k9G9:-NCyJFnEECX4SIXoikgF:b-o0jcsg) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/modules/match_prediction/variables_release.tf#L24)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This variable would differ on DEV/UAT and LIVE?
</blockquote></details>

no, it wouldn't, and I was in 2 minds about adding it as a release var to both match prediction and search. But I wasn't sure whether hard-coding it to `false` and `true`, respectively, within the terraform function definitions was a good idea, either - even though the values shouldn't really be changed without very good reason (most likely involving more dev changes).

I am happy to hard-code the values and remove the release vars. What do you think?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: all files reviewed, 4 unresolved discussions (waiting on @zabeen)

___
*[`terraform/core/main.tf` line 182 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCyTfc58szwRR761enH:-NCyTfc58szwRR761enI:b7j9epa) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/main.tf#L182)):*
> ```HCL
>   IP_RESTRICTION_SETTINGS                             = var.IP_RESTRICTION_SETTINGS
>   MAC_SOURCE                                          = var.MAC_SOURCE
>   SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS = var.MATCH_PREDICTION_SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS
> ```

Suppose, we can remove SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS from release variables
___
*[`terraform/core/modules/match_prediction/function.tf` line 36 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCyTKmB4YBQUw0DlgKj:-NCyTKmB4YBQUw0DlgKk:b6g6m6p) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/modules/match_prediction/function.tf#L36)):*
> ```HCL
>     "MessagingServiceBus:ImportFileSubscription"                               = azurerm_servicebus_subscription.haplotype-frequency-file-processor.name
>     "MessagingServiceBus:ImportFileTopic"                                      = azurerm_servicebus_topic.haplotype-frequency-file-uploads.name
>     "MatchPredictionAlgorithm:SuppressCompressedPhenotypeConversionExceptions" = var.SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS
> ```

can we use MATCH_PREDICTION_SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS here?
___
*[`terraform/core/modules/match_prediction/variables_release.tf` line 24 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCxrAyy-HwkHAB2k9G9:-NCyRase-lQkXW-vvjsF:b-bgi7ea) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/modules/match_prediction/variables_release.tf#L24)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

no, it wouldn't, and I was in 2 minds about adding it as a release var to both match prediction and search. But I wasn't sure whether hard-coding it to `false` and `true`, respectively, within the terraform function definitions was a good idea, either - even though the values shouldn't really be changed without very good reason (most likely involving more dev changes).

I am happy to hard-code the values and remove the release vars. What do you think?
</blockquote></details>

Can we just use MATCH_PREDICTION_SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS where SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS is used and remove this from release variables?

This way, it would default to false for match predictions

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: 43 of 48 files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCxs68rBFF9ozqLpUqW:-NCyYq_V6JnzRM3Vyycg:b-kio22w) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please add info about all new feature flags into https://github.com/Anthony-Nolan/Atlas/blob/master/README_Configuration.md
</blockquote></details>

I've removed the release vars/feature flags, please see latest commit message

___
___
*[`terraform/core/main.tf` line 182 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCyTfc58szwRR761enH:-NCyYZ1HEXIRBiDUyXLz:bb7f2mf) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/main.tf#L182)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Suppose, we can remove SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS from release variables
</blockquote></details>

done
___
*[`terraform/core/modules/match_prediction/function.tf` line 36 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCyTKmB4YBQUw0DlgKj:-NCyY_aN3vWlqd4hevLu:b-cp4o7q) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/modules/match_prediction/function.tf#L36)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

can we use MATCH_PREDICTION_SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS here?
</blockquote></details>

I've removed the release vars, please see latest commit message
___
*[`terraform/core/modules/match_prediction/variables_release.tf` line 24 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCxrAyy-HwkHAB2k9G9:-NCyYiTj7lAaLkOMjbfG:b-g4ahi4) ([raw file](https://github.com/anthony-nolan/atlas/blob/488ae79658484dc44fc4291bbef9cc72830e9daa/terraform/core/modules/match_prediction/variables_release.tf#L24)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Can we just use MATCH_PREDICTION_SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS where SUPPRESS_COMPRESSED_PHENOTYPE_CONVERSION_EXCEPTIONS is used and remove this from release variables?

This way, it would default to false for match predictions
</blockquote></details>

I've removed the release vars, please see latest commit  message

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`terraform/core/modules/match_prediction/function.tf` line 38 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCyjk-96OLb4tUX2UdM:-NCyjk-G2m3UPIw6Qr1Q:b-3x0ul0) ([raw file](https://github.com/anthony-nolan/atlas/blob/ea32ac19577c7043af418f0f2b7db63bda5804c9/terraform/core/modules/match_prediction/function.tf#L38)):*
> ```HCL
>     
>     // Compressed phenotype conversion exceptions should NOT be suppressed when running match prediction requests outside of search
>     "MatchPredictionAlgorithm:SuppressCompressedPhenotypeConversionExceptions" = true
> ```

shouldn't this be false as it should not be suppressed?

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`terraform/core/modules/match_prediction/function.tf` line 38 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/810#-NCyjk-96OLb4tUX2UdM:-NCyw9WpAWmm6RAEMpKY:b-pu7a8a) ([raw file](https://github.com/anthony-nolan/atlas/blob/ea32ac19577c7043af418f0f2b7db63bda5804c9/terraform/core/modules/match_prediction/function.tf#L38)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

shouldn't this be false as it should not be suppressed?
</blockquote></details>

Done. :facepalm:

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/810)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
