### PR TITLE
fix: #1108: "MatchingDonorInfo" contains unupdated donor data in repe…

### PR DESCRIPTION
**Pull request by IgorKupreychik**
…at-search-results json file after donor data update before repeat search request

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

___
*[`Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs` line 195 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109#-NhfW6o8DsTpuW3Iaw1F:-NhfW6o8DsTpuW3Iaw1G:b-2eneom) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2316268246894268693c7ff82d39eeafa32caba5/Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs#L195)):*
> ```Smalltalk
>         // If we can identify all donors that need their type updating in one go, then this approach is drastically faster.
>         // ~0.04 seconds to update 333 records vs. ~1.2 seconds to updated 333 records even in a single connection.
>         private static async Task UpdateDonorTypes(List<DonorInfo> donorInfos, IDbConnection connection)
> ```

Is this method used? If not, let's remove it as it only updates the type

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs` line 195 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109#-NhfW6o8DsTpuW3Iaw1F:-NhfXvjDEq1PMEBjWkap:b-bvlncf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2316268246894268693c7ff82d39eeafa32caba5/Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs#L195)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Is this method used? If not, let's remove it as it only updates the type
</blockquote></details>

I don't see any references to it, so it's likely not used (unless it's called via some extravagant way like using reflection)

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

___
*[`Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs` line 195 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109#-NhfW6o8DsTpuW3Iaw1F:-NhfYPEK7V4U98xru2AZ:b-9kj6q6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2316268246894268693c7ff82d39eeafa32caba5/Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs#L195)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

I don't see any references to it, so it's likely not used (unless it's called via some extravagant way like using reflection)
</blockquote></details>

Let's remove it then. I don't think it's called via reflection

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
