### PR TITLE
feature: #1274: CBT-1472: Add migration for search tracking tables

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking.Data/Migrations/20240522082237_AddSearchTrackingSchemaAndTables.cs` line 33 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311#-Ny_nyvW7hPKBbWY_TM8:-Ny_nyvX2BEfJl1gTAzw:bd631nv) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ff6170558f6fe6a0ab142d6aeb20e2675e8c6115/Atlas.SearchTracking.Data/Migrations/20240522082237_AddSearchTrackingSchemaAndTables.cs#L33)):*
> ```Smalltalk
>                     MatchingAlgorithm_FailureInfo_Json = table.Column<string>(type: "nvarchar(max)", nullable: true),
>                     MatchingAlgorithm_TotalAttemptsNumber = table.Column<byte>(type: "tinyint", nullable: true),
>                     MatchingAlgorithm_NumberOfMatching = table.Column<int>(type: "int", nullable: true),
> ```

Following the repeat searches issue, let's change this and also change the messaging event as well:
1) Let's leave int? NumberOfResults
2) Add a separate field int? RepeatSearch_AddedResultCount
3) Add a separate field int? RepeatSearch_RemovedResultCount
4) Add a separate field int? RepeatSearch_UpdatedResultCount
5) Remove MatchingAlgorithm_NumberOfNoLongerMatching

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking.Data/Migrations/20240522082237_AddSearchTrackingSchemaAndTables.cs` line 33 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311#-Ny_nyvW7hPKBbWY_TM8:-Nya-qLV0nL31HO-cnzX:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ff6170558f6fe6a0ab142d6aeb20e2675e8c6115/Atlas.SearchTracking.Data/Migrations/20240522082237_AddSearchTrackingSchemaAndTables.cs#L33)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Following the repeat searches issue, let's change this and also change the messaging event as well:
1) Let's leave int? NumberOfResults
2) Add a separate field int? RepeatSearch_AddedResultCount
3) Add a separate field int? RepeatSearch_RemovedResultCount
4) Add a separate field int? RepeatSearch_UpdatedResultCount
5) Remove MatchingAlgorithm_NumberOfNoLongerMatching
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking.Data/Migrations/20240523151533_AddSearchTrackingSchemaAndTables.cs` line 35 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311#-NydutzwCuoret6naV6V:-NydutzwCuoret6naV6W:b-x6t8ez) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b57feff0daabea26c581f5803cab42f56d4dc979/Atlas.SearchTracking.Data/Migrations/20240523151533_AddSearchTrackingSchemaAndTables.cs#L35)):*
> ```Smalltalk
>                     MatchingAlgorithm_NumberOfMatching = table.Column<int>(type: "int", nullable: true),
>                     MatchingAlgorithm_NumberOfResults = table.Column<int>(type: "int", nullable: true),
>                     RepeatSearch_AddedResultCount = table.Column<int>(type: "int", nullable: true),
> ```

Sorry, should be 
MatchingAlgorithm_RepeatSearch_AddedResultCount
MatchingAlgorithm_RepeatSearch_RemovedResultCount
MatchngAlgorithm_RepeatSearch_UpdatedResultCount

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)* status: all files reviewed, 3 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Search.Tracking/Models/MatchingAlgorithmCompletedEvent.cs` line 21 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311#-NydvFAA9VElbp23b_Si:-NydvFAA9VElbp23b_Sj:b-61ic55) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b57feff0daabea26c581f5803cab42f56d4dc979/Search.Tracking/Models/MatchingAlgorithmCompletedEvent.cs#L21)):*
> ```Smalltalk
>         public int? NumberOfResults { get; set; }
>         public int? NumberOfMatching { get; set; }
>         public int? RepeatSearch_AddedResultCount { get; set; }
> ```

Let's create a class MatchingAlgorithmRepeatSearchResultsDetails and use it here so that we don't have "_" in the properties names in this class

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)* status: all files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Search.Tracking/Models/MatchingAlgorithmCompletedEvent.cs` line 21 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311#-NydvFAA9VElbp23b_Si:-NyelYkO9OujqjtQaQ-s:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b57feff0daabea26c581f5803cab42f56d4dc979/Search.Tracking/Models/MatchingAlgorithmCompletedEvent.cs#L21)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's create a class MatchingAlgorithmRepeatSearchResultsDetails and use it here so that we don't have "_" in the properties names in this class
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Data/Migrations/20240523151533_AddSearchTrackingSchemaAndTables.cs` line 35 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311#-NydutzwCuoret6naV6V:-Nyek7n-6FaOiQpQZhu4:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b57feff0daabea26c581f5803cab42f56d4dc979/Atlas.SearchTracking.Data/Migrations/20240523151533_AddSearchTrackingSchemaAndTables.cs#L35)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Sorry, should be 
MatchingAlgorithm_RepeatSearch_AddedResultCount
MatchingAlgorithm_RepeatSearch_RemovedResultCount
MatchngAlgorithm_RepeatSearch_UpdatedResultCount
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1311)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
