### PR TITLE
Versioning chores

### PR DESCRIPTION
**Pull request by zabeen**
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/639)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/639)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @benbelow)

___
*[Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md, line 11 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/639#-MfrG09_4-1CCkoLh6-4:-MfrG09_4-1CCkoLh6-5:b-iawszi) ([raw file](https://github.com/anthony-nolan/atlas/blob/c8ce59e3a8bed65c993d65198efff67352b5cae0/Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md#L11)):*
> ```Markdown
> ## Versions
> 
> ### 1.0.1
> ```

Note, I purposely only bumped the API project... this relates to my qs on the ADR card

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/639)* status: all files reviewed, 2 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/639#-Mfr_T1gAWzoveejtw3l:-Mfr_T1gAWzoveejtw3m:b-odwykc) (no related file):*
see comments on larger 996 review

---

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/639)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @benbelow)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/639#-Mfr_T1gAWzoveejtw3l:-MfreCod6L5J5Kb2h3Yi:b-896fix) (no related file):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

see comments on larger 996 review
</blockquote></details>

Done.

---

**Review by benbelow — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
