### PR TITLE
fix: #1140: don't update DonorManagementLog if Donor wasn't updated

### PR DESCRIPTION
**Pull request by SergeyEzh**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: all files reviewed, 2 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs` line 170 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Nr5FJ02BQEG1kzdRrF0:-Nr5FJ02BQEG1kzdRrF1:b-6mqkj1) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9c9655c654752dddbb30c8f2eaedd7a8a8d25650/Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs#L170)):*
> ```Smalltalk
> 
>             var (availableUpdates, unavailableUpdates) = updatesList.ReifyAndSplit(upd => upd.IsAvailableForSearch);
>             var recordOfUpdatesApplied = updatesList
> ```

suggest rename to `managementInfo`



_Code quote:_
```Smalltalk
recordOfUpdatesApplied
```
___
*[`Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs` line 189 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Nr5F-Qr6njgGtnnFGyZ:-Nr5F-Qr6njgGtnnFGy_:bx1ie8r) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9c9655c654752dddbb30c8f2eaedd7a8a8d25650/Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs#L189)):*
> ```Smalltalk
> 
> 
>                 var updatedDonors = processedUpdates
> ```

suggest rename to "successfullyAppliedUpdates" to make this extra step clearer



_Code quote:_
```Smalltalk
updatedDonors
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs` line 170 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Nr5FJ02BQEG1kzdRrF0:-Nr5K2Aj4JpdPg8Wdv2Y:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9c9655c654752dddbb30c8f2eaedd7a8a8d25650/Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs#L170)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

suggest rename to `managementInfo`
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs` line 189 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Nr5F-Qr6njgGtnnFGyZ:-Nr5K2_O6mDmG2fjOSqs:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9c9655c654752dddbb30c8f2eaedd7a8a8d25650/Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs#L189)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

suggest rename to "successfullyAppliedUpdates" to make this extra step clearer
</blockquote></details>

Done.

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 19 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Ns8je1U2wG_vkYgqBvE:-Ns8je1U2wG_vkYgqBvF:brmzdtw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a2703deb37793cbf2afeba65b1371df7ea7f49f7/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L19)):*
> ```Smalltalk
> using System.Text;
> using System.Threading.Tasks;
> ```

suggest adding `using Injection = Atlas.MatchingAlgorithm.Test.Integration.DependencyInjection.DependencyInjection;` here to help readability of the setup method
___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 46 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Ns8psIh9zPkVGF_lCjz:-Ns8psIh9zPkVGF_lCk-:bskfhp9) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a2703deb37793cbf2afeba65b1371df7ea7f49f7/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L46)):*
> ```Smalltalk
>             expectedSequenceNumber = update.UpdateSequenceNumber;
> 
>             await service.ApplyDonorUpdatesToDatabase(new[] { update }, activeDb, FileBackedHlaMetadataRepositoryBaseReader.NewerTestsHlaVersion, false);
> ```

all this should be moved to a private method called from within the test below, because there is no guarantee that a second test added to this fixture would need this same setup steps

`expectedSequenceNumber` will be returned from new method so doesn't need to be a field



_Code quote:_
```Smalltalk
            activeDb = dbProvider.GetActiveDatabase();
            expectedSequenceNumber = update.UpdateSequenceNumber;

            await service.ApplyDonorUpdatesToDatabase(new[] { update }, activeDb, FileBackedHlaMetadataRepositoryBaseReader.NewerTestsHlaVersion, false);
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 19 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Ns8je1U2wG_vkYgqBvE:-NsDNu6n1dMyKFDBNZj6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a2703deb37793cbf2afeba65b1371df7ea7f49f7/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L19)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

suggest adding `using Injection = Atlas.MatchingAlgorithm.Test.Integration.DependencyInjection.DependencyInjection;` here to help readability of the setup method
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 46 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-Ns8psIh9zPkVGF_lCjz:-NsDNVC00ybXip2y_QhD:bas4llz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a2703deb37793cbf2afeba65b1371df7ea7f49f7/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L46)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

all this should be moved to a private method called from within the test below, because there is no guarantee that a second test added to this fixture would need this same setup steps

`expectedSequenceNumber` will be returned from new method so doesn't need to be a field
</blockquote></details>

Agree, except first line `activeDb = dbProvider.GetActiveDatabase();`. Looking on other tests, it's very likely that other test will need it.

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 51 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDctLQ8qB_AuIjXQGh:-NsDctLQ8qB_AuIjXQGi:b-afkpbt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2f1adf54df643cc376215f61374717c049ae93da/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L51)):*
> ```Smalltalk
>             var expectedSequenceNumber = await AddUpdateDatabaseWithDonor();
>             var update = new DonorInfoBuilder(DonorId)
>                 .WithHlaAtLocus(Atlas.Common.Public.Models.GeneticData.Locus.A, Atlas.Common.Public.Models.GeneticData.LocusPosition.One, "*01:ZZZZZZZ")
> ```

please add to `using` block for better readability



_Code quote:_
```Smalltalk
Atlas.Common.Public.Models.GeneticData
```
___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 56 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDbU2E4eMJpK2zqTiw:-NsDbU2E4eMJpK2zqTix:bdsjdnz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2f1adf54df643cc376215f61374717c049ae93da/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L56)):*
> ```Smalltalk
> 
>             if (update.UpdateSequenceNumber == expectedSequenceNumber)
>                 update.UpdateSequenceNumber++;
> ```

think it would be clearer just to do `update.UpdateSequenceNumber = ++expectedSequenceNumber` without the `if` check 



_Code quote:_
```Smalltalk
            if (update.UpdateSequenceNumber == expectedSequenceNumber)
                update.UpdateSequenceNumber++;
```
___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 65 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDcGex5u-10orho_al:-NsDcGex5u-10orho_am:b-3x0paz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2f1adf54df643cc376215f61374717c049ae93da/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L65)):*
> ```Smalltalk
>         }
> 
>         private async Task<long> AddUpdateDatabaseWithDonor()
> ```

rename: `AddDonorUpdateToDatabase`



_Code quote:_
```Smalltalk
AddUpdateDatabaseWithDonor
```

**Review by zabeen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: all files reviewed, 3 unresolved discussions (waiting on @SergeyEzh)

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 51 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDctLQ8qB_AuIjXQGh:-NsDk5DN54wmUGJ78CMR:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2f1adf54df643cc376215f61374717c049ae93da/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L51)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please add to `using` block for better readability
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 56 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDbU2E4eMJpK2zqTiw:-NsDk5cm7V-K9Fu8jint:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2f1adf54df643cc376215f61374717c049ae93da/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L56)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

think it would be clearer just to do `update.UpdateSequenceNumber = ++expectedSequenceNumber` without the `if` check
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 65 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDcGex5u-10orho_al:-NsDk60tBNyHYnixSWUL:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2f1adf54df643cc376215f61374717c049ae93da/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L65)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

rename: `AddDonorUpdateToDatabase`
</blockquote></details>

Done.

**Review by zabeen — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 56 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDtOfx8t62Yhpoa-wq:-NsDx4CY2TADIHZrkpMD:b7zasqn) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/97c32e7acd128b50409b396306085475e6f78e49/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L56)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

missing the `++`
</blockquote></details>

Oops, my bad.

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 56 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDtOfx8t62Yhpoa-wq:-NsDxI4nBGGL6bjLVRXj:b-7ql1td) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/97c32e7acd128b50409b396306085475e6f78e49/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L56)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Oops, my bad.
</blockquote></details>

fixed

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs` line 56 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230#-NsDtOfx8t62Yhpoa-wq:-NsDzmPJ5MYQLEr4ZSs5:b6e6xpc) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/97c32e7acd128b50409b396306085475e6f78e49/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs#L56)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

fixed
</blockquote></details>

ah, my bad too, can't use `++` because that would increment `expected` var :laughing:

**Pull request merged**
