### PR TITLE
docs: Clarifications made to the deployment readme.

### PR DESCRIPTION
**Pull request by zabeen**
Please check these changes to the deployment readme are correct and clear. Thanks!

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/844)

### CODE REVIEW

**Comment by seanmobrien** [comment]
> > _[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/844)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @luken-an and @seanmobrien)
> 
> _[`README_Deployment.md` line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/844#-NIhvY0GDGkxp8JXCkd9:-NIhvY0GDGkxp8JXCkdA:bvus5yn) ([raw file](https://github.com/anthony-nolan/atlas/blob/fc0b5191a2f013d048411676dbbdeef022c3e9af/README_Deployment.md#L29)):_
> 
> > ```gfm
> >     - e.g. The matching algorithm Data Refresh needs to be able to scale azure databases at runtime.
> >     - This information is set up as app settings by Terraform - the relevant Terraform variables are `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`
> >     - These variables (`AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`) are also used by Terraform to fetch function keys .
> > ```
> 
> @seanmobrien I thought it was a typo, but in fact these are names of tarraform release vars!

Thanks, Zabeen!  One thing I did notice is the Anthony Nolan release pipeline has different values for the TF_VAR_AZURE_CLIENT_ID / TF_VAR_AZURE_CLIENT_SECRET and the Terraform Variable Group's ARM_CLIENT_ID and ARM_CLIENT_SECRET, which leads me to believe these are two separate credentials.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/844)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @luken-an and @seanmobrien)

___
*[`README_Deployment.md` line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/844#-NIhvY0GDGkxp8JXCkd9:-NIlC55U7Bekw6Bjc8TZ:bh6imil) ([raw file](https://github.com/anthony-nolan/atlas/blob/fc0b5191a2f013d048411676dbbdeef022c3e9af/README_Deployment.md#L29)):*
<details><summary><i>Previously, seanmobrien wrote…</i></summary><blockquote>

Thanks, Zabeen!  One thing I did notice is the Anthony Nolan release pipeline has different values for the TF_VAR_AZURE_CLIENT_ID / TF_VAR_AZURE_CLIENT_SECRET and the Terraform Variable Group's ARM_CLIENT_ID and ARM_CLIENT_SECRET, which leads me to believe these are two separate credentials. 
</blockquote></details>

Yup, could I make that clearer in the readme? I'll submit a change, would appreciate if you could review it.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/844)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @luken-an and @seanmobrien)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/844)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @luken-an and @seanmobrien)

**Pull request merged**
