### PR TITLE
test: #1015: Delete haplotype frequencies for a failed HF set as part…

### PR DESCRIPTION
**Pull request by IgorKupreychik**
… of import clean up

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyInspectionRepository.cs` line 84 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGNCYw8cBf5c5S9tYk:-NaGOM2p2l95-DE6nhXn:b4e5p3n) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyInspectionRepository.cs#L84)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

not seen this before - so it will either return `1` if there are rows, or nothing?
</blockquote></details>

I wonder if a simple `COUNT(*)` would be more legible, and then change the check below from `== 1` to `> 0`?

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyInspectionRepository.cs` line 84 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGNCYw8cBf5c5S9tYk:-NaG_wXu8ueYZQ0tYHUl:bs2qv3s) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyInspectionRepository.cs#L84)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I wonder if a simple `COUNT(*)` would be more legible, and then change the check below from `== 1` to `> 0`?
</blockquote></details>

Well, it's just for tests, not sure if we need to pay as much attention on it at all. But, if we're talking about performance, TOP 1 1 would definitely be faster, than COUNT(*), but again, since it's for tests only, I don't see much difference

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs` line 69 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGJit34-Mo8rTCiaVs:-NaGaOOuDtwEZyodTv1b:b-j6moud) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs#L69)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

if you used `frequencySetImporter.Invoking(x => x.)Import(file, importBehavior).Should().Throw<Exception>();` instead

would the `.Received()` checks below still work, or would they be out of scope?
</blockquote></details>

Could you please clarify what are the benefits of the method you propose over the one that's implemented?

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs` line 69 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGJit34-Mo8rTCiaVs:-NaGbDoC7imfELJuViMv:bh2q1yj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs#L69)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

Could you please clarify what are the benefits of the method you propose over the one that's implemented?
</blockquote></details>

Ahh, your question is mostly related to try-catch block, right? If so - yes, it makes sense.

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs` line 69 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGJit34-Mo8rTCiaVs:-NaGaqq82NfWV29n9xw4:bfr38kt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs#L69)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

Could you please clarify what are the benefits of the method you propose over the one that's implemented?
</blockquote></details>

it takes up fewer lines then try/catch and is consistent with how we assert exceptions in other tests. But the only unknown is whether it works with the later `.Received` assertions.
___
*[`Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyInspectionRepository.cs` line 84 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGNCYw8cBf5c5S9tYk:-NaGbcY79cR6U7lmTiGB:b-5mvtt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyInspectionRepository.cs#L84)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

Well, it's just for tests, not sure if we need to pay as much attention on it at all. But, if we're talking about performance, TOP 1 1 would definitely be faster, than COUNT(*), but again, since it's for tests only, I don't see much difference 
</blockquote></details>

ok, that's fine, if it's faster then that is good for tests!

honestly, I thought it was a typo at first :laughing: 

maybe add a comment like "// using `TOP 1 1` as it's faster than using COUNT(*)" so unfamiliar devs like myself aren't tempted to refactor :wink:

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs` line 69 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGJit34-Mo8rTCiaVs:-NaGc8ui-klgK9tdSWAw:b-smf9q5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs#L69)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

it takes up fewer lines then try/catch and is consistent with how we assert exceptions in other tests. But the only unknown is whether it works with the later `.Received` assertions.
</blockquote></details>

yes, it works

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs` line 69 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023#-NaGJit34-Mo8rTCiaVs:-NaGcJdo4SkpSmM0ip9z:b7tsv5r) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c9a60f21b80cb7a9b971c3d554f8fc4654e86fd3/Atlas.MatchPrediction.Test/Services/HaplotypeFrequencies/Import/FrequencySetImporterTests.cs#L69)):*
> Ahh, your question is mostly related to try-catch block, right?

yup!

**Review by zabeen — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1023)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
