### PR TITLE
chore: #805: Add additional endpoint for batched match prediction req…

### PR DESCRIPTION
**Pull request by zabeen**
…uests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/811)

### CODE REVIEW

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/811)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by zabeen — COMMENTED** [review]
I've removed the single request endpoint because it is now redundant, and have upgraded MP to use `Azure.Messaging.ServiceBus` to leverage safe batch sending functionality: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#sending-messages

> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/811#-:-NCySsZLA6IPRUJV4lgt:b60nasn)* status: 7 of 14 files reviewed, all discussions resolved (waiting on @daria-sorokina-da)

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/811)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/811)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
