### PR TITLE
feature: #1274: CBT-1472: Add unit tests for DAL

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316)

### CODE REVIEW

**Review by SergeyEzh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, and @pchenery)

___
*[`Atlas.SearchTracking.Data/Repositories/MatchPredictionRepository.cs` line 61 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316#-NzcPFXQ9GdvfeH9ZAXt:-NzcPFXQ9GdvfeH9ZAXu:bs6g7k1) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/6eb8d4f6d7e30cb7278006bd71ecc0b9a5971810/Atlas.SearchTracking.Data/Repositories/MatchPredictionRepository.cs#L61)):*
> ```Smalltalk
>         }
> 
>         public async Task<SearchRequestMatchPredictionTiming?> GetSearchRequestMatchPredictionById(int id)
> ```

probably here should be `Task<SearchRequestMatchPredictionTiming?>` since we don't return null value
___
*[`Atlas.SearchTracking.Data.Test/TestHelpers/SqliteMemoryContext.cs` line 14 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316#-NzcQNNL6VpJZPINZECy:-NzcQNNM9SUVhAZbuozv:bmf2hez) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/6eb8d4f6d7e30cb7278006bd71ecc0b9a5971810/Atlas.SearchTracking.Data.Test/TestHelpers/SqliteMemoryContext.cs#L14)):*
> ```Smalltalk
>         /// Connection must be closed in TearDown
>         /// </summary>
>         public static Tuple<IDbConnection, SearchTrackingContext> Create()
> ```

I'd recommend use newest syntax for tuples:
`public static (IDbConnection, SearchTrackingContext) Create()`

and


`return (connection, new SearchTrackingContext(options));`

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @alikhanmda, @daria-sorokina-da, and @SergeyEzh)

___
*[`Atlas.SearchTracking.Data/Repositories/MatchPredictionRepository.cs` line 61 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316#-NzcPFXQ9GdvfeH9ZAXt:-NzcqeYtD1sbLMfhpnIM:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/6eb8d4f6d7e30cb7278006bd71ecc0b9a5971810/Atlas.SearchTracking.Data/Repositories/MatchPredictionRepository.cs#L61)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

probably here should be `Task<SearchRequestMatchPredictionTiming?>` since we don't return null value
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Data.Test/TestHelpers/SqliteMemoryContext.cs` line 14 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316#-NzcQNNL6VpJZPINZECy:-NzcriqzEOY_BvTMpW3S:b-ucfknh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/6eb8d4f6d7e30cb7278006bd71ecc0b9a5971810/Atlas.SearchTracking.Data.Test/TestHelpers/SqliteMemoryContext.cs#L14)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

I'd recommend use newest syntax for tuples:
`public static (IDbConnection, SearchTrackingContext) Create()`

and


`return (connection, new SearchTrackingContext(options));`
</blockquote></details>

Thanks!

**Review by SergeyEzh — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alikhanmda and @daria-sorokina-da)

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alikhanmda)

**Pull request merged**
