### PR TITLE
draft: feat: #1118: update azurerm version & migrate to workspace based appl…

### PR DESCRIPTION
**Pull request by SergeyEzh**
@zabeen , There's draft PR for application insights migration. I'll leave details on the ticket.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167)* status: all files reviewed, 6 unresolved discussions (waiting on @SergeyEzh)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJXp_B-SaynoeAtJ0):*
we may want to split these changes into two PRs: 

* first update the `azurerm` version and check nothing changes/breaks in dev
* Thereafter, just a commit for the AI workspace change



_Code quote:_
```
- e8bccf3: feat: #1118: update azurerm version & migrate to workspace based application insights
```
___
*[`terraform/core/application_insights.tf` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCIng-BLMMdyZAY_ob:-NoCIng-BLMMdyZAY_oc:b-klm5z2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/application_insights.tf#L10)):*
> ```HCL
> 
> resource "azurerm_log_analytics_workspace" "ai_workspace" {
>   name                = "${lower(replace(local.environment, "/\\W/", ""))}loganalyticsworkspace"
> ```

I take it we are not allowed whitespace in the name?



_Code quote:_
```HCL
{lower(replace(local.environment, "/\\W/", ""))}
```
___
*[`terraform/core/function.tf` line 133 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJ8Ui1rqNBwSN60Ch:-NoCJ8Ui1rqNBwSN60Ci:b-btwzqm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/function.tf#L133)):*
> ```HCL
>     #   ip_address = ip
>     #   subnet_id  = null
>     # }]
> ```

please remove commented lines



_Code quote:_
```HCL
    # ip_restriction = [for ip in var.IP_RESTRICTION_SETTINGS : {
    #   ip_address = ip
    #   subnet_id  = null
    # }]
```
___
*[`terraform/core/function.tf` line 137 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJC9e4DOo6qhwmP20:-NoCJC9e4DOo6qhwmP21:b-jrxcue) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/function.tf#L137)):*
> ```HCL
>     scm_minimum_tls_version = "1.0"
>     cors {
>       # allowed_origins     = []
> ```

comment



_Code quote:_
```HCL
# allowed_origins     = []
```
___
*[`terraform/core/modules/donor_import/function.tf` line 64 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJNAU14brvcCh3cwn:-NoCJNAU14brvcCh3cwo:b-jrxcue) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/modules/donor_import/function.tf#L64)):*
> ```HCL
>     }
>     cors {
>       # allowed_origins     = []
> ```

comment



_Code quote:_
```HCL
 # allowed_origins     = []
```
___
*[`terraform/core/modules/donor_import/function.tf` line 78 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJKepE5tROEkcJ2EN:-NoCJKepE5tROEkcJ2EO:bq8afp5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/modules/donor_import/function.tf#L78)):*
> ```HCL
>     #   ip_address = ip
>     #   subnet_id  = null
>     # }]
> ```

comments



_Code quote:_
```HCL
    # ip_restriction = [for ip in var.IP_RESTRICTION_SETTINGS : {
    #   ip_address = ip
    #   subnet_id  = null
    # }]
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167)* status: all files reviewed, 6 unresolved discussions (waiting on @zabeen)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJXp_B-SaynoeAtJ0):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

we may want to split these changes into two PRs: 

* first update the `azurerm` version and check nothing changes/breaks in dev
* Thereafter, just a commit for the AI workspace change
</blockquote></details>

Agree.
___
*[`terraform/core/application_insights.tf` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCIng-BLMMdyZAY_ob:-NoCUaMuD-4AVzg3e0ge:b-9nld1f) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/application_insights.tf#L10)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I take it we are not allowed whitespace in the name?
</blockquote></details>

In azure, different resource provides has their own rules on what characters are allowed in name. I've checked, in this particular place we're allowed to use whitespaces . I just picked this snippet from another file. Do you want another name?
___
*[`terraform/core/function.tf` line 133 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJ8Ui1rqNBwSN60Ch:-NoCWPjX5m7en-QZ2CJV:b-t8xq39) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/function.tf#L133)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please remove commented lines
</blockquote></details>

oops, missed it during cleaning up. Will remove it. Same as others.

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167)* status: all files reviewed, 6 unresolved discussions (waiting on @zabeen)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJXp_B-SaynoeAtJ0):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

@zabeen , Do you want me create separate ticket for azurerm upgrade? Or it's fine to create two PRs for this ticket?

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167)* status: all files reviewed, 6 unresolved discussions (waiting on @SergeyEzh)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCJXp_B-SaynoeAtJ0):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

@zabeen , Do you want me create separate ticket for azurerm upgrade? Or it's fine to create two PRs for this ticket?
</blockquote></details>

Two PR same ticket is fine

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167)* status: all files reviewed, 6 unresolved discussions (waiting on @SergeyEzh)

___
*[`terraform/core/application_insights.tf` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1167#-NoCIng-BLMMdyZAY_ob:-NoDTrjS8J0Z4JTHB4eX:bhgi30u) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e8bccf376d66199b30aff9137e0227e018f7321d/terraform/core/application_insights.tf#L10)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

In azure, different resource provides has their own rules on what characters are allowed in name. I've checked, in this particular place we're allowed to use whitespaces . I just picked this snippet from another file. Do you want another name?
</blockquote></details>

In that case you can simply use `${local.environment}-ATLAS`. When we plan to have only one instance of a resource type, e.g., one sql server, one application insights, we tend to name it “<env>-ATLAS” as the resource type is obvious from both the terraform definition and within Azure portal.

**Pull request closed without merging**
