### PR TITLE
#895: All non-completed searches should be in 1 place

### PR DESCRIPTION
**Pull request by IgorKupreychik**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899)* status: all files reviewed, 7 unresolved discussions (waiting on @daria-sorokina-da, @disaev-nmdp, and @IgorKupreychik)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ5-d2F2GyHr9j__75t):*
small comment, please can you pre-fix commits with a keyword, as described here:
https://github.com/Anthony-Nolan/Atlas/blob/master/README_Contribution_Versioning.md#contributing
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ500j13kpeOiwWEpQg:-NQ500j13kpeOiwWEpQh:bunj41x) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L33)):*
> ```Smalltalk
>         /// <param name="remainingRetriesCount">The number of times this <paramref name="searchRequestId"/> will be retried until it completes successfully.</param>
>         /// <param name="errorMessage"></param>
>         Task SetSearchFailure(string searchRequestId, int attemptNumber, int remainingRetriesCount, string errorMessage);
> ```

I suggest moving this method out to a new dedicated service that can be called by both the SearchRunner and the DLQ listener function.

E.g.,  `MatchingFailureNotificationSender`

Also suggest rename method to `SendFailureNotification`
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 130 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ50uMR6bpPvxD63hKr:-NQ50uMR6bpPvxD63hKs:byni4vl) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L130)):*
> ```Smalltalk
>         }
> 
>         public async Task SetSearchFailure(string searchRequestId, int attemptNumber, int remainingRetriesCount, string errorMessage)
> ```

`errorMessage` should be renamed to `validationError` as we are only used it in this context.

Plus, it should be an optional param, as we don't always set it.
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 152 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ53NP76sVXLwlCVs-i:-NQ52G4k3Ec7h83ZIUqy:b-gmxppi) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L152)):*
> ```Smalltalk
>         }
> 
>         private string SearchAlgorithmServiceVersion => Assembly.GetExecutingAssembly().GetName().Version?.ToString();
> ```

Generally, class-level fields should be listed at the top of class - but as the send failure method is being moved to a new service, this will be set within the new method anyway :)
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs` line 62 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ53wyH0hqqKU935mjJ:-NQ53wyH0hqqKU935mjK:b-a98jtw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs#L62)):*
> ```Smalltalk
> 
>         [FunctionName(nameof(DeadLetterQueueListener))]
>         public async Task DeadLetterQueueListener(
> ```

Suggest function rename to `MatchingRequestsDeadLetterQueueListener`
___
*[`Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs` line 64 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ54B4OB_e6CebAP51D:-NQ54B4OB_e6CebAP51E:bxnlu8c) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs#L64)):*
> ```Smalltalk
>         public async Task DeadLetterQueueListener(
>             [ServiceBusTrigger(
>                 "%MessagingServiceBus:SearchRequestsTopic%/Subscriptions/%MessagingServiceBus:SearchRequestsSubscription%/$DeadLetterQueue",
> ```

nice, so it can be done with service bus trigger! great :)
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs` line 178 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ55TyH3LUxL8RCuJMO:-NQ55TyH3LUxL8RCuJMP:b5tw3j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs#L178)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task SetSearchFailure_PublishesFailureNotification()
> ```

this test should be moved to a new fixture, after the method has been moved to a new service class
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs` line 182 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ55awZ4ktEkVKGT-15:-NQ55awZ4ktEkVKGT-16:bz3x5a8) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/e6536a358e37a84d70882f60cc5b859f3ecbdf6b/Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs#L182)):*
> ```Smalltalk
>             await searchRunner.SetSearchFailure("search_id", 7, 3, "error message");
> 
>             await searchServiceBusClient.Received().PublishToResultsNotificationTopic(Arg.Any<MatchingResultsNotification>());
> ```

would be good to assert that that the `MatchingResultsNotification` props are correctly set, especially `WasSuccessful` should be `false`, and the failure info.

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs` line 72 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ5fG_Z0CH1xwOg2A2e:-NQ5ooOs6wJdnD6h4qDJ:b-ao885v) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b8cd2764a8493039d4776f60a1c40f8e6c83f3d1/Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs#L72)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

have you tested this locally? does reading the dead-lettered message automatically remove the message from the DLQ, as happens with the main queue?
</blockquote></details>

Of course I tested it before posting the PR, yes - it behaves like a regular queue and removes the entry from DLQ after processing

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da, @disaev-nmdp, and @IgorKupreychik)

___
*[`Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs` line 72 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQ5fG_Z0CH1xwOg2A2e:-NQ5pzBPA3XabgH49x-7:b-s9gs8c) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b8cd2764a8493039d4776f60a1c40f8e6c83f3d1/Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs#L72)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

Of course I tested it before posting the PR, yes - it behaves like a regular queue and removes the entry from DLQ after processing
</blockquote></details>

great! I thought we may have to complete the message via an additional method call, so it's great that it works nicely as is. :)

**Review by zabeen — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899)* status: all files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da, @disaev-nmdp, and @IgorKupreychik)

**Review by zabeen — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @daria-sorokina-da and @disaev-nmdp)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899#-NQAKIyQBG8a2xYplG1i):*
in future, please use `push --force` instead of `merge` when applying conflicting changes from local to the remote feature branch, it keeps the history a bit cleaner :)

**Pull request merged**
