### PR TITLE
Draft: Migration to isolated worker (#1305) and migration to .net8 (#1159) 

### PR DESCRIPTION
**Pull request by SergeyEzh**
Creating as draft, because of issue with http triggers. It will be converted to PR when a fix will be found.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)

### CODE REVIEW

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 163 of 163 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 8 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.Client.Models/Atlas.Client.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZH4q3QpizF4179KH:-Nz8ZH4q3QpizF4179KI:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Client.Models/Atlas.Client.Models.csproj#L4)):*
> ```XML
> 
>   <PropertyGroup>
>     <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change
___
*[`Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZS477SrFLMSzIJ6c:-Nz8ZS477SrFLMSzIJ6d:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj#L4)):*
> ```XML
> 
>   <PropertyGroup>
>     <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change
___
*[`Atlas.Debug.Client/Atlas.Debug.Client.csproj` line 5 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZThoBGoOK8h8-rLe:-Nz8ZThoBGoOK8h8-rLf:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Debug.Client/Atlas.Debug.Client.csproj#L5)):*
> ```XML
>   <PropertyGroup>
>     <TargetFramework>net8.0</TargetFramework>
>     <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change
___
*[`Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj` line 5 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZVAbBEeP8wBI9Hqw:-Nz8ZVAbBEeP8wBI9Hqx:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj#L5)):*
> ```XML
>   <PropertyGroup>
>     <TargetFramework>net8.0</TargetFramework>
>     <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change
___
*[`Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZY4Y3IYRlCpjcNW8:-Nz8ZY4Y3IYRlCpjcNW9:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj#L4)):*
> ```XML
> 
>   <PropertyGroup>
>     <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change
___
*[`Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8_47yA3nLcv58YvTA:-Nz8_47zCAmYs29jmq52:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj#L3)):*
> ```XML
> <Project Sdk="Microsoft.NET.Sdk">
>     <PropertyGroup>
>       <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change
___
*[`Atlas.Functions.PublicApi/Functions/ApiDocumentationFunctions.cs` line 19 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8_Dc1-vRWBkszpC4l:-Nz8_Dc1-vRWBkszpC4m:b422fgs) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Functions.PublicApi/Functions/ApiDocumentationFunctions.cs#L19)):*
> ```Smalltalk
>     public static class ApiDocumentationFunctions
>     {
>         //[SwaggerIgnore]
> ```

What about these commented-out functions?
___
*[`Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8_XXN3Qa3qswa__hj:-Nz8_XXN3Qa3qswa__hk:b21k4qx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj#L4)):*
> ```XML
> 
>   <PropertyGroup>
>     <VersionPrefix>2.2.0</VersionPrefix>
> ```

I think we need to update the major version for this change

**Review by daria-sorokina-da — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 9 unresolved discussions (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-NzCzqCB3HZOqXrD-Iy4:-NzCzqCB3HZOqXrD-Iy5:b-8lfhqu) (no related file):*
Please update changelogs

```
### 3.0.0
* Updated .NET version from 6.0 to 8.0
```

___

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 44 of 44 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 4 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs` line 23 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5sRIe4Od3cOKTUhQl:-O-5sRIe4Od3cOKTUhQm:bkrwtc4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs#L23)):*
> ```Smalltalk
>                 var httpContext = context.GetHttpContext();
> 
>                 if (httpContext is { Response.HasStarted: false })
> ```

Could you please describe why we need this code?
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 37 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5t9ck11cfacx-Jg3Z:-O-5t9ck11cfacx-Jg3_:b-cqc4i8) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L37)):*
> ```Markdown
> 
> ### 3.0.0
> * E: Updated .NET version from 6.0 to 8.0
> ```

Sorry, what's `E:`?
___
*[`Atlas.MatchingAlgorithm.Api/SwaggerStartup.cs` line 25 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5tiB34YwZSrZbCye6:-O-5tiB402iKxJz6kpPy:b9h8kz1) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.MatchingAlgorithm.Api/SwaggerStartup.cs#L25)):*
> ```Smalltalk
>             {
>                 c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
>                 c.RoutePrefix = string.Empty;
> ```

We have route prefix "api" in all other functions - why is the matching algorithm different?

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 3 unresolved discussions (waiting on @pchenery and @SergeyEzh)

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da and @pchenery)

___
*[`Atlas.Client.Models/Atlas.Client.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZH4q3QpizF4179KH:-O-L85HT5fiWPzsYjyoA:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Client.Models/Atlas.Client.Models.csproj#L4)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done
___
*[`Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs` line 23 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5sRIe4Od3cOKTUhQl:-O-LA8RDDv5j0xk6mL6s:boprlxs) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs#L23)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Could you please describe why we need this code?
</blockquote></details>

Do you mean this condition? Just in case, if code in function manipulate response directly and complete it and after that exception happened. 

Or you meant the whole middleware?
___
*[`Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZS477SrFLMSzIJ6c:-O-L8Ilz33gdCl7PktsP:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj#L4)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done
___
*[`Atlas.Debug.Client/Atlas.Debug.Client.csproj` line 5 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZThoBGoOK8h8-rLe:-O-L8Jq60QNYaOFDCEel:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Debug.Client/Atlas.Debug.Client.csproj#L5)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done
___
*[`Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj` line 5 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZVAbBEeP8wBI9Hqw:-O-L8KerDZJXnPhaNnrx:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj#L5)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done
___
*[`Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8ZY4Y3IYRlCpjcNW8:-O-L8LUa4BH0F36avYhb:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj#L4)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done
___
*[`Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8_47yA3nLcv58YvTA:-O-L8N-c0vzClJGBlZmR:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj#L3)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 37 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5t9ck11cfacx-Jg3Z:-O-L8_e350cLwkQqWJIX:b-hrnqvi) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L37)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Sorry, what's `E:`?
</blockquote></details>

Just following style in this document, the E stands for `Enchancement ` (description is above in document)
___
*[`Atlas.Functions.PublicApi/Functions/ApiDocumentationFunctions.cs` line 19 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8_Dc1-vRWBkszpC4l:-O-L9Ac-B1eLQQ_mQVCT:b-zd56ou) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.Functions.PublicApi/Functions/ApiDocumentationFunctions.cs#L19)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What about these commented-out functions?
</blockquote></details>

fixed, thanks.
___
*[`Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-Nz8_XXN3Qa3qswa__hj:-O-L8vm27FY5XvolqTXc:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/edfe3cbdf9e71c065ed01a71df83f7411dc67184/Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj#L4)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to update the major version for this change
</blockquote></details>

done

**Review by daria-sorokina-da — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs` line 23 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5sRIe4Od3cOKTUhQl:-O-_PuDo-2u5cpfOIZSi:bbltoei) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs#L23)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Do you mean this condition? Just in case, if code in function manipulate response directly and complete it and after that exception happened. 

Or you meant the whole middleware?
</blockquote></details>

Yes, I'm trying to understand this condition in the middleware.

If the response has started (and cannot be changed) - then we throw an exception (the same as originally). What will happen in this case? Will the response get sent?

If the response has not started - then we set status code 500, and complete the response.

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: all files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @pchenery)

___
*[`Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs` line 23 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5sRIe4Od3cOKTUhQl:-O-_riEoEnrN2-H7MjUI:b25hlnl) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.Common/FunctionsWorker/ExceptionHandlingMiddleware.cs#L23)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Yes, I'm trying to understand this condition in the middleware.

If the response has started (and cannot be changed) - then we throw an exception (the same as originally). What will happen in this case? Will the response get sent?

If the response has not started - then we set status code 500, and complete the response.
</blockquote></details>

HasStarted will be true, when response headers is already transmitted to client. From my understanding then only way to start transmit it earlier in pipeline is to call `.CompleteAsync()`. And therefore, if reponse.HasStarted is true, the response is already has been or being send.

But hopefully, it doesn't matter already. According to bug report (https://github.com/Azure/azure-functions-dotnet-worker/issues/2476), this bug get fixed recently. So I'm going to update nuget packets and remove this middleware.
___
*[`Atlas.MatchingAlgorithm.Api/SwaggerStartup.cs` line 25 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314#-O-5tiB34YwZSrZbCye6:-O-_vEe67XmVQ7AqCWfL:bncilf0) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5af2477ab1b5d9683e2576ae2921776c8ff1463d/Atlas.MatchingAlgorithm.Api/SwaggerStartup.cs#L25)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

We have route prefix "api" in all other functions - why is the matching algorithm different?
</blockquote></details>

I don't know why here url is different. I want to note that it isn't functions project nor production deployed code, but just debug helper. This is why, I left it as it was.

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
