### PR TITLE
feat: #1067: remove call to donor reader during matching

### PR DESCRIPTION
**Pull request by SergeyEzh**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 2 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 22 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWAmBW63qbl1LiRdsm:-NkWAmBW63qbl1LiRdsn:b-zd8cjd) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/90fa67257e6317ba6aa9b41b99c25e5304ace964/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L22)):*
> ```Smalltalk
>         private IMatchingAlgorithmSearchLogger searchLogger;
>         private IDonorReader donorReader;
>         private IAtlasFeatureManager featureManager;
> ```

think this can be removed now?
___
*[`Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs` line 146 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWAqy-BbDLhKAR0uaA:-NkWAqy-BbDLhKAR0uaB:bqr0zo2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/03ce5dc7709ad5a7bcb97dc114c863ddee01c46f/Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs#L146)):*
> ```Smalltalk
>             services.AddSingleton<ILogger, FileBasedLogger>();
> 
>             var atlasFeatureManager = Substitute.For<IAtlasFeatureManager>();
> ```

please also make sure to remove the feature manager from [matching algorithm service config](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L315) as well, along with these lines:
```
services.AddAzureAppConfiguration();
services.AddFeatureManagement();
```

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 3 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Donors/DonorHelper.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWC_G09C1MPMCcGRL3:-NkWC_G09C1MPMCcGRL4:be3h4ob) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/90fa67257e6317ba6aa9b41b99c25e5304ace964/Atlas.MatchingAlgorithm/Services/Donors/DonorHelper.cs#L33)):*
> ```Smalltalk
>         public async Task<Dictionary<int, DonorLookupInfo>> GetDonorLookup(List<MatchAndScoreResult> reifiedScoredMatches)
>         {
>             return reifiedScoredMatches.ToDictionary(r => r.MatchResult.DonorId, r => r.MatchResult.DonorInfo.ToDonorLookupInfo());
> ```

it seems this service isn't doing anything special now, so this entire `GetDonorLookup` method could be moved back to the class that calls `DonorHelper`.

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs` line 146 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWAqy-BbDLhKAR0uaA:-Nk_EEZI9-xrVUBDukJi:brxq5b7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/03ce5dc7709ad5a7bcb97dc114c863ddee01c46f/Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs#L146)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please also make sure to remove the feature manager from [matching algorithm service config](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L315) as well, along with these lines:
```
services.AddAzureAppConfiguration();
services.AddFeatureManagement();
```
</blockquote></details>

May be we should leave it configured in matching algorithm service config just in case we need feature flags again ?

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: 3 of 19 files reviewed, 2 unresolved discussions (waiting on @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkojY0J2DYf7FNQgrVJ:-NkojY0J2DYf7FNQgrVK:b-70qr3c) (no related file):*
@SergeyEzh seeing the number of changes you had to make to clean up reference to Feature manager, I can see your point about leaving feature manager in .MatchingAlgorithm and .RepeatSearch projects! (A general point: `Atlas.Common` is a utils project so code in there that is useful long-term can remain even if not being used presently)

please could you hard reset the last commit (fe5eea4) and force push the feature branch, then I'll add suggestions on how we can better document the existing code so it's purpose is clear to future devs

thanks so much

___

**Review by zabeen — COMMENTED** [review]
@SergeyEzh please also remove the feature flag definition from terraform by deleting the file: terrform>modules>matching_algorithm>app_configuration.tf

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-:-Nkow-ci9gz5uFNzDWNm:b-o4aodp)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh and @zabeen)

**Review by SergeyEzh — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-:-NkozCVYDv4xNDITs_B0:bb6un1j)* status: all files reviewed, 2 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkowW3sDpFlwF1y4Zzo:-NkozQw3BhDhvXTnFI0Q:bb6un1j) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

@SergeyEzh  please also remove the feature flag definition from terraform by deleting the file: terrform>modules>matching\_algorithm>app\_configuration.tf
</blockquote></details>

Done

___
___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 366 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-Nkou8wqEmDc1lbLCCE3:-NkpCB3ZBF4KsvosjVZ4:b-ur8upq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c3c6d170bc1c234120486f7a8fdc9a04af0b3809/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L366)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Move all lines to do with feature manager config to a new private method in this class, titled `SetUpFeatureManager`
```
            services.AddAzureAppConfiguration();
            services.AddFeatureManagement();

services.AddScoped<IAtlasFeatureManager, AtlasFeatureManager>();

```

Add method level comment stating that this config should be left place, even if no feature flags are currently in use


Please do same for repeat search service config
</blockquote></details>

Done for MatchingAlgorithm, but I didn't find any similar code for  repeat search service. There is another code: 

This one I found for repeat search service and for couple another projects. Do you want to move that code to another method as well?
___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 22 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWAmBW63qbl1LiRdsm:-NkpEHrp02PiJMwMv4av:b-rx6wra) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/90fa67257e6317ba6aa9b41b99c25e5304ace964/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L22)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

think this can be removed now?
</blockquote></details>

Since I removed DonorHelper it can't test this functionality without testing whole SearchService.Serach method. I didn't find unit tests for this service. Do you want to write me one?

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh and @zabeen)

___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 366 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-Nkou8wqEmDc1lbLCCE3:-NkpVCQz86e3BiF0lgs2:bo6ompl) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c3c6d170bc1c234120486f7a8fdc9a04af0b3809/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L366)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Done for MatchingAlgorithm, but I didn't find any similar code for  repeat search service. There is another code: 

This one I found for repeat search service and for couple another projects. Do you want to move that code to another method as well?
</blockquote></details>

Yes please!
___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 22 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWAmBW63qbl1LiRdsm:-NkpSNIy5JuJuU1uAzdL:b-70nb8p) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/90fa67257e6317ba6aa9b41b99c25e5304ace964/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L22)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

Since I removed DonorHelper it can't test this functionality without testing whole SearchService.Serach method. I didn't find unit tests for this service. Do you want to write me one?
</blockquote></details>

I don't think it would be easy or useful to unit test this. 
You could extend [this integration test fixture](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/Search/SingleDonorSearchTests.cs) with assertion that the following props are being populated:

- ExternalDonorCode
- EthnicityCode
- RegistryCode

You'll need to [set these values in the test donor](https://github.com/Anthony-Nolan/Atlas/blob/03ce5dc7709ad5a7bcb97dc114c863ddee01c46f/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/Search/SingleDonorSearchTests.cs#L58C31-L58C31)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh and @zabeen)

___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 366 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-Nkou8wqEmDc1lbLCCE3:-NkpVRG6-UqZLH0aD55a:bpy83el) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c3c6d170bc1c234120486f7a8fdc9a04af0b3809/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L366)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Yes please!
</blockquote></details>

@SergeyEzh although it looks like they are already in a method, sorry read too quickly

So don't move them, just add a method level comment explaining what it's for (i.e., feature management)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 2 unresolved discussions (waiting on @SergeyEzh and @zabeen)

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: 3 of 21 files reviewed, 2 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 366 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-Nkou8wqEmDc1lbLCCE3:-NktxQFu1x5z_XnHyhZ1:bb6un1j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c3c6d170bc1c234120486f7a8fdc9a04af0b3809/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L366)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

@SergeyEzh although it looks like they are already in a method, sorry read too quickly

So don't move them, just add a method level comment explaining what it's for (i.e., feature management)
</blockquote></details>

Done
___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 22 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkWAmBW63qbl1LiRdsm:-NktxVkRAFrC3Csoh_fb:bb6un1j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/90fa67257e6317ba6aa9b41b99c25e5304ace964/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L22)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I don't think it would be easy or useful to unit test this. 
You could extend [this integration test fixture](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/Search/SingleDonorSearchTests.cs) with assertion that the following props are being populated:

- ExternalDonorCode
- EthnicityCode
- RegistryCode

You'll need to [set these values in the test donor](https://github.com/Anthony-Nolan/Atlas/blob/03ce5dc7709ad5a7bcb97dc114c863ddee01c46f/Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/Search/SingleDonorSearchTests.cs#L58C31-L58C31)
</blockquote></details>

Done

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: all files reviewed, 4 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Config/FeatureFlags.cs` line 5 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvI1lg98F5sc1Ul_Em:-NkvI1lg98F5sc1Ul_En:b-r5jldg) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm/Config/FeatureFlags.cs#L5)):*
> ```Smalltalk
>     public static class FeatureFlags
>     {
>         // This class is a container for feature flags constants, leave it here even there is no any 
> ```

Please move comment to XML class level comment
___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 369 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvFg8MCzLfaSM68P5i:-NkvFg8MCzLfaSM68P5j:bj6pzsw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L369)):*
> ```Smalltalk
>         private static void RegisterFeatureManager(this IServiceCollection services)
>         {
>             // Feature manager's services should be registered event if features aren't used at the moment
> ```

I like wording of your other comment, please copy it here: "// Feature management, leave it configured even if there is no active feature flags in use"

Also please make it an XML comment on the method itself, i.e., `/// <summary>`
___
*[`Atlas.MatchingAlgorithm.Api/Startup.cs` line 50 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvGFO-CYd3mz8n-Cx8:-NkvGFO-CYd3mz8n-Cx9:b-j4rhpk) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm.Api/Startup.cs#L50)):*
> ```Smalltalk
>         private void AddFeatureManagement(IConfiguration configuration, ConfigurationBuilder builder)
>         {
>             // Feature management, leave it configured even if there is no active feature flags in use
> ```

please make it an XML comment on the method itself, i.e., `/// <summary>`
___
*[`Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/AlgorithmTestingService.cs` line 44 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvH0Ay2B6fsJE6H4Ze:-NkvH0Ay2B6fsJE6H4Zf:bgp2uvt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/AlgorithmTestingService.cs#L44)):*
> ```Smalltalk
>         private static void AddFeatureManagement(IConfigurationBuilder config)
>         {
>             // Feature management, leave it configured even if there is no active feature flags in use
> ```

pls move to `/// <summary>`

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: 15 of 21 files reviewed, 4 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.MatchingAlgorithm/Config/FeatureFlags.cs` line 5 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvI1lg98F5sc1Ul_Em:-NkypdEZEWMGTaUEOfyB:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm/Config/FeatureFlags.cs#L5)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Please move comment to XML class level comment
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs` line 369 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvFg8MCzLfaSM68P5i:-Nkype1k-YgWqtXytjL2:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs#L369)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I like wording of your other comment, please copy it here: "// Feature management, leave it configured even if there is no active feature flags in use"

Also please make it an XML comment on the method itself, i.e., `/// <summary>`
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Api/Startup.cs` line 50 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvGFO-CYd3mz8n-Cx8:-Nkypfj07dD8nB5c2hny:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm.Api/Startup.cs#L50)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please make it an XML comment on the method itself, i.e., `/// <summary>`
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/AlgorithmTestingService.cs` line 44 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141#-NkvH0Ay2B6fsJE6H4Ze:-NkypjP93-Gg9gdE4hKD:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2e7ef7b2948a1aa2bf62cc088b0d3a8b0e94b7ad/Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/AlgorithmTestingService.cs#L44)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

pls move to `/// <summary>`
</blockquote></details>

Done.

**Review by zabeen — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
