### PR TITLE
feature: CBT-1476: Changes to SearchRequestMatchingAlgorithmAttemptTi…

### PR DESCRIPTION
**Pull request by pchenery**
…mings table
https://anthonynolan.atlassian.net/browse/CBT-2758

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368)

### CODE REVIEW

**Review by SergeyEzh — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.SearchTracking.Data/Migrations/20240830163227_AmendSearchRequestMatchingAlgorithmAttemptsTable.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368#-O5mPy7QE8TUjSHLoQqh:-O5mPy7QE8TUjSHLoQqi:b-glqegy) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/1ccd9b22d60b5fc2ed5ee6f33b29666794540a45/Atlas.SearchTracking.Data/Migrations/20240830163227_AmendSearchRequestMatchingAlgorithmAttemptsTable.cs#L16)):*
> ```Smalltalk
>                 schema: "SearchTracking");
> 
>             migrationBuilder.CreateTable(
> ```

If previous migrations are already deployed to uat/prod, I'd suggest to use `migrationBuilder.RenameTable` to not lose data in the table. If not, it is OK to recreate this table with new name/

**Review by SergeyEzh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.SearchTracking.Data/Migrations/20240830163227_AmendSearchRequestMatchingAlgorithmAttemptsTable.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368#-O5mPy7QE8TUjSHLoQqh:-O5maapkCPkkt7AOi0k_:b-arjyg5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/1ccd9b22d60b5fc2ed5ee6f33b29666794540a45/Atlas.SearchTracking.Data/Migrations/20240830163227_AmendSearchRequestMatchingAlgorithmAttemptsTable.cs#L16)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

If previous migrations are already deployed to uat/prod, I'd suggest to use `migrationBuilder.RenameTable` to not lose data in the table. If not, it is OK to recreate this table with new name/
</blockquote></details>

Good to know there's a RenameTable option, thanks. Currently, no SearchTracking tables exist in uat or live, so we should be fine

**Review by SergeyEzh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1368)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
