### PR TITLE
feature: CBT-1476: Send matching algorithm completed event

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 157 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O5SdaAFEi5tczfMVhZI:-O5SdaAFEi5tczfMVhZJ:bxjdz7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/02c13e41a748146c78d7c76a3a7cffd62ae8c905/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L157)):*
> ```Smalltalk
>             // Invalid HLA is treated as an "Expected error" pathway and will not be retried.
>             // This means only a single failure notification will be sent out, and the request message will be completed and not dead-lettered.
>             catch (HlaMetadataDictionaryException hmdException)
> ```

What about this exception? I would suggest to send the search tracking event inside the finally case as we always need to do that
___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs` line 195 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O5ShKGL2q89vuVvtH4T:-O5ShKGMECpHWMJelvZX:b17xa8x) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/02c13e41a748146c78d7c76a3a7cffd62ae8c905/Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs#L195)):*
> ```Smalltalk
>             // Only a single failure notification is sent out and the request message will be completed, not dead-lettered.
> 
>             catch (FluentValidation.ValidationException validationException)
> ```

Same here - please use the finally clause to send the message

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 157 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O5SdaAFEi5tczfMVhZI:-O6fWgyM2QLAa1qWcVgB:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/02c13e41a748146c78d7c76a3a7cffd62ae8c905/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L157)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What about this exception? I would suggest to send the search tracking event inside the finally case as we always need to do that
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs` line 195 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O5ShKGL2q89vuVvtH4T:-O6fWiPd6_TabYpc_tFR:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/02c13e41a748146c78d7c76a3a7cffd62ae8c905/Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs#L195)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same here - please use the finally clause to send the message
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 4 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 85 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vOw6458vuA6qCxhiW:-O6vOw65ASN3koTWw-f_:b-guijpl) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L85)):*
> ```Smalltalk
>             var searchStopWatch = new Stopwatch();
>             var resultsSentTime = new DateTime();
>             var numberOfResults = 0;
> ```

I'd say number of results should be null by default. If there's an error - then it will be null in the database as well
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 86 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vOmrTEmQjftvReA_Y:-O6vOmrTEmQjftvReA_Z:bvupdfz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L86)):*
> ```Smalltalk
>             var resultsSentTime = new DateTime();
>             var numberOfResults = 0;
>             var matchingAlgorithmFailureInfo = new MatchingAlgorithmFailureInfo();
> ```

failure info should be null by default, because if there's no error - then there'll be no failure info
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 166 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vPCN04uGio_Jfw4-F:-O6vPCN04uGio_Jfw4-G:bydcd3v) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L166)):*
> ```Smalltalk
>                 await matchingFailureNotificationSender.SendFailureNotification(identifiedSearchRequest, attemptNumber, 0, hmdException.Message);
> 
>                 matchingAlgorithmFailureInfo.Type = MatchingAlgorithmFailureType.ValidationError;
> ```

Should be HlaMetadataDictionaryError
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 180 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vPKgs6QbvXyQjmhst:-O6vPKgs6QbvXyQjmhsu:b-sibv0e) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L180)):*
> ```Smalltalk
>                     searchRequestMaxRetryCount - attemptNumber);
> 
>                 matchingAlgorithmFailureInfo.Type = MatchingAlgorithmFailureType.ValidationError;
> ```

Should be UnexpectedError

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 85 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vOw6458vuA6qCxhiW:-O6zM9mK6diebtiJtb7D:b-orumjy) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L85)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I'd say number of results should be null by default. If there's an error - then it will be null in the database as well
</blockquote></details>

Good point
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 86 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vOmrTEmQjftvReA_Y:-O6zOD2n2_jtcPCnhlfE:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L86)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

failure info should be null by default, because if there's no error - then there'll be no failure info
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 166 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vPCN04uGio_Jfw4-F:-O6zOSCo66bkj6pUt_-u:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L166)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Should be HlaMetadataDictionaryError
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 180 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O6vPKgs6QbvXyQjmhst:-O6zT_8FAzVQWZQZenJF:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/c0fbd3f3c0f4dd0c48971042203262905322dd4a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L180)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Should be UnexpectedError
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 86 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O7-1x7Q7bsoNbOuOs_0:-O7-1x7Q7bsoNbOuOs_1:bx3shhd) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b3e8156c2977d02e604f0bbda0f0efd15bc9fc5a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L86)):*
> ```Smalltalk
>             var resultsSentTime = new DateTime();
>             int? numberOfResults = null;
>             MatchingAlgorithmFailureInfo? matchingAlgorithmFailureInfo = new MatchingAlgorithmFailureInfo();
> ```

default value should be null, right?

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 86 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O7-1x7Q7bsoNbOuOs_0:-O7-2_6sE5dcy0i6opVp:b-oo43e1) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b3e8156c2977d02e604f0bbda0f0efd15bc9fc5a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L86)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

default value should be null, right?
</blockquote></details>

FailureInfo was null when I tested it with a working message, was trying to avoid a NullReferenceException when testing a HLA exception. Happy to change if there's a better way that I've missed?
 
"CompletionDetails": {
    "IsSuccessful": true,
    "FailureInfo": {
      "Message": null,
      "ExceptionStacktrace": null,
      "Type": null
    },

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 86 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O7-1x7Q7bsoNbOuOs_0:-O73FqPb4itsFGes_rZS:b-iqhpwh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b3e8156c2977d02e604f0bbda0f0efd15bc9fc5a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L86)):*
<details><summary><i>Previously, pchenery wrote…</i></summary><blockquote>

FailureInfo was null when I tested it with a working message, was trying to avoid a NullReferenceException when testing a HLA exception. Happy to change if there's a better way that I've missed?
 
"CompletionDetails": {
    "IsSuccessful": true,
    "FailureInfo": {
      "Message": null,
      "ExceptionStacktrace": null,
      "Type": null
    },
</blockquote></details>

Here the matchingAlgorithmFailureInfo should be null, and then when you fill it, you do:
```
matchingAlgorithmFailureInfo = new MatchingAlgorithmFailureInfo() 
{
  Type = MatchingAlgorithmFailureType.ValidationError,
  Message = validationException.Message,
  ExceptionStacktrace = validationException.StackTrace
}
```

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 86 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365#-O7-1x7Q7bsoNbOuOs_0:-O73XTGX1HXM6ecYTRwN:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/b3e8156c2977d02e604f0bbda0f0efd15bc9fc5a/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L86)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Here the matchingAlgorithmFailureInfo should be null, and then when you fill it, you do:
```
matchingAlgorithmFailureInfo = new MatchingAlgorithmFailureInfo() 
{
  Type = MatchingAlgorithmFailureType.ValidationError,
  Message = validationException.Message,
  ExceptionStacktrace = validationException.StackTrace
}
```
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
