### PR TITLE
feature: #1274: CBT-1474: Implement function for processing search tr…

### PR DESCRIPTION
**Pull request by pchenery**
…acking events

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322)

### CODE REVIEW

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322)* status: all files reviewed, 15 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking/Atlas.SearchTracking.csproj` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ESHZNCcP970zyUYzG:-O0Ei55NBxak3LEmDezV:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking/Atlas.SearchTracking.csproj#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What do we need the Azure.Messaging.ServiceBus for?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking/Atlas.SearchTracking.csproj` line 11 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ESD0T8hyMnoXSF1lP:-O0Ei5mtEW3tvSCq_jGn:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking/Atlas.SearchTracking.csproj#L11)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What do we need the Microsoft.Extensions.Configuration for?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking/Atlas.SearchTracking.csproj` line 21 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ESL7u0JhDbjr4MEFB:-O0EiLeH8okezYxdOOfp:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking/Atlas.SearchTracking.csproj#L21)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Do we need this folder? Is it empty?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking/Services/SearchTrackingProcess.cs` line 8 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ESRHK1bIDt5mXOBlD:-O0EjiZz0REXKSoYKfB6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking/Services/SearchTrackingProcess.cs#L8)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

ISearchTrackingEventProcessor
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking/Services/SearchTrackingProcess.cs` line 13 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ESVAP-BQfZj8ikWgO:-O0EjjGq4_l1cQEHN4DZ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking/Services/SearchTrackingProcess.cs#L13)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

SearchTrackingEventProcessor
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Common/Atlas.SearchTracking.Common.csproj` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ET5yr6-7kulR5QGZf:-O0Ek3987Zgl0A43H21R:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Common/Atlas.SearchTracking.Common.csproj#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Do we need both these dependencies? Maybe Microsoft.Azure.ServiceBus would be enough?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Data/appsettings.json` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ETTG1BaruSyjSaaKl:-O0EqwWQ-EqmWPerz548:b1n6x4c) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Data/appsettings.json#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Is Initial Catalog "Atlas" expected here? Shouldn't it be "AtlasSearchTracking", i.e.?
</blockquote></details>

Not sure, I think it only has to be the name of the database, but obviously happy to change it if it really should!
___
*[`Atlas.SearchTracking.Data/Context/SearchTrackingContext.cs` line 15 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ETgV_9gxg-n1SjWYg:-O0Eka-G0MyAC2BvPSwT:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Data/Context/SearchTrackingContext.cs#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please add a new line after
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/host.json` line 7 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EUYnJ4APjmchywV19:-O0Eklpx9ABsVoRneA0D:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Functions/host.json#L7)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Request;Exception;Event;Trace
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/local.settings.template.json` line 7 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EUqQ4AvqLvzdzPgtv:-O0ElBwyCHJaxcBor63v:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Functions/local.settings.template.json#L7)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What do we need the SearchTrackingMaxDeliveryCount for?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 20 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EV8uVENhxYxTeDe9p:-O0ElmH58uKoAX-8CDJB:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L20)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Instead of using "search-tracking-events", "search-tracking" here shouldn't we use MessagingServiceBus:SearchTrackingTopic and MessagingServiceBus:SearchTrackingSubscription?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 25 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EVdOT25hDgAKR1gHv:-O0EpAYh9vvr7g1CnvKZ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L25)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I would suggest to use Enum.Parse instead of Tryparse - because if it doesn't parse OK, then we should fail, right?
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/Properties/serviceDependencies.json` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EW204EOALQz_JPene:-O0EpHuVE_fogRlfgxAH:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Functions/Properties/serviceDependencies.json#L1)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

No need for this file
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/Properties/serviceDependencies.local.json` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EW3o8E_GvbxqqaWMH:-O0EpWCoCtPwosrSOMCL:bamrmqj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Functions/Properties/serviceDependencies.local.json#L1)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

No need for this file
</blockquote></details>

Can no longer see this file?
___
*[`Atlas.SearchTracking.Common/Settings/ServiceBus/MessagingServiceBusSettings.cs` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0EWKWlBEsq33pJufS7:-O0EqgS85MarJVscHjTz:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Common/Settings/ServiceBus/MessagingServiceBusSettings.cs#L4)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's call these SearchTrackingServiceBusSettings
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking/Atlas.SearchTracking.csproj` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0IiKEUBlY8y0J2nkcX:-O0IiKEUBlY8y0J2nkcY:b-e2fw3y) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/03053df5b0e7f50f3725172fa5b98208f85dc33e/Atlas.SearchTracking/Atlas.SearchTracking.csproj#L11)):*
> ```XML
>   <ItemGroup>
>     <PackageReference Include="Newtonsoft.Json" Version="12.0.3">
>       <TreatAsUsed>true</TreatAsUsed>
> ```

What do we need the TreatAsUsed for?
___
*[`Atlas.SearchTracking.Data/appsettings.json` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0ETTG1BaruSyjSaaKl:-O0IiSA_7x0I0PW9PlMl:bjgtqu0) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0e9561d17f428264145707f53d5139d10c51e7fa/Atlas.SearchTracking.Data/appsettings.json#L10)):*
<details><summary><i>Previously, pchenery wrote…</i></summary><blockquote>

Not sure, I think it only has to be the name of the database, but obviously happy to change it if it really should!
</blockquote></details>

Let's see how the tables get added then separately
___
*[`Atlas.SearchTracking.Test/Services/SearchTrackingProcessTests.cs` line 13 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0Ij64cC7neEcSG3-xi:-O0Ij64cC7neEcSG3-xj:b-w4pipu) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/03053df5b0e7f50f3725172fa5b98208f85dc33e/Atlas.SearchTracking.Test/Services/SearchTrackingProcessTests.cs#L13)):*
> ```Smalltalk
> {
>     [TestFixture]
>     public class SearchTrackingEventProcessorTests
> ```

Please rename the file to match the class name

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322)* status: all files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking/Atlas.SearchTracking.csproj` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0IiKEUBlY8y0J2nkcX:-O0IwIKL1Wz1WmRwSNaI:bbvb1qm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/03053df5b0e7f50f3725172fa5b98208f85dc33e/Atlas.SearchTracking/Atlas.SearchTracking.csproj#L11)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

What do we need the TreatAsUsed for?
</blockquote></details>

Removed the reference altogether
___
*[`Atlas.SearchTracking.Test/Services/SearchTrackingProcessTests.cs` line 13 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322#-O0Ij64cC7neEcSG3-xi:-O0IldfB5qCLq2fwogNa:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/03053df5b0e7f50f3725172fa5b98208f85dc33e/Atlas.SearchTracking.Test/Services/SearchTrackingProcessTests.cs#L13)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please rename the file to match the class name
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1322)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
