### PR TITLE
#919 Report symmetric difference between WMDA donpool/donor type donor id set and Atlas set

### PR DESCRIPTION
**Pull request by disaev-nmdp**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940)* status: all files reviewed, 2 unresolved discussions (waiting on @disaev-nmdp)

___
*[`Atlas.DonorImport/Services/DonorChecker/DonorCheckerBlobStorageClient.cs` line 11 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940#-NSuEHC423zxy7U7JC66:-NSuEHC423zxy7U7JC67:bya3cy9) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bbefb740aa044a4c3e70e9b37a99721ec8b37962/Atlas.DonorImport/Services/DonorChecker/DonorCheckerBlobStorageClient.cs#L11)):*
> ```Smalltalk
>     public interface IDonorCheckerBlobStorageClient
>     {
>         Task UploadResults<T>(T checkerResults, string filename) where T : class;
> ```

Can we add an interface for the results classes so that we don't have just any class in the generic where type constraints here
___
*[`Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940#-NSuEx9076GJlcEVoulc:-NSuEx9076GJlcEVould:bgwngic) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bbefb740aa044a4c3e70e9b37a99721ec8b37962/Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs#L162)):*
> ```Smalltalk
> 
> 
>         public async Task<IReadOnlyCollection<string>> GetExternalDonorCodes(string registryCode, DatabaseDonorType donorType)
> ```

How many will there be - won't it be millions? Are we sure we can go without batching of any kind?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940)* status: all files reviewed, 3 unresolved discussions (waiting on @disaev-nmdp)

___
*[`Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940#-NSuEx9076GJlcEVoulc:-NSzFnvL06-stD5R1Rv3:b25v4p6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bbefb740aa044a4c3e70e9b37a99721ec8b37962/Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs#L162)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

How many will there be - won't it be millions? Are we sure we can go without batching of any kind?
</blockquote></details>

Let's ask Mark to count donors grouped by DonPool, DonorType and see what's the largest group number is

**Review by disaev-nmdp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940)* status: 12 of 17 files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport/Services/DonorChecker/DonorCheckerBlobStorageClient.cs` line 11 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940#-NSuEHC423zxy7U7JC66:-NTJS7jI9PAkL2pbbBV-:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bbefb740aa044a4c3e70e9b37a99721ec8b37962/Atlas.DonorImport/Services/DonorChecker/DonorCheckerBlobStorageClient.cs#L11)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Can we add an interface for the results classes so that we don't have just any class in the generic where type constraints here
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Services/DonorChecker/DonorIdChecker.cs` line 48 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940#-NSzFg0Z2gtBYjkOPfls:-NTJSGMeD-vBCcJN3wVW:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bbefb740aa044a4c3e70e9b37a99721ec8b37962/Atlas.DonorImport/Services/DonorChecker/DonorIdChecker.cs#L48)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's add timing logs 
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs` line 162 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940#-NSuEx9076GJlcEVoulc:-NTJSJHqEWsiPdzV1uR0:bvlr0zp) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bbefb740aa044a4c3e70e9b37a99721ec8b37962/Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs#L162)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's ask Mark to count donors grouped by DonPool, DonorType and see what's the largest group number is
</blockquote></details>

Tested on set of ~15M donors, big memory usage but no memory or timeout exceptions

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @disaev-nmdp)

**Pull request merged**
