### PR TITLE
Issue 636

### PR DESCRIPTION
**Pull request by zabeen**
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @benbelow)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluLfv23OpORmVr2Vv:-MfluLfv23OpORmVr2Vw:ba82lkf) (no related file):*
Blocking on failing snapshot  test & addition of new tests

---

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.Client.Models/Search/Results/ResultsNotification.cs, line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluhPr4WKUVCIwHU4O:-MfluhPr4WKUVCIwHU4P:bm68h3o) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L29)):*
> ```Smalltalk
>         /// The version of the HLA Nomenclature used by the matching algorithm component - used for analysing both donor and patient hla.
>         /// </summary>
>         public string HlaNomenclatureVersion { get; set; }
> ```

I didn't rename this prop as tbh I couldn't be bothered to introduce a breaking API change right now :laughing: But maybe we should... :shrug:

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs, line 106 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mflv5uN-ZjO794dg_qG:-Mflv5uN-ZjO794dg_qH:b-5la5dt) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs#L106)):*
> ```Smalltalk
>         /// will be assigned a default placeholder value to avoid issues in subsequent haplotype/diplotype filtering steps, as `null` has a special meaning.
>         /// </summary>
>         private async Task<PhenotypeInfo<IReadOnlyCollection<string>>> ConvertAllHla(
> ```

I moved this out from the extensions class as it was only being used here, and logic may be bespoke enough to keep it private to expansion. Saying that, I will probably move it to its own service class within same namespace so I can more explicitly unit test.
___
*[Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs, line 145 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mflvmvw56X8fvD8bhGI:-Mflvmvw56X8fvD8bhGJ:bth59iv) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs#L145)):*
> ```Smalltalk
>                     //TODO issue #637 - re-attempt HLA conversion using other approaches
> 
>                     return new List<string> {hlaConversionFailurePlaceholderText};
> ```

I was tempted to return an empty List here instead... it would probably be fine... but felt a placeholder value was safer to avoid any confusion during diplotype filtering

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @benbelow and @zabeen)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluLfv23OpORmVr2Vv:-Mfm7C7i8X7RDtgzluX1:b97a6xd) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Blocking on failing snapshot  test & addition of new tests
</blockquote></details>

snapshot test fixed - still need to add new tests

---

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @benbelow and @zabeen)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluLfv23OpORmVr2Vv:-MfmVIZw3OzPgxpWwdMT:b-hl44fb) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

snapshot test fixed - still need to add new tests
</blockquote></details>

match prob. service tests added - all that's left is to add tests to cover HMD exception suppression during phenotype expansion

---

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs, line 194 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmXEbT72OQvd4WeNUE:-MfmXEbT72OQvd4WeNUF:b-smf937) ([raw file](https://github.com/anthony-nolan/atlas/blob/8e717c2dbc8a5bedee3dc3355e4a1fd37ad11474/Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs#L194)):*
> ```Smalltalk
>             var donorStringGenotypes = donorGenotypes.Select(g => g.ToHlaNames()).ToHashSet();
>             
>             // TODO: ATLAS-233: Re-introduce hardcoded 100% probability for guaranteed match but no represented genotypes
> ```

Btw, I looked up this card, and it's closed as won't fix - but the comment doesn't 100% align with the card description either :thinking:

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs, line 194 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmXEbT72OQvd4WeNUE:-MfmXbp22IsJxT2KMK1i:b3uiffc) ([raw file](https://github.com/anthony-nolan/atlas/blob/8e717c2dbc8a5bedee3dc3355e4a1fd37ad11474/Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs#L194)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Btw, I looked up this card, and it's closed as won't fix - but the comment doesn't 100% align with the card description either :thinking: 
</blockquote></details>

https://anthonynolan.atlassian.net/browse/ATLAS-233

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 8 unresolved discussions (waiting on @zabeen)

___
*[Atlas.Client.Models/Search/Results/ResultsNotification.cs, line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluhPr4WKUVCIwHU4O:-MfmSHbdCdwGRzYUGC-n:bdrr7cm) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L29)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I didn't rename this prop as tbh I couldn't be bothered to introduce a breaking API change right now :laughing: But maybe we should... :shrug: 
</blockquote></details>

I mean, neither WMDA nor AN have started integration work - it's a much better time now than it will be later! 
___
*[Atlas.HlaMetadataDictionary/ExternalInterface/HlaMetadataDictionary.cs, line 63 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmSXHYCwn7fpH0dDxa:-MfmSXHYCwn7fpH0dDxb:bthjcgo) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.HlaMetadataDictionary/ExternalInterface/HlaMetadataDictionary.cs#L63)):*
> ```Smalltalk
>         bool IsActiveVersionDifferentFromLatestVersion();
> 
>         string ActiveHlaNomenclatureVersion { get; }
> ```

`Active` is a bit of a leftover term from the matching algorithm. 

I think it makes some sense in the bool above (as it's saying "is my version up to date" - but for this property I think `HlaNomenclatureVersion` would probably be enough, and have less risk of confusing it with the active/dormant state of matching. 

 
___
*[Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs, line 105 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmT5w66WgCFZRoF0hb:-MfmT5w66WgCFZRoF0hc:bnsv0gs) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs#L105)):*
> ```Smalltalk
>         public FrequencySetMetadata PatientFrequencySetMetadata { get; set; }
> 
>         public string MatchingAlgorithmHlaNomenclatureVersion { get; set; }
> ```

I'm wondering about what this means for the separation of concerns of the MPA and matching - we've otherwise gone to great lengths to ensure MPA can be run independently of any knowledge of Matching, and it doesn't seem unreasonable to expect the MPA to be called on its own - only as debug for now, but as a future feature it isn't unreasonable.

How would you feel about either naming `InputHlaNomeclatureVersion`, (or just leaving this as it was, as it's already in an input class) - and then making it clear in documentation that this should be the version used for matching if run  
___
*[Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs, line 106 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mflv5uN-ZjO794dg_qG:-MfmVXca36VdgzOBJpam:b-3ahc0z) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs#L106)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I moved this out from the extensions class as it was only being used here, and logic may be bespoke enough to keep it private to expansion. Saying that, I will probably move it to its own service class within same namespace so I can more explicitly unit test.
</blockquote></details>

I don't mind having it split out to limit its usage - I do think a new file is wise though, testing aside, to keep each of them a bit more of a manageable size
___
*[Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs, line 145 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mflvmvw56X8fvD8bhGI:-MfmW2FTC6XtSZcZFErI:b9aftjj) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.MatchPrediction/Services/ExpandAmbiguousPhenotype/CompressedPhenotypeExpander.cs#L145)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I was tempted to return an empty List here instead... it would probably be fine... but felt a placeholder value was safer to avoid any confusion during diplotype filtering
</blockquote></details>

Having to use a placeholder text in any context feels quite off to me - I think I'd lean quite strongly towards the empty list approach. It implies "we didn't find any matching hla" to me - and if we need to debug/track this, we have the custom event
___
*[Atlas.MatchPrediction/Services/MatchProbability/GenotypeConverter.cs, line 45 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmXNIUCxqqYBxvTMmt:-MfmXNIUCxqqYBxvTMmu:b4zdkwt) ([raw file](https://github.com/anthony-nolan/atlas/blob/8e717c2dbc8a5bedee3dc3355e4a1fd37ad11474/Atlas.MatchPrediction/Services/MatchProbability/GenotypeConverter.cs#L45)):*
> ```Smalltalk
>             var hlaMetadataDictionary = hlaMetadataDictionaryFactory.BuildDictionary(hlaNomenclatureVersion);
> 
>             using (logger.RunTimed($"Convert genotypes for matching: {subjectLogDescription}", LogLevel.Verbose))
> ```

`matching` tends to be used to mean the matching algorithm. Would the subtle change to `match calculation` make this clearer? It would for me, but perhaps only for me 😅
___
*[Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs, line 194 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmXEbT72OQvd4WeNUE:-MfmXlLT-JcsbZd9KDyA:bm5eaqw) ([raw file](https://github.com/anthony-nolan/atlas/blob/8e717c2dbc8a5bedee3dc3355e4a1fd37ad11474/Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs#L194)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

https://anthonynolan.atlassian.net/browse/ATLAS-233
</blockquote></details>

I think let's remove this. We probably have to seek out much more impactful changes if we do pick up performance work again, and we'll need to investigate/triage at that point anyway.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 8 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs, line 105 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmT5w66WgCFZRoF0hb:-MfmYajW9P80A8Mv5P7f:b9052t4) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs#L105)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I'm wondering about what this means for the separation of concerns of the MPA and matching - we've otherwise gone to great lengths to ensure MPA can be run independently of any knowledge of Matching, and it doesn't seem unreasonable to expect the MPA to be called on its own - only as debug for now, but as a future feature it isn't unreasonable.

How would you feel about either naming `InputHlaNomeclatureVersion`, (or just leaving this as it was, as it's already in an input class) - and then making it clear in documentation that this should be the version used for matching if run  
</blockquote></details>

It's still valid to pass this in, keeping in mind issue #637, as we would need to know the matching algorithm version to do the "previous allele names" lookup, in the case where our initial attempt at phenotype conversion fails.

I wouldn't want to call it "Input..." as that implies we are always using it in MPA - whereas, we only need it for a specific case, where we can't find the allele in the HF set version.

I could add a TODO comment explaining why it's still needed at all... cuz as of this PR, it has become temporarily redundant

**Review by benbelow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 8 unresolved discussions (waiting on @zabeen)

___
*[Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs, line 105 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmT5w66WgCFZRoF0hb:-MfmisbI2ZLtX420v4Gz:b-i0585o) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs#L105)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

It's still valid to pass this in, keeping in mind issue #637, as we would need to know the matching algorithm version to do the "previous allele names" lookup, in the case where our initial attempt at phenotype conversion fails.

I wouldn't want to call it "Input..." as that implies we are always using it in MPA - whereas, we only need it for a specific case, where we can't find the allele in the HF set version.

I could add a TODO comment explaining why it's still needed at all... cuz as of this PR, it has become temporarily redundant


</blockquote></details>

I'd still like to *either* 

(a) come up with a different name that still makes sense in the case when we call the debug endpoints that perform MPA on its own
(b) make it optional - so that if we *don't* provide this noemclature version, we don't have the ability to fallback, and will treat newer versioned HLA as unrepresented.

**Review by benbelow — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 8 unresolved discussions (waiting on @zabeen)

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 14 of 24 files reviewed, 7 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.Client.Models/Search/Results/ResultsNotification.cs, line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluhPr4WKUVCIwHU4O:-MfmYCx777S5se9GFlSN:b-tl1b3q) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L29)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I mean, neither WMDA nor AN have started integration work - it's a much better time now than it will be later! 
</blockquote></details>

does this affect versioning?

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 14 of 24 files reviewed, 4 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.HlaMetadataDictionary/ExternalInterface/HlaMetadataDictionary.cs, line 63 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmSXHYCwn7fpH0dDxa:-Mfn5wyQB0L1_HE_kIJu:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.HlaMetadataDictionary/ExternalInterface/HlaMetadataDictionary.cs#L63)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

`Active` is a bit of a leftover term from the matching algorithm. 

I think it makes some sense in the bool above (as it's saying "is my version up to date" - but for this property I think `HlaNomenclatureVersion` would probably be enough, and have less risk of confusing it with the active/dormant state of matching. 

 
</blockquote></details>

Done.
___
*[Atlas.MatchPrediction/Services/MatchProbability/GenotypeConverter.cs, line 45 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmXNIUCxqqYBxvTMmt:-Mfn65J23eR31cKzLcID:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/8e717c2dbc8a5bedee3dc3355e4a1fd37ad11474/Atlas.MatchPrediction/Services/MatchProbability/GenotypeConverter.cs#L45)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

`matching` tends to be used to mean the matching algorithm. Would the subtle change to `match calculation` make this clearer? It would for me, but perhaps only for me 😅
</blockquote></details>

Done.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 10 of 32 files reviewed, 4 unresolved discussions (waiting on @benbelow)

___
*[Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs, line 105 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmT5w66WgCFZRoF0hb:-Mfn6Yt8CBHkqmDVmkEv:b-891lyt) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs#L105)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I'd still like to *either* 

(a) come up with a different name that still makes sense in the case when we call the debug endpoints that perform MPA on its own
(b) make it optional - so that if we *don't* provide this noemclature version, we don't have the ability to fallback, and will treat newer versioned HLA as unrepresented. 
</blockquote></details>

c) if it's not being used by MPA right now, just delete it from input model - and worry about naming etc when we get to #637?

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 10 of 32 files reviewed, 3 unresolved discussions (waiting on @benbelow)

___
*[Atlas.Client.Models/Search/Results/ResultsNotification.cs, line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluhPr4WKUVCIwHU4O:-Mfn8EiC5sybtMLm7U5h:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L29)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

does this affect versioning?
</blockquote></details>

Done.

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r7, 14 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[Atlas.Client.Models/Search/Results/ResultsNotification.cs, line 29 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfluhPr4WKUVCIwHU4O:-Mfn9uxg9mH-xZP4VUfl:b-mr2vua) ([raw file](https://github.com/anthony-nolan/atlas/blob/1140af305c108ae6989312502ab05bc1060877d0/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L29)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we should add it to our changelog for 1.1 for sure. Given there are no consumers, I think having a "breaking change" in 1.1 is better than going live with v2 for the first time 😅
___
*[Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs, line 105 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmT5w66WgCFZRoF0hb:-MfnAVD38tR-U5eNIaco:b2zw7bh) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs#L105)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

c) if it's not being used by MPA right now, just delete it from input model - and worry about naming etc when we get to #637?
</blockquote></details>

ahaha that works for me!

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: 23 of 35 files reviewed, 1 unresolved discussion (waiting on @benbelow)

___
*[Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs, line 105 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfmT5w66WgCFZRoF0hb:-MfnK9O8Ed40TZrKx5dp:b-uzg0g5) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fb125b07cde4e9b73053adc322dbab115ab3692/Atlas.MatchPrediction/ExternalInterface/Models/MatchProbability/MatchProbabilityInput.cs#L105)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

ahaha that works for me!
</blockquote></details>

went with c) :smile:

**Review by benbelow — APPROVED** [review]
we'll need a version bump, and to introduce a changelog. 

Don't mind merging this early if you want to start testing - but we should have those before the JIRA card can be closed. 

> Reviewed 11 of 12 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638#-:-MfqgiUW5G09mJIf0nTj:b-f1wdnh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by zabeen — COMMENTED** [review]
Yeah was going to change log after merge to unblock testing 

> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638#-:-Mfqhhl297hU2jRu4CBO:b-gbpq9j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by benbelow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/638#-MfrNkCr63zvKPQlqYS_:-MfrNkCr63zvKPQlqYSa:b-skanj9) (no related file):*
@benbelow you seem busy so I've rebased this onto my second "version chores" PR, so I can get on with writing the changelog

---

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 2 unresolved discussions (waiting on @zabeen)

___
*[Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md, line 2 at r11](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mfr_3ucBd0MWPjbgRgf:-Mfr_3ucBd0MWPjbgRgg:b-3wezjl) ([raw file](https://github.com/anthony-nolan/atlas/blob/7875cee7808893b3a6f3e82ed876866b956c1120/Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md#L2)):*
> ```Markdown
> # Changelog
> All notable data structure changes to this project will be documented in this file.
> ```

"data structure" seems a bit out of place here
___
*[Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md, line 5 at r11](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mfr_6fsCr2Ywgi21S79:-Mfr_6fsCr2Ywgi21S7A:b-apx9ts) ([raw file](https://github.com/anthony-nolan/atlas/blob/7875cee7808893b3a6f3e82ed876866b956c1120/Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md#L5)):*
> ```Markdown
> 
> This includes both schema and data workflow changes.
> ```

I think we should make it clear that this is the changelog for Atlas as a product - I know it's called `PublicApi` because of the project its in, but it's worth being clear that this will cover functional (e.g. algorithmic) changes that affect Atlas as a whole but don't change the public Api explciitly.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: all files reviewed, 2 unresolved discussions (waiting on @benbelow and @zabeen)

___
*[Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md, line 5 at r11](https://reviewable.io/reviews/anthony-nolan/atlas/638#-Mfr_6fsCr2Ywgi21S79:-Mfre4rV9Fr8xw3kk1ic:b-w8sneg) ([raw file](https://github.com/anthony-nolan/atlas/blob/7875cee7808893b3a6f3e82ed876866b956c1120/Atlas.Functions.PublicApi/CHANGELOG_PublicApi.md#L5)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I think we should make it clear that this is the changelog for Atlas as a product - I know it's called `PublicApi` because of the project its in, but it's worth being clear that this will cover functional (e.g. algorithmic) changes that affect Atlas as a whole but don't change the public Api explciitly. 
</blockquote></details>

made changes on my other PR

**Review by benbelow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/638)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request closed without merging**
