### PR TITLE
Renamed Dpb1MismatchDirection to MismatchDirection

### PR DESCRIPTION
**Pull request by WMDAJesse**
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/663)

### CODE REVIEW

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/663)* status: all files reviewed, 1 unresolved discussion (waiting on @WMDAJesse)

___
*[Atlas.Client.Models/Search/Results/Matching/PerLocus/LocusSearchResult.cs, line 54 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/663#-MrNXJoE-atl0_ddi99T:-MrNXJoE-atl0_ddi99U:b-ttvq7) ([raw file](https://github.com/anthony-nolan/atlas/blob/5b760e0fc7ff5efafaf7558ce80e04d851496eea/Atlas.Client.Models/Search/Results/Matching/PerLocus/LocusSearchResult.cs#L54)):*
> ```Smalltalk
>         
>         /// <summary>
>         /// Indicates the direction of the DPB1 mismatch, when there is a DPB1 mismatch.
> ```

this documentation will need updating as well

**Review by benbelow — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WMDAJesse)

**Review by benbelow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WMDAJesse)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/663#-MrWSXsTAN8qS-Lpauiz):*
something I haven't picked up on in previous reviews, and I don't think it should be blocking, but: 

for the rest of Atlas development, we've used a couple of conventions to make the git history easier to read for future developers / support engineers.

(a) we've used semantic tags e.g. `feature:` / `chore:` / `fix:` to indicate what type of change we're making
(b) We've linked to the JIRA or Github issue that the ticket relates to as a commit message prefix.

Would you be ok to adopt these conventions moving forward?

**Comment by WMDAJesse** [comment]
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/663#-MrWSXsTAN8qS-Lpauiz):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

something I haven't picked up on in previous reviews, and I don't think it should be blocking, but: 

for the rest of Atlas development, we've used a couple of conventions to make the git history easier to read for future developers / support engineers.

(a) we've used semantic tags e.g. `feature:` / `chore:` / `fix:` to indicate what type of change we're making
(b) We've linked to the JIRA or Github issue that the ticket relates to as a commit message prefix.

Would you be ok to adopt these conventions moving forward?
</blockquote></details>

No problem. I can do that

**Review by benbelow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @WMDAJesse)

**Pull request merged**
