### PR TITLE
996 mismatch orientation

### PR DESCRIPTION
**Pull request by zabeen**
Use scoring result to re-orientate match prediction categories.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @zabeen)

___
*[`Atlas.Client.Models/Search/Results/MatchPrediction/MatchProbabilityPerLocusResponse.cs` line 17 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004#-NYtS36NEnKnvS8dgM1e:-NYtS36NEnKnvS8dgM1f:by6tdl0) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/1a37e5a811b56e86ffef2b624ddcce90cd02dafa/Atlas.Client.Models/Search/Results/MatchPrediction/MatchProbabilityPerLocusResponse.cs#L17)):*
> ```Smalltalk
>             {
>                 matchProbabilities = value;
>                 PositionalMatchCategories = CalculatePositionalMatchCategories(matchProbabilities);
> ```

I need to move the “Calculate” and set step out of the model

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
