### PR TITLE
feature: CBT-2878: Add endpoints for scoring and batch scoring to Atl…

### PR DESCRIPTION
**Pull request by pchenery**
…as Public API

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)* status: all files reviewed, 6 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Client.Models/Scoring/ScoringResult.cs` line 1 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBYDqO3SepbuGRyGkP:-OBBYDqO3SepbuGRyGkQ:bpc150u) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/ScoringResult.cs#L1)):*
> ```Smalltalk
> using Atlas.Client.Models.Search.Results.Matching.PerLocus;
> ```

Which models are reused from Atlas.Client.Models.Search.Results?
I'd suggest to move the to Atlas.Client.Models.Common.Results
___
*[`Atlas.Client.Models/Scoring/ScoringResult.cs` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBYOgS4sA9z9cTUX8p:-OBBYOgS4sA9z9cTUX8q:b43iifm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/ScoringResult.cs#L4)):*
> ```Smalltalk
> using Atlas.Client.Models.Search.Results.Matching;
> 
> namespace Atlas.Client.Models.Scoring
> ```

Please move this to Atlas.Client.Models.Scoring.Results
___
*[`Atlas.Client.Models/Scoring/IdentifiedDonorHla.cs` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBXhs-9cig-BLYhS4l:-OBBXhs-9cig-BLYhS4m:b-iosibd) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/IdentifiedDonorHla.cs#L3)):*
> ```Smalltalk
> using Atlas.Common.Public.Models.GeneticData.PhenotypeInfo.TransferModels;
> 
> namespace Atlas.Client.Models.Scoring
> ```

Please put this into Atlas.Client.Models.Scoring.Requests folder
___
*[`Atlas.Client.Models/Scoring/ScoringRequest.cs` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBXLpxBDsxJbU3huTM:-OBBXLpxBDsxJbU3huTN:bo625ls) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/ScoringRequest.cs#L10)):*
> ```Smalltalk
>         public PhenotypeInfoTransfer<string> PatientHla { get; set; }
> 
>         public ScoringCriteria ScoringCriteria { get; set;        }
> ```

extra spaces before `}`
___
*[`Atlas.Client.Models/Scoring/ScoringRequest.cs` line 21 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBX84a7wgcAuuvdhcG:-OBBX84a7wgcAuuvdhcH:b-r6rdff) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/ScoringRequest.cs#L21)):*
> ```Smalltalk
>     /// Request to score multiple donors against a patient
>     /// </summary>
>     public class BatchScoringRequest : ScoringRequest
> ```

Let's call this DonorHlaBatchScoringRequest
___
*[`Atlas.Client.Models/Scoring/ScoringCriteria.cs` line 6 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBXzWX8Lj6_aa4HETb:-OBBXzWX8Lj6_aa4HETc:b-9m19wf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/ScoringCriteria.cs#L6)):*
> ```Smalltalk
> namespace Atlas.Client.Models.Scoring
> {
>     public class ScoringCriteria
> ```

We already have https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Client.Models/Search/Requests/SearchRequest.cs#L89

Let's move it to Please put this into Atlas.Client.Models.Common.Requests folder and reuse so that we don't have to create one more class

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)* status: all files reviewed, 7 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Client.Models/Scoring/ScoringRequest.cs` line 4 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OBBZUJM-eYeQ7eCMpm4:-OBBZUJM-eYeQ7eCMpm5:b-iosibd) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5018e1eb6843d0b90437586bbd40cddc455357a4/Atlas.Client.Models/Scoring/ScoringRequest.cs#L4)):*
> ```Smalltalk
> using System.Collections.Generic;
> 
> namespace Atlas.Client.Models.Scoring
> ```

Please put this into Atlas.Client.Models.Scoring.Requests folder

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 45 of 45 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)* status: all files reviewed, 4 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Client.Models/Scoring/Requests/IdentifiedDonorHla.cs` line 5 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-CCHl5YUh5QY6SNbi:-OC-CCHm--GiqhsD7e0s:b-g9e6ua) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Scoring/Requests/IdentifiedDonorHla.cs#L5)):*
> ```Smalltalk
> namespace Atlas.Client.Models.Scoring.Requests
> {
>     public class IdentifiedDonorHla : PhenotypeInfoTransfer<string>
> ```

All other scoring-related classes are in one file. Do we really need a separate fie for this class?
___
*[`Atlas.Client.Models/Common/Requests/SearchRequest.cs` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-BqFEEX18HRs9bCqv:-OC-BqFF5W_yoLiofZKi:buktdef) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Common/Requests/SearchRequest.cs#L11)):*
> ```Smalltalk
> // ReSharper disable UnusedAutoPropertyAccessor.Global
> 
> namespace Atlas.Client.Models.Common.Requests
> ```

This model should still be in Atlas.Client.Models.Search.Requests - only the models that are reused between scoring and search requests need to go to the common folder - supposedly ScoringCriteria
___
*[`Atlas.Client.Models/Scoring/Requests/ScoringRequest.cs` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-CwBPB6tPVZw8aDy7:-OC-CwBPB6tPVZw8aDy8:b-pi1ymb) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Scoring/Requests/ScoringRequest.cs#L11)):*
> ```Smalltalk
>         public PhenotypeInfoTransfer<string> PatientHla { get; set; }
> 
>         public ScoringCriteria ScoringCriteria{ get; set; }
> ```

Missing space before `{`
___
*[`Atlas.Client.Models/Scoring/Results/ScoringResult.cs` line 1 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-CPVDDnU0a-aR_k7q:-OC-CPVDDnU0a-aR_k7r:b557nyy) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Scoring/Results/ScoringResult.cs#L1)):*
> ```Smalltalk
> using Atlas.Client.Models.Search.Results.Matching.PerLocus;
> ```

I would expect this class not to use any using from the Atlas.Client.Models.Search.Results folder.
Let's move all common classes to Atlas.Client.Models.Common.Results

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)* status: all files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.Client.Models/Common/Requests/SearchRequest.cs` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-BqFEEX18HRs9bCqv:-OC2mERtEhmZX1poveqa:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Common/Requests/SearchRequest.cs#L11)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This model should still be in Atlas.Client.Models.Search.Requests - only the models that are reused between scoring and search requests need to go to the common folder - supposedly ScoringCriteria
</blockquote></details>

Done.
___
*[`Atlas.Client.Models/Scoring/Requests/IdentifiedDonorHla.cs` line 5 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-CCHl5YUh5QY6SNbi:-OC2miUD-hI1SfQ9XpHi:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Scoring/Requests/IdentifiedDonorHla.cs#L5)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

All other scoring-related classes are in one file. Do we really need a separate fie for this class?
</blockquote></details>

Done.
___
*[`Atlas.Client.Models/Scoring/Requests/ScoringRequest.cs` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-CwBPB6tPVZw8aDy7:-OC2mtQEAedwbKNm6Iee:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Scoring/Requests/ScoringRequest.cs#L11)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Missing space before `{`
</blockquote></details>

Done.
___
*[`Atlas.Client.Models/Scoring/Results/ScoringResult.cs` line 1 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC-CPVDDnU0a-aR_k7q:-OC30vyC5PAOejO7netf:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/83bb6e2ca0b999435e916428e4a1c22ef88fc923/Atlas.Client.Models/Scoring/Results/ScoringResult.cs#L1)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I would expect this class not to use any using from the Atlas.Client.Models.Search.Results folder.
Let's move all common classes to Atlas.Client.Models.Common.Results
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 74 of 74 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.Client.Models/Atlas.Client.Models.csproj` line 31 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378#-OC84RT93yyqHGDRVf3M:-OC84RT93yyqHGDRVf3N:b-ffk8a5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/76542063472ad176a11a9ca4e502119dac6f5e13/Atlas.Client.Models/Atlas.Client.Models.csproj#L31)):*
> ```XML
> 
>   <ItemGroup>
>     <Folder Include="Scoring\Results\Matching\PerLocus\" />
> ```

Do you need this folder? Is it empty now?

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1378)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
