### PR TITLE
fix: #1100: Repeat search failing at matching algorithm

### PR DESCRIPTION
**Pull request by IgorKupreychik**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs` line 84 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106#-NhQT70H0G5UGrDAHMJr:-NhQT70H0G5UGrDAHMJs:b-u2pbsu) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/757212e0af407ea2740b4f5c9311c36fa896b36e/Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs#L84)):*
> ```Smalltalk
>             {
>                 ExternalDonorCode = externalDonorCode,
>                 AtlasId = allDonorsUpdatedSinceCutoff.TryGetValue(externalDonorCode, out var atlasId)
> ```

Do we need this check? Won't the results contain correct AtlasDonorId at all times?

**Comment by IgorKupreychik** [comment]
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs` line 84 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106#-NhQT70H0G5UGrDAHMJr:-NhQUaCJAkUi0myW0U4y:beursdf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/757212e0af407ea2740b4f5c9311c36fa896b36e/Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs#L84)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Do we need this check? Won't the results contain correct AtlasDonorId at all times?
</blockquote></details>

That's a good question. I believe results should always contain the correct AtlasDonorId, but at the same time I can't understand why initially it was implemented the way to pull AtlasDonorId not from the results and was there any specific logic behind it? Do you think we should always pull AtlasDonorId just from results?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs` line 84 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106#-NhQT70H0G5UGrDAHMJr:-NhQdFkW3jjNgx_5eu9J:b-xctx42) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/757212e0af407ea2740b4f5c9311c36fa896b36e/Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs#L84)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

That's a good question. I believe results should always contain the correct AtlasDonorId, but at the same time I can't understand why initially it was implemented the way to pull AtlasDonorId not from the results and was there any specific logic behind it? Do you think we should always pull AtlasDonorId just from results?
</blockquote></details>

I'd always put the Atlas Id from the results, otherwise we're introducing a logic that's hard to debug

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
