### PR TITLE
#953 add matching start time

### PR DESCRIPTION
**Pull request by disaev-nmdp**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)* status: all files reviewed, 3 unresolved discussions (waiting on @disaev-nmdp)

___
*[`Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs` line 77 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUfUqUO6rov3imluu9c:-NUfUqUO6rov3imluu9d:b5qbrij) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fc5639f6de3f8fca0e28cdb905279426673d8e3c/Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs#L77)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// DateTime that the request was picked up for processing (equivalent to dequeued time for queued requests)
> ```

"that the matching request"



_Code quote:_
```Smalltalk
that the request
```
___
*[`Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs` line 79 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUfUj4xDtjDWmsqEDEK:-NUfUj4xDtjDWmsqEDEL:beyz8uu) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fc5639f6de3f8fca0e28cdb905279426673d8e3c/Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs#L79)):*
> ```Smalltalk
>         /// DateTime that the request was picked up for processing (equivalent to dequeued time for queued requests)
>         /// </summary>
>         public DateTimeOffset SearchStartTime { get; set; }
> ```

Please rename to `MatchingStartTime` for clarity on which part of search we mean
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 21 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUfUyM88dgGQqeRhOHU:-NUfUyM88dgGQqeRhOHV:b-d90cec) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fc5639f6de3f8fca0e28cdb905279426673d8e3c/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L21)):*
> ```Markdown
> * Ensure all failed search requests are reported as completed by routing dead-lettered search request messages to the `search-results-ready` topic, with the appropriate failure information.
> * Added performance logs for initial search.
> * Added search and repeat search start time to matching result set
> ```

"Added matching request start time to result set"



_Code quote:_
```Markdown
Added search and repeat search start time to matching result set
```

**Review by zabeen — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)* status: all files reviewed, 2 unresolved discussions (waiting on @disaev-nmdp)

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)* status: all files reviewed, 3 unresolved discussions (waiting on @disaev-nmdp)

___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 18 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUg2re518KOzWueB3QX:-NUg2re518KOzWueB3QY:b-ujm1zw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2d4d2058d80f207fc3f19c3f51143ddba9aacab4/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L18)):*
> ```Markdown
> * Bug fix: Stopped excessive number of `CreateContainer` API calls being made during blob download.
> 
> #### Search
> ```

Will also need to extend the client changelog with info on the new property:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Client.Models/CHANGELOG_Client.md#160

**Review by disaev-nmdp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs` line 77 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUfUqUO6rov3imluu9c:-NUgLnjr0bkVZu8YnWVL:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fc5639f6de3f8fca0e28cdb905279426673d8e3c/Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs#L77)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

"that the matching request"
</blockquote></details>

Done.
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 21 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUfUyM88dgGQqeRhOHU:-NUgLmLB6PbCBMsJspUx:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fc5639f6de3f8fca0e28cdb905279426673d8e3c/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L21)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

"Added matching request start time to result set"
</blockquote></details>

Done.
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 18 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965#-NUg2re518KOzWueB3QX:-NUgLlwaBH5sMPeGyjoJ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2d4d2058d80f207fc3f19c3f51143ddba9aacab4/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L18)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Will also need to extend the client changelog with info on the new property:
https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.Client.Models/CHANGELOG_Client.md#160
</blockquote></details>

Done.

**Review by zabeen — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @disaev-nmdp)

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @disaev-nmdp)

**Pull request merged**
