### PR TITLE
feature: #1066: Set up Matching Algorithm Feature Flag Infrastructure…

### PR DESCRIPTION
**Pull request by IgorKupreychik**
… via Azure App Configuration

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da and @IgorKupreychik)

___
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfKssVU9YoA67h6gweo:bvf2i0l) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
> ```Smalltalk
> namespace Atlas.Common.FeatureManagement
> {
>     public abstract class AtlasFeatureManager
> ```

Add interface `IAtlasFeatureManager` with method `Task<bool> IsFeatureEnabled(string featureName)` and use in DI, will make mocking out easier
___
*[`Atlas.MatchingAlgorithm/Services/Donors/DonorHelper.cs` line 40 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKtge6B7m0IE-tl3Uv:-NfKtge6B7m0IE-tl3Uw:b-ixdpj7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm/Services/Donors/DonorHelper.cs#L40)):*
> ```Smalltalk
>             return isFeatureEnabled
>                 ? GetDonorLookupFromMatchResults(reifiedScoredMatches)
>                 : await LoadDonorLookupFromDatabase(reifiedScoredMatches);
> ```

suggest rename to `LoadDonorLookupFromDonorStore`
___
*[`Atlas.MatchingAlgorithm.Functions/Startup.cs` line 55 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKuvbS3VMU5VAzfvUc:-NfKuvbS3VMU5VAzfvUd:b-bmu921) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm.Functions/Startup.cs#L55)):*
> ```Smalltalk
>         public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
>         {
>             var azureConfigurationConnectionString = Environment.GetEnvironmentVariable("AzureAppConfiguration:ConnectionString");
> ```

`OptionsReaderFor<T>()` is being used elsewhere in this class, any reason we can't use it to retrieve the conn string after registering the setting below?
___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 36 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKvRXv2ecyvEpKOuA1:-NfKvRXv2ecyvEpKOuA2:b-t6e99k) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L36)):*
> ```Smalltalk
>             donorReader.GetDonors(Arg.Any<IEnumerable<int>>()).Returns(new List<Donor> { new Donor { ExternalDonorCode = "donor_from_database" } }.ToDictionary(_ => 1, v => v.ToPublicDonor()));
> 
>             configurationRefresherProvider = Substitute.For<IConfigurationRefresherProvider>();
> ```

this setup will be simplified if you add new interface `IAtlasFeatureManager`
___
*[`Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs` line 145 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKvvQq281FNS1vuRKC:-NfKvvQq281FNS1vuRKD:by5vsly) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs#L145)):*
> ```Smalltalk
>             services.AddSingleton<ILogger, FileBasedLogger>();
> 
>             var featureManagerSnapshot = Substitute.For<IFeatureManagerSnapshot>();
> ```

Similarly here, new interface means you can just mock out `IAtlasFeatureManager`
___
*[`Atlas.RepeatSearch.Functions/Startup.cs` line 40 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKwKUc1zZp1O-LkX3A:-NfKwKUc1zZp1O-LkX3B:bdhdp6u) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.RepeatSearch.Functions/Startup.cs#L40)):*
> ```Smalltalk
>         }
> 
>         public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
> ```

ah, good catch that we need to also update repeat search! :thumbsup:

**Comment by IgorKupreychik** [comment]
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfL3fvP3DmrLMrSgpQ-:b-cqk4vy) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Add interface `IAtlasFeatureManager` with method `Task<bool> IsFeatureEnabled(string featureName)` and use in DI, will make mocking out easier
</blockquote></details>

It would require adding SupportedFeatures at the interface level as well which doesn't make sense

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchingAlgorithm.Functions/Startup.cs` line 55 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKuvbS3VMU5VAzfvUc:-NfL4IMo8pkADw16fW6z:bde3dh9) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm.Functions/Startup.cs#L55)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

`OptionsReaderFor<T>()` is being used elsewhere in this class, any reason we can't use it to retrieve the conn string after registering the setting below?
</blockquote></details>

I've already explained it in Teams...

**Comment by IgorKupreychik** [comment]
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 36 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKvRXv2ecyvEpKOuA1:-NfL4hAoCUEoEV7kG0o7:b-p8q0kj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L36)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

this setup will be simplified if you add new interface `IAtlasFeatureManager`
</blockquote></details>

see the comment above why we shouldn't use interface here

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: 33 of 34 files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da and @IgorKupreychik)

___
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfL68irEZGCQ9eqtndr:b-pvtdri) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

It would require adding SupportedFeatures at the interface level as well which doesn't make sense
</blockquote></details>

It is possible and acceptable for interfaces to have props, e.g., https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.HlaMetadataDictionary/ExternalInterface/HlaMetadataDictionary.cs#L64

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: 33 of 34 files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da and @IgorKupreychik)

___
*[`Atlas.MatchingAlgorithm.Functions/Startup.cs` line 55 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKuvbS3VMU5VAzfvUc:-NfL7bMo9zAfWqJ3Lrg0:b-gyv7jl) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.MatchingAlgorithm.Functions/Startup.cs#L55)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

I've already explained it in Teams... 

</blockquote></details>

Yes, I remember that, it just looks so enticing in the code because it's being passed in a few lines above :laughing:

**Comment by IgorKupreychik** [comment]
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfL7yXPB9_RpYhzZGKe:bjyskn7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

It is possible and acceptable for interfaces to have props, e.g., https://github.com/Anthony-Nolan/Atlas/blob/38e6a6298858269aa1159c39b40dd0fe33bee882/Atlas.HlaMetadataDictionary/ExternalInterface/HlaMetadataDictionary.cs#L64
</blockquote></details>

I didn't say it's not possible, I said it doesn't make sense in this particular case. What's the purpose of this? Just to simplify testing a bit? However, on the other hand, via the interface we would exposing the information (SupportedFeatures) which shouldn't be exposed at all since it must be used only internally by *FeatureManager* classes

**Review by zabeen — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da and @IgorKupreychik)

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 33 of 34 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 5 unresolved discussions (waiting on @IgorKupreychik and @zabeen)

___
*[`terraform/core/app_configuration.tf` line 1 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfL9xAw-LYUbstu7ib2:-NfL9xAxCX5dG8MH7ULc:b-gdodm4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/32d21d05256fc8786104503c4cb54e57da3675e3/terraform/core/app_configuration.tf#L1)):*
> ```HCL
> resource "azurerm_app_configuration" "atlas_config" {
> ```

I'd call this resource atlas_app_configuration so that its type is obvious from its name

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 5 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfL9o8tBRSpwNvzB97p:b-p2o2yq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

I didn't say it's not possible, I said it doesn't make sense in this particular case. What's the purpose of this? Just to simplify testing a bit? However, on the other hand, via the interface we would exposing the information (SupportedFeatures) which shouldn't be exposed at all since it must be used only internally by *FeatureManager* classes
</blockquote></details>

Looking at the changeset, `SupportedFeatures` doesn't have to be part of the interface. 

The DonorHelper service that uses `IAtlasFeatureManager` only accesses the method, `IsFeatureEnabled`, but not `SupportedFeatures`. 

I can't actually find a usage for the prop other than it being overriden in the concrete class.

**Comment by IgorKupreychik** [comment]
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfLDGSC-tlz2cFqNwx8:b-v78jq5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Looking at the changeset, `SupportedFeatures` doesn't have to be part of the interface. 

The DonorHelper service that uses `IAtlasFeatureManager` only accesses the method, `IsFeatureEnabled`, but not `SupportedFeatures`. 

I can't actually find a usage for the prop other than it being overriden in the concrete class.
</blockquote></details>

If we expose only `IsFeatureEnabled` what type should DonorHelper accept then? AtlasFeatureManager or IAtlasFeatureManager? 
And what type MatchingAlgorithmFeatureManager has to inherit/implement? AtlasFeatureManager or IAtlasFeatureManager?

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da and @IgorKupreychik)

___
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfLFPe697yX3KeDWwXQ:baazksg) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

If we expose only `IsFeatureEnabled` what type should DonorHelper accept then? AtlasFeatureManager or IAtlasFeatureManager? 
And what type MatchingAlgorithmFeatureManager has to inherit/implement? AtlasFeatureManager or IAtlasFeatureManager?
</blockquote></details>

DonorHelper should accept the interface

abstract AtlasFeatureManager will inherit from the interface

Matching...Manager inherits from the abstract base class (and by extension, will also inherit from interface)

`SupportedFeatures` should remain a protected abstract prop, and `IsFeatureEnabled` should use it to check whether the flag string value being provided is actually supported or not (throw argument / not supported exception if not a valid value)

**Comment by IgorKupreychik** [comment]
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfLJJuq6wliIDWAbOGH:beuj79m) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

DonorHelper should accept the interface

abstract AtlasFeatureManager will inherit from the interface

Matching...Manager inherits from the abstract base class (and by extension, will also inherit from interface)

`SupportedFeatures` should remain a protected abstract prop, and `IsFeatureEnabled` should use it to check whether the flag string value being provided is actually supported or not (throw argument / not supported exception if not a valid value)
</blockquote></details>

Hold on, I just realized, that SupportedFeatures is not used at all... I probably added it looking at the samples you provided in the ticket, but now I'm not even sure if we need it at all since my implementation is different, than the one from samples... I see your point about throwing exception if the feature is not supported, but it just adds an artificial limitation... Moreover it adds an additional complexity with managing feature manager classes specific for each module... Please confirm if we really need it or if that property can be removed and we would just use AtlasFeatureManager instead of the module specific version.

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da and @IgorKupreychik)

___
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfLQtUXC4rq3bO9CpCF:blfba9) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
> if that property can be removed and we would just use AtlasFeatureManager instead of the module specific version
yes, let's do this, but please also do the interface change as well :wink:

**Review by zabeen — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 5 unresolved discussions (waiting on @IgorKupreychik)

**Comment by IgorKupreychik** [comment]
*[`Atlas.Common/FeatureManagement/AtlasFeatureManager.cs` line 9 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfKssVU9YoA67h6gwen:-NfLaH2p3nInXKSQUlgC:b-535ue0) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/659ce48ae5006874e99087869168896542c2fc4e/Atlas.Common/FeatureManagement/AtlasFeatureManager.cs#L9)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

> if that property can be removed and we would just use AtlasFeatureManager instead of the module specific version
yes, let's do this, but please also do the interface change as well :wink:
</blockquote></details>

done :)

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 6 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 36 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfLiEpl3o3JhlCddGFh:-NfLiEpl3o3JhlCddGFi:b-z8jzq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a8ddc04e7520b47e3582bd809223aa3c86bbf2d4/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L36)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task GetDonorLookup_FeatureFlagDisabled_GetsDataFromDatabase()
> ```

FromDonorStore



_Code quote:_
```Smalltalk
FromDatabase
```
___
*[`Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs` line 64 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfLiVQi4K6mQWuABKw4:-NfLiVQi4K6mQWuABKw5:b-et39l4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a8ddc04e7520b47e3582bd809223aa3c86bbf2d4/Atlas.MatchingAlgorithm.Test/Services/Donors/DonorHelperTests.cs#L64)):*
> ```Smalltalk
>             var donor = actual.FirstOrDefault();
>             donor.Should().NotBeNull();
>             donor.Value.ExternalDonorCode.Should().Be("donor_from_database");
> ```

from_donor_store



_Code quote:_
```Smalltalk
from_database
```
___
*[`Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs` line 144 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfLjCzjBjyra6vYPH0s:-NfLjCzjBjyra6vYPH0t:b-qtzilg) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a8ddc04e7520b47e3582bd809223aa3c86bbf2d4/Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs#L144)):*
> ```Smalltalk
>             services.AddSingleton<ILogger, FileBasedLogger>();
> 
>             var atlasFeatureManager = Substitute.For<IAtlasFeatureManager>();
> ```

do you also need to mock out the method call, i.e., IsFeatureEnabled(default).ReturnsForAnyArgs... ?
___
*[`Atlas.Common/FeatureManagement/FeatureFlags.cs` line 1 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082#-NfLhRNs1ExxhP_cjWiM:-NfLgzeU33HnSk_ApypZ:b-ogjbhn) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/a8ddc04e7520b47e3582bd809223aa3c86bbf2d4/Atlas.Common/FeatureManagement/FeatureFlags.cs#L1)):*
> ```Smalltalk
> namespace Atlas.MatchingAlgorithm.Services.FeatureManagement
> ```

update namespace after file move

however, I think this enum would be better off in `Atlas.MatchingAlgorithm.Config` to make it clear it's a FF that configures the behaviour of Matching Algorithm

**Review by zabeen — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 2 unresolved discussions (waiting on @IgorKupreychik)

**Review by zabeen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 7 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
