### PR TITLE
chore: #902: Move to using Azure.Storage.Blobs and stop making unnece…

### PR DESCRIPTION
**Pull request by zabeen**
…ssary CreateContainer requests when fetching blobs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907#-NQVBf6G7S76CurEesSL:-NQVBf6G7S76CurEesSM:b-p2f1bs) (no related file):*
Blocking comment as I'm still testing these changes...

___

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907#-NQVBf6G7S76CurEesSL:-NQVUl--5FNfyzoLvZpS:bdahvf2) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Blocking comment as I'm still testing these changes...
</blockquote></details>

Testing on AN-dev passed but the blobs were being written as `application/octet-stream` - not a breaking change, but have made small code change to set to `text/plain` just to be consistent with previous implementation

___

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @daria-sorokina-da)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/907#-NQVBf6G7S76CurEesSL:-NQVbqsQ6Ubb6qEJHhZn:b67zezn) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Testing on AN-dev passed but the blobs were being written as `application/octet-stream` - not a breaking change, but have made small code change to set to `text/plain` just to be consistent with previous implementation
</blockquote></details>

All working now

___

**Pull request merged**
