### PR TITLE
New debug client package added with donor import endpoints

### PR DESCRIPTION
**Pull request by zabeen**
Still need to add endpoints for alerts/notifications and matching algorithm, but I'll do that in the next PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.Debug.Client/ClientConfiguration.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210#-NpQlz47D5k8l6rmBta1:-NpQlz47D5k8l6rmBta2:bua6ck7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bac2fef270184a4249d179659c9a81bdb7d5feeb/Atlas.Debug.Client/ClientConfiguration.cs#L33)):*
> ```Smalltalk
>             Func<IServiceProvider, DonorImportHttpFunctionSettings> fetchDonorImportHttpSettings)
>         {
>             services.AddHttpClient<IDonorImportClient, DonorImportClient>((sp, client) =>
> ```

FYI, am using .Net `IHttpClientFactory` to create and manage instances of HttpClient, which means we don't have to do it ourselves.

I am not sure how well known this factory is (I only learned about it whilst working on this ticket!). I can add a comment to explain its benefits, if it's not clear?

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

___
*[`Atlas.Debug.Client/ClientConfiguration.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210#-NpQlz47D5k8l6rmBta1:-NpUG5CiBvn61r7me2rB:bdrnbgz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bac2fef270184a4249d179659c9a81bdb7d5feeb/Atlas.Debug.Client/ClientConfiguration.cs#L33)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

FYI, am using .Net `IHttpClientFactory` to create and manage instances of HttpClient, which means we don't have to do it ourselves.

I am not sure how well known this factory is (I only learned about it whilst working on this ticket!). I can add a comment to explain its benefits, if it's not clear?
</blockquote></details>

Haven't used it before, but I think the code is self-explanatory

**Review by SergeyEzh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.Debug.Client/ClientConfiguration.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210#-NpQlz47D5k8l6rmBta1:-NpU5PfP7TwfRuCltcIP:bmyz56q) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bac2fef270184a4249d179659c9a81bdb7d5feeb/Atlas.Debug.Client/ClientConfiguration.cs#L33)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

FYI, am using .Net `IHttpClientFactory` to create and manage instances of HttpClient, which means we don't have to do it ourselves.

I am not sure how well known this factory is (I only learned about it whilst working on this ticket!). I can add a comment to explain its benefits, if it's not clear?
</blockquote></details>

It is well documented here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-8.0
Perhaps, it worth to leave this link somewhere. It was introduced in asp.net core 2.1,  but I learned about it only 2 years ago.
___
*[`Atlas.Debug.Client/ClientConfiguration.cs` line 41 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210#-NpUA2eyEsKEUezo1yEO:-NpUA2eyEsKEUezo1yEP:b-qquvhr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bac2fef270184a4249d179659c9a81bdb7d5feeb/Atlas.Debug.Client/ClientConfiguration.cs#L41)):*
> ```Smalltalk
>             });
> 
>             services.AddSingleton<IDonorImportClient, DonorImportClient>(sp =>
> ```

`AddHttpClient` should have already registered `IDonorHelper` as transient service there's no need to register it again. I see you're providing here ApiKey, but you can do the same with `AddHttpClient` using corresponding overload : `AddHttpClient<TClient,TImplementation>(IServiceCollection, String, Func<HttpClient,IServiceProvider,TImplementation>)`


Also, it is very important that you're trying to register `DonorImportClient` as singleton. This prevents `IHttpClientFactory` from managing client instances: Just one instance of `DonorImportClient`, `HttpClient` and `HttpMessageHandler` will be created and will live forever. It isn't so bad if we configure underlying `HttpMessageHandler` properly, but this is what `IHttClientFactory`for. To let us not worry about low-level details. 

So it is better to leave `IDonorImportClient` transient. It is cheap to create HttpClient itself, slowest part is creating `HttpMessageHandler` but `IHttpClientFactory` use shared pool of them so it will be fast. And unlike singlton registration, it will be destroying and recreating them `HttpMessageHandler` over time. This will allow to react on DNS changes, to close connection when it isn't used for long time and so on.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.Debug.Client/ClientConfiguration.cs` line 41 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210#-NpUA2eyEsKEUezo1yEO:-NpUIKDwDpJMzMEpdupz:bd6mmyt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bac2fef270184a4249d179659c9a81bdb7d5feeb/Atlas.Debug.Client/ClientConfiguration.cs#L41)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

`AddHttpClient` should have already registered `IDonorHelper` as transient service there's no need to register it again. I see you're providing here ApiKey, but you can do the same with `AddHttpClient` using corresponding overload : `AddHttpClient<TClient,TImplementation>(IServiceCollection, String, Func<HttpClient,IServiceProvider,TImplementation>)`


Also, it is very important that you're trying to register `DonorImportClient` as singleton. This prevents `IHttpClientFactory` from managing client instances: Just one instance of `DonorImportClient`, `HttpClient` and `HttpMessageHandler` will be created and will live forever. It isn't so bad if we configure underlying `HttpMessageHandler` properly, but this is what `IHttClientFactory`for. To let us not worry about low-level details. 

So it is better to leave `IDonorImportClient` transient. It is cheap to create HttpClient itself, slowest part is creating `HttpMessageHandler` but `IHttpClientFactory` use shared pool of them so it will be fast. And unlike singlton registration, it will be destroying and recreating them `HttpMessageHandler` over time. This will allow to react on DNS changes, to close connection when it isn't used for long time and so on.
</blockquote></details>

Thanks, I was unclear about this, I am glad you picked up on it because I was going to ask if this "double" registration makes sense!

I will implement your suggestion in the next PR I am working on today.

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.Debug.Client/ClientConfiguration.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210#-NpQlz47D5k8l6rmBta1:-NpUIeBX83iJiYpn86jW:b-cfj7zw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/bac2fef270184a4249d179659c9a81bdb7d5feeb/Atlas.Debug.Client/ClientConfiguration.cs#L33)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

It is well documented here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-8.0
Perhaps, it worth to leave this link somewhere. It was introduced in asp.net core 2.1,  but I learned about it only 2 years ago.
</blockquote></details>

Thanks for the feedback!

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

**Review by SergeyEzh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1210)* status: 22 of 45 files reviewed, all discussions resolved (waiting on @daria-sorokina-da)

**Pull request merged**
