### PR TITLE
653 donors import upsert

### PR DESCRIPTION
**Pull request by IgorZhuravlevDataArt**
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @benbelow and @IgorZhuravlevDataArt)

___
*[README_DonorImport.md, line 103 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9lTex-CxnXVVwr0uo:-Mo9lTex-CxnXVVwr0up:bpuj5t8) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L103)):*
> ```
> Error then update 
> ```
Is this for the case when donor already existed?
If not, I see it as "Create, then update (values from Upsert stands)"
___
*[README_DonorImport.md, line 108 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9mT3NAmlygwN1pPmd:-Mo9mT3NAmlygwN1pPme:b-rtnz96) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L108)):*
> ```
> Donor updated and not deleted, no error
> ```
Why are we changing "No donor, no error" to "Donor updated and not deleted, no error"? 
Update will produce an updated record, while Delete will remove the donor. Or do you mean we won't delete it because of upload time check?
___
*[README_DonorImport.md, line 109 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9m3iaAL6lXwB7cD_R:-Mo9m3iaAL6lXwB7cD_S:b-rbuhmf) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L109)):*
> ```
> No donor, error
> ```
This would be New donor, won't it?
___
*[README_DonorImport.md, line 109 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9oKs85Vbprf1Yf3ck:-Mo9oKs85Vbprf1Yf3cl:b-okdjc7) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L109)):*
> ```
> Donor updated and not deleted, no error
> ```
Same here - won't we delete the donor?

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: all files reviewed, 14 unresolved discussions (waiting on @IgorZhuravlevDataArt)

___
*[Atlas.DonorImport/Services/DonorFileImporter.cs, line 149 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9i8Uk89OpJKswgN4B:-Mo9i8Uk89OpJKswgN4C:b-xqwcoy) ([raw file](https://github.com/anthony-nolan/atlas/blob/e97f01a23c6448f532ce0b61441c909bab347b86/Atlas.DonorImport/Services/DonorFileImporter.cs#L149)):*
> ```Smalltalk
>         {
>             var validationResult = searchableDonorValidator.Validate(donorUpdate);
>             logger.SendTrace($"Invalid Donor found with Id: {donorUpdate.RecordId}", LogLevel.Verbose);
> ```

:o 

good spot! 
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DonorValidationTests.cs, line 86 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9iMyZDQn02PhBbbZq:-Mo9iMyZDQn02PhBbbZr:b-kmvbrb) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DonorValidationTests.cs#L86)):*
> ```Smalltalk
>                     .With(upd => upd.ChangeType, ImportDonorChangeType.Edit)
>                     .Build();
>             modifiedDonor.Hla.A = null;
> ```

we should amend the builder to ensure this data is created correctly in the first place, rather than modifying it once it's been created. 

Same for other tests in this file. 
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 191 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9jlw78CNAAlMPdFix:-Mo9jlw78CNAAlMPdFiy:b-rid1su) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L191)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task DonorImportOrder_CreateThenUpsertOutOfOrder_ThrowsException()
> ```

Is `ThrowsException` correct here? From the look of the assertions, it will notify support, then not update the donor - but not throw...

This seems to be the case throughout the suite, including pre-existing tests. Am I missing something? 
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 207 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9j_QKCUIG8i3qqjxk:-Mo9j_QKCUIG8i3qqjxl:b-x95oza) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L207)):*
> ```Smalltalk
>             result1.UpdateFile.Should().Be(file2Name);
> 
>             // Import File 2, it should throw exception and donor remain unchanged
> ```

I think this should say File 1!
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 474 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9lxizAflV3VbQiciE:-Mo9lxizAflV3VbQiciF:b-biail4) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L474)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task DonorImportOrder_UpdateThenUpsertWithExistingDonor_UpdatesAndRejectsSecondUpsert()
> ```

the body of this test doesn't look like it's rejecting the second upsert?
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 639 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9m8PJ8x3t98yJEGkA:-Mo9m8PKCqR5QhqWaWVb:b47xfim) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L639)):*
> ```Smalltalk
>             result1.UpdateFile.Should().Be(initialFileName);
> 
>             // Import File 2, Exception and donor unchanged
> ```

I think this comment is wrong - should be `Import File 1, donor updated`
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 807 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9mPFQ9q03MkGgkxbp:-Mo9mPFQ9q03MkGgkxbq:b-rzy2w0) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L807)):*
> ```Smalltalk
>             result1.Should().BeNull();
> 
>             // Import File 1, Donor created
> ```

I thought this should "Throw Error", according to the test name?
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 53 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9nH5GCg-NqCnIMQUc:-Mo9nH5GCg-NqCnIMQUd:b1mv09u) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L53)):*
> ```Smalltalk
>                 mockServiceBusClient = Substitute.For<IMessagingServiceBusClient>();
>                 var services = DependencyInjection.ServiceConfiguration.BuildServiceCollection();
>                 services.AddScoped(sp => mockServiceBusClient);
> ```

I think if we really do want a new mock each test - then we could think about changing this to `AddTransient` to ensure every provided mock is a new one. 
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 73 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9n1Ps1ZKfmZromV3J:-Mo9n1Ps1ZKfmZromV3K:b2k8r3o) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L73)):*
> ```Smalltalk
>         public async Task SetUp()
>         {
>             mockServiceBusClient = DependencyInjection.DependencyInjection.Provider.GetService<IMessagingServiceBusClient>(); //We want a new one of these every time, for ease of asserting calls.
> ```

I'm not convinced I trust this comment - without explicitly starting a new scope, is it true that this will actually be a new mock each time?

Also, we're clearing received calls in the TearDown method - which implies we *are* sharing this mock between tests after all!
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 93 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9nPGh092jkEgfSyce:-Mo9nPGi9GE4DIyCGdr6:b-rv6m3z) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L93)):*
> ```Smalltalk
>             TestStackTraceHelper.CatchAndRethrowWithStackTraceInExceptionMessage(() =>
>             {
>                 mockServiceBusClient.ClearReceivedCalls();
> ```

if we're making a new mock every test, I think it's misleading to keep this clear call here. 
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 99 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9nh7t-UGOu71D_jHh:-Mo9nh7t-UGOu71D_jHi:b2bo59h) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L99)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task ImportDonors_ForUpsert_CreateDonors_IfNotExist()
> ```

this doesn't quite match the test naming convention used throughout the project elsewhere, of

`UnitUnderTest_Conditions_Expectation`. 

It's quite minor, but I think it would be good to stay consistent within the project. 

e.g. `ImportDonors_ForUpsert_WhenDonorsDoNotExist_CreatesDonors`

**Review by IgorZhuravlevDataArt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: 6 of 10 files reviewed, 14 unresolved discussions (waiting on @benbelow and @daria-sorokina-da)

___
*[README_DonorImport.md, line 103 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9lTex-CxnXVVwr0uo:-MoDf8dIEJCeev9mlGIy:be4thnv) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L103)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

> ```
> Error then update 
> ```
Is this for the case when donor already existed?
If not, I see it as "Create, then update (values from Upsert stands)"
</blockquote></details>

Yes, it is the case when donor already existed. I added more tests and table row for the case when the donor is not exist.
___
*[README_DonorImport.md, line 108 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9mT3NAmlygwN1pPmd:-MoDfaTaD6QDGHH3R9rG:b-syxxhx) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L108)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

> ```
> Donor updated and not deleted, no error
> ```
Why are we changing "No donor, no error" to "Donor updated and not deleted, no error"? 
Update will produce an updated record, while Delete will remove the donor. Or do you mean we won't delete it because of upload time check?


</blockquote></details>

Exactly, importing files are checking against the upload time
___
*[README_DonorImport.md, line 109 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9m3iaAL6lXwB7cD_R:-MoDgGwF-QWBFWaNR-ch:b-1eh3wi) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L109)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

> ```
> No donor, error
> ```
This would be New donor, won't it?
</blockquote></details>

Sure, done.
___
*[README_DonorImport.md, line 109 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9oKs85Vbprf1Yf3ck:-MoDgiV7E0bpXYqUhmQ1:b-e5b3m2) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/README_DonorImport.md#L109)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

> ```
> Donor updated and not deleted, no error
> ```
Same here - won't we delete the donor?
</blockquote></details>

No, because the latest operation is Upsert
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DonorValidationTests.cs, line 86 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9iMyZDQn02PhBbbZq:-MoE1TBa16d4jJ4P0FaE:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DonorValidationTests.cs#L86)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

we should amend the builder to ensure this data is created correctly in the first place, rather than modifying it once it's been created. 

Same for other tests in this file. 
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 191 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9jlw78CNAAlMPdFix:-MoE8MeK2521dmVA_MUt:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L191)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

Is `ThrowsException` correct here? From the look of the assertions, it will notify support, then not update the donor - but not throw...

This seems to be the case throughout the suite, including pre-existing tests. Am I missing something? 
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 207 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9j_QKCUIG8i3qqjxk:-MoE8jha2I8ljYqk9E-V:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L207)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I think this should say File 1!
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 474 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9lxizAflV3VbQiciE:-MoE9N2iCNbvcoc4I7i9:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L474)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

the body of this test doesn't look like it's rejecting the second upsert?
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 639 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9m8PJ8x3t98yJEGkA:-MoE9hQLC7QPdHoCPvRt:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L639)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I think this comment is wrong - should be `Import File 1, donor updated`
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs, line 807 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9mPFQ9q03MkGgkxbp:-MoE9y3p7BvE_3Pa2z0J:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs#L807)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I thought this should "Throw Error", according to the test name?
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 53 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9nH5GCg-NqCnIMQUc:-MoEA_Xy-LOGSXCVsUdX:b-atlcqt) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L53)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I think if we really do want a new mock each test - then we could think about changing this to `AddTransient` to ensure every provided mock is a new one. 
</blockquote></details>

Done. Have sense, thank you!
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 73 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9n1Ps1ZKfmZromV3J:-MoEBVqbBEy8Kpn4kYoC:b-4j1p9r) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L73)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

I'm not convinced I trust this comment - without explicitly starting a new scope, is it true that this will actually be a new mock each time?

Also, we're clearing received calls in the TearDown method - which implies we *are* sharing this mock between tests after all!
</blockquote></details>

Done. Sorry, it was copy-pasted from other similar tests
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 93 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9nPGh092jkEgfSyce:-MoEDSVc5KodE-21e1Gs:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L93)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

if we're making a new mock every test, I think it's misleading to keep this clear call here. 
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 99 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9nh7t-UGOu71D_jHh:-MoEEpMF7bB4O_UeWGjz:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L99)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

this doesn't quite match the test naming convention used throughout the project elsewhere, of

`UnitUnderTest_Conditions_Expectation`. 

It's quite minor, but I think it would be good to stay consistent within the project. 

e.g. `ImportDonors_ForUpsert_WhenDonorsDoNotExist_CreatesDonors`
</blockquote></details>

Done.

**Review by benbelow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: all files reviewed, 6 unresolved discussions (waiting on @daria-sorokina-da and @IgorZhuravlevDataArt)

___
*[README_DonorImport.md, line 104 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/654#-MoEFV2U5KEb6aiB1ey6:-MoEFV2U5KEb6aiB1ey7:b6qlvyz) ([raw file](https://github.com/anthony-nolan/atlas/blob/dce0e2a5b3783402ff79de71b3d7b77c9016d4b4/README_DonorImport.md#L104)):*
> ```Markdown
> | Update  | Delete | No donor              | No donor                      | No Donor in either case so this is fine                                                                |
> | Upsert  | Create | Update then error     | Error then update             | This should be fine, the second create will be disregarded, support will be alerted                    |
> | Upsert*  | Create | Create then error     | Create then discard changes  | *Where donor already existed                    |
> ```

in revieable it thinks these two `*` are making italics! If it's the same in github we may need a different character for this
___
*[README_DonorImport.md, line 104 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/654#-MoEFc609ay6JvP4dq-P:-MoEFc609ay6JvP4dq-Q:b-c5t8lo) ([raw file](https://github.com/anthony-nolan/atlas/blob/dce0e2a5b3783402ff79de71b3d7b77c9016d4b4/README_DonorImport.md#L104)):*
> ```Markdown
> | Update  | Delete | No donor              | No donor                      | No Donor in either case so this is fine                                                                |
> | Upsert  | Create | Update then error     | Error then update             | This should be fine, the second create will be disregarded, support will be alerted                    |
> | Upsert*  | Create | Create then error     | Create then discard changes  | *Where donor already existed                    |
> ```

Is this correct? 

Assuming the donor exists already, I'd expect the "in order" case to be "Update then error"

and the out of order case to be "error then update"
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 73 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9n1Ps1ZKfmZromV3J:-MoEG83T5VHh4GUEYoOj:b-hrpef) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L73)):*
<details><summary><i>Previously, IgorZhuravlevDataArt wrote…</i></summary><blockquote>

Done. Sorry, it was copy-pasted from other similar tests
</blockquote></details>

makes sense, no worries! Just stands as a reminder that what's already written isn't necessarily always correct (especially when code iterates over time and things get missed from an update), and that we should always be willing to challenge existing code :)

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 4 of 6 files at r2, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorZhuravlevDataArt)

___
*[Atlas.DonorImport/Services/DonorRecordChangeApplier.cs, line 145 at r6](https://reviewable.io/reviews/anthony-nolan/atlas/654#-MoEOwWuBo1vYuf8vuZv:-MoEOwWuBo1vYuf8vuZw:bl00qjv) ([raw file](https://github.com/anthony-nolan/atlas/blob/c10a9d5afbd900de8f353a0443e2f471c73cae6a/Atlas.DonorImport/Services/DonorRecordChangeApplier.cs#L145)):*
> ```Smalltalk
>         }
> 
>         /// Processes a collection of donor updates as UPSERTS - i.e. if the donor already exists, update it - if not, create it.
> ```

Was opening <summary> removed intentionally?

**Review by IgorZhuravlevDataArt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @benbelow and @daria-sorokina-da)

___
*[README_DonorImport.md, line 104 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/654#-MoEFV2U5KEb6aiB1ey6:-MoEO_D522D8TswJZpN4:b-pu16jg) ([raw file](https://github.com/anthony-nolan/atlas/blob/dce0e2a5b3783402ff79de71b3d7b77c9016d4b4/README_DonorImport.md#L104)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

in revieable it thinks these two `*` are making italics! If it's the same in github we may need a different character for this
</blockquote></details>

Github thinks the same, but only in edit mode. The final markup looks well
___
*[README_DonorImport.md, line 104 at r5](https://reviewable.io/reviews/anthony-nolan/atlas/654#-MoEFc609ay6JvP4dq-P:-MoEPil8C0sZRBMEYQmI:b-naod1u) ([raw file](https://github.com/anthony-nolan/atlas/blob/dce0e2a5b3783402ff79de71b3d7b77c9016d4b4/README_DonorImport.md#L104)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

Is this correct? 

Assuming the donor exists already, I'd expect the "in order" case to be "Update then error"

and the out of order case to be "error then update"
</blockquote></details>

Sure! I've mixed up the cases
___
*[Atlas.DonorImport/Services/DonorRecordChangeApplier.cs, line 145 at r6](https://reviewable.io/reviews/anthony-nolan/atlas/654#-MoEOwWuBo1vYuf8vuZv:-MoET21_2mjYpKTETYTL:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/c10a9d5afbd900de8f353a0443e2f471c73cae6a/Atlas.DonorImport/Services/DonorRecordChangeApplier.cs#L145)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Was opening <summary> removed intentionally?
</blockquote></details>

Done.
___
*[Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs, line 73 at r4](https://reviewable.io/reviews/anthony-nolan/atlas/654#-Mo9n1Ps1ZKfmZromV3J:-MoEQA0RDGzbdH21VnuU:b-30yfwl) ([raw file](https://github.com/anthony-nolan/atlas/blob/6fedf970d90ffd3faa5ed233013c95134aef0670/Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs#L73)):*
<details><summary><i>Previously, benbelow (Ben Below) wrote…</i></summary><blockquote>

makes sense, no worries! Just stands as a reminder that what's already written isn't necessarily always correct (especially when code iterates over time and things get missed from an update), and that we should always be willing to challenge existing code :) 
</blockquote></details>

Sounds good :)

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 4 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/654)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorZhuravlevDataArt)

**Pull request merged**
