### PR TITLE
feature: CBT-3444: Add index to Donors on RegistryCode, DonorType and…

### PR DESCRIPTION
**Pull request by pchenery**
… LastUpdated

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.DonorImport.Data/Migrations/DonorContextModelSnapshot.cs` line 107 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODujJxX4-XDcCJDGFJk:-ODujJxX4-XDcCJDGFJl:bvc3tso) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/514e9ba4e3c5a2c76cd2f67f00ee63ee49a5cd89/Atlas.DonorImport.Data/Migrations/DonorContextModelSnapshot.cs#L107)):*
> ```Smalltalk
>                     SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LastUpdated"), new[] { "ExternalDonorCode" });
> 
>                     b.HasIndex("RegistryCode", "DonorType", "LastUpdated");
> ```

If we decide to add included properties - please describe it here https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#included-columns
___
*[`Atlas.DonorImport.Data/Migrations/20241212112028_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs` line 11 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODuipM1-Qhu54FFiA__:-ODuipM1-Qhu54FFiA_a:bn35j7v) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/514e9ba4e3c5a2c76cd2f67f00ee63ee49a5cd89/Atlas.DonorImport.Data/Migrations/20241212112028_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs#L11)):*
> ```Smalltalk
>         private const string createIndexSql = @"
>             if not exists (SELECT 1 FROM sys.indexes WHERE name = 'IX_Donors_RegistryCode_DonorType_LastUpdated' AND object_id = OBJECT_ID('Donors.Donors'))
> 	            CREATE INDEX [IX_Donors_RegistryCode_DonorType_LastUpdated] ON Donors.Donors([RegistryCode], [DonorType], [LastUpdated]) WITH (ONLINE = ON);
> ```

Do we need to return the whole donor info, or just the Donor Ids for the task?

If it's just the donor ids, can we add an INCLUDE statement to make the index size smaller?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.DonorImport.Data/Models/Donor.cs` line 152 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODuk71S6KbZiFPZv0Wt:-ODuk71S6KbZiFPZv0Wu:b-zv45t) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/514e9ba4e3c5a2c76cd2f67f00ee63ee49a5cd89/Atlas.DonorImport.Data/Models/Donor.cs#L152)):*
> ```Smalltalk
>             donorModel.HasIndex(d => d.Hash);
>             donorModel.HasIndex(d => d.LastUpdated).IncludeProperties(d => d.ExternalDonorCode);
>             donorModel.HasIndex(d => new{d.RegistryCode, d.DonorType, d.LastUpdated});
> ```

If we decide to add included properties - please describe it here [https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#included-columns](https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#included-columns)

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Migrations/20241212112028_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs` line 11 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODuipM1-Qhu54FFiA__:-ODvfZrF8cf5jVCgbRqK:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/514e9ba4e3c5a2c76cd2f67f00ee63ee49a5cd89/Atlas.DonorImport.Data/Migrations/20241212112028_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs#L11)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Do we need to return the whole donor info, or just the Donor Ids for the task?

If it's just the donor ids, can we add an INCLUDE statement to make the index size smaller?
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Data/Models/Donor.cs` line 152 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODuk71S6KbZiFPZv0Wt:-ODvffqk1HYB9GzIpL8E:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/514e9ba4e3c5a2c76cd2f67f00ee63ee49a5cd89/Atlas.DonorImport.Data/Models/Donor.cs#L152)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

If we decide to add included properties - please describe it here [https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#included-columns](https://learn.microsoft.com/en-us/ef/core/modeling/indexes?tabs=data-annotations#included-columns)
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery)

___
*[`Atlas.DonorImport.Data/Migrations/20241212145111_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs` line 10 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODzt8AEA1eLUsAycAXH:-ODzt8AEA1eLUsAycAXI:bt1j6v2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/d1d50f5db009539ef6ce8ede08856e289c10e63f/Atlas.DonorImport.Data/Migrations/20241212145111_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs#L10)):*
> ```Smalltalk
>     {
>         private const string createIndexSql = @"
>             if not exists (SELECT 1 FROM sys.indexes WHERE name = 'IX_Donors_RegistryCode_DonorType_LastUpdated' AND object_id = OBJECT_ID('Donors.Donors'))
> ```

Let's do some cleanup:

1) if not exists -> IF NOT EXISTS
2) don't we need BEGIN and END inside IF NOT EXISTS? Ex. https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorImportRepository.cs#L141

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.DonorImport.Data/Migrations/20241212145111_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs` line 10 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387#-ODzt8AEA1eLUsAycAXH:-OE-Eumy4ADpDqbvsSYe:b-dakait) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/d1d50f5db009539ef6ce8ede08856e289c10e63f/Atlas.DonorImport.Data/Migrations/20241212145111_IndexDonorsOnRegistryCodeDonorTypeLastUpdated.cs#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's do some cleanup:

1) if not exists -> IF NOT EXISTS
2) don't we need BEGIN and END inside IF NOT EXISTS? Ex. https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorImportRepository.cs#L141
</blockquote></details>

The example I found didn't use BEGIN/END, but have added them in

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1387)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
