### PR TITLE
feature: CBT-1475: Update search tracking message event type

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 26 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2y3FKgEZp9oaG3mkoH:-O2y3FKgEZp9oaG3mkoI:b461oes) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6f20b794ba687fe7bf15a89b9040c7c35f9d5d/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L26)):*
> ```Smalltalk
>         {
>             var body = Encoding.UTF8.GetString(message.Body);
>             var eventType = Enum.Parse<SearchTrackingEventType>(message.ApplicationProperties.GetValueOrDefault("SearchTrackingEventType").ToString());
> ```

Can we move this constant to Atlas.SearchTracking.Common? I suppose it's used by both sender and reader of the messages

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 26 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2y3FKgEZp9oaG3mkoH:-O2y4_-k5nb6kFoitEPE:b5sg3n5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6f20b794ba687fe7bf15a89b9040c7c35f9d5d/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L26)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Can we move this constant to Atlas.SearchTracking.Common? I suppose it's used by both sender and reader of the messages
</blockquote></details>

Sorry, which constant do you mean?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 26 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2y3FKgEZp9oaG3mkoH:-O2y5UEO-QIXtjNGyYLn:b-i7j1l7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6f20b794ba687fe7bf15a89b9040c7c35f9d5d/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L26)):*
<details><summary><i>Previously, pchenery wrote…</i></summary><blockquote>

Sorry, which constant do you mean?
</blockquote></details>

The "EventType" string

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 26 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2y3FKgEZp9oaG3mkoH:-O2y8XhiCqARf6TJini4:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6f20b794ba687fe7bf15a89b9040c7c35f9d5d/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L26)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

The "EventType" string
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking.Common/Config/SearchTrackingConstants.cs` line 5 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2ybIae8idsOpdRREx6:-O2ybIae8idsOpdRREx7:bell4fv) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/57b89cc610fcfa2fdf501e5e8e5493a6559a8701/Atlas.SearchTracking.Common/Config/SearchTrackingConstants.cs#L5)):*
> ```Smalltalk
>     public static class SearchTrackingConstants
>     {
>         public const string SearchTrackingEventType = "EventType";
> ```

Please use this constant in the client that sends the search tracking event
___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 13 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2ybPKL91kXIDW6f_-b:-O2ybPKL91kXIDW6f_-c:b6fmfkj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/57b89cc610fcfa2fdf501e5e8e5493a6559a8701/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L13)):*
> ```Smalltalk
>     {
>         private readonly ISearchTrackingEventProcessor searchTrackingEventProcessor;
>         private const string EventType = SearchTrackingConstants.SearchTrackingEventType;
> ```

We don't need the private constant here

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking.Common/Config/SearchTrackingConstants.cs` line 5 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2ybIae8idsOpdRREx6:-O2ydfP97aDF42G6vxCX:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/57b89cc610fcfa2fdf501e5e8e5493a6559a8701/Atlas.SearchTracking.Common/Config/SearchTrackingConstants.cs#L5)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please use this constant in the client that sends the search tracking event
</blockquote></details>

Done.
___
*[`Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs` line 13 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2ybPKL91kXIDW6f_-b:-O2ydf4O2PfRNblhf1xp:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/57b89cc610fcfa2fdf501e5e8e5493a6559a8701/Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs#L13)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

We don't need the private constant here
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.SearchTracking.Common/Clients/SearchTrackingServiceBusClient.cs` line 19 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2yeX1p7NtWSs5NH3W3:-O2yeX1p7NtWSs5NH3W4:bx2vfa1) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ee08fde5416d32f7a9721995accba870d73fdb92/Atlas.SearchTracking.Common/Clients/SearchTrackingServiceBusClient.cs#L19)):*
> ```Smalltalk
>         private readonly string connectionString;
>         private readonly string searchTrackingTopicName;
>         private readonly string EventTypePropertyName = SearchTrackingConstants.EventType;
> ```

Suppose we now don't need this private field `private readonly string EventTypePropertyName`

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.SearchTracking.Common/Clients/SearchTrackingServiceBusClient.cs` line 19 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344#-O2yeX1p7NtWSs5NH3W3:-O2yhgRU6n_6o5sDbYFc:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ee08fde5416d32f7a9721995accba870d73fdb92/Atlas.SearchTracking.Common/Clients/SearchTrackingServiceBusClient.cs#L19)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Suppose we now don't need this private field `private readonly string EventTypePropertyName`
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
