### PR TITLE
fix: #875: Update test pipeline to support multiple orgs

### PR DESCRIPTION
**Pull request by seanmobrien**
Adding optional terraform AZURE_LOCATION variable to support Azure region selection
Using dynamic SQL and storage account names to support unique names across deployments
Removing Anthony Nolan VSTS feed id from test-pipeline.xml

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/873)

### CODE REVIEW

**Review by luken-an — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/873)* status: all files reviewed, 1 unresolved discussion (waiting on @seanmobrien)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/873#-NN6jMqW141_TLYRldqe):*
tiniest thing, please could you amend the commit messages with a GitHub issue # and a keyword (e.g., `fix` or `chore`), I've [extended the README](https://github.com/Anthony-Nolan/Atlas/commit/a52070997fd9fbe4825a748e2cafc10c6e870685?short_path=e876e7e#diff-e876e7ee0e973dc39d31da82d81d66e81fbb8f2a2ef31bd31b1f80552ac54d01) with guidance on how commit messages should be structured.

**Comment by seanmobrien** [comment]
> 

Commit messages amended to reference issue 875

**Review by zabeen — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @seanmobrien)

**Pull request merged**
