### PR TITLE
fix: ASRT-26103: Mac code url updates

### PR DESCRIPTION
**Pull request by daria-sorokina-da**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1375)

### CODE REVIEW

**Comment by stuartmcdonnell1980** [comment]
Many thanks Daria. Do I make the change on UAT\Live or do we re-deploy via the pipeline?

**Review by daria-sorokina-da — COMMENTED** [review]
@stuartmcdonnell1980 no need to redeploy or change anything as I made the manual changes already in all environments, and changed the release pipeline variables - see comment in [https://anthonynolan.atlassian.net/browse/ASRT-26103](https://anthonynolan.atlassian.net/browse/ASRT-26103 "https://anthonynolan.atlassian.net/browse/asrt-26103")

> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1375#-:-O9A-3XY-eRhxEYmc75Y:bllyw80)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @stuartmcdonnell1980)

**Comment by stuartmcdonnell1980** [comment]
Excellent, thanks Daria

**Review by stuartmcdonnell1980 — APPROVED** [review]
Thanks for the steer on this Daria.

**Pull request merged**
