### PR TITLE
feature: #805: Load validation dataset, send requests to match predic…

### PR DESCRIPTION
**Pull request by zabeen**
…tion algorithm, and download results.

Important, the new projects in manual testing are not production-quality code; they are intended for a dev to run locally to validate Atlas. Therefore, please don't spend long reviewing. I purposely did not spend any time writing tests either, as it was a best effort to get this up and running asap - but of course do point out any bad or unsecure practices on my part!

Many thanks :)

Btw, I have already submitted 10 million requests to a remote Atlas instance using the code, so it's all working. :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/814)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 65 of 66 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/814)* status: all files reviewed, 5 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.Client.Models/Atlas.Client.Models.csproj` line 5 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5FBiCvyZgTrTCP-R:-NDb5FBjEOIwAEpGHyBH:blbiu87) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Client.Models/Atlas.Client.Models.csproj#L5)):*
> ```XML
>     <PropertyGroup>
>         <TargetFramework>net6.0</TargetFramework>
>         <VersionPrefix>1.6.0</VersionPrefix>
> ```

Current version deployed to production is 1.4, so there is no need to change version to 1.6.0
___
*[`Atlas.Client.Models/CHANGELOG_Client.md` line 15 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5XSs1dZ6NdPf7xTr:-NDb5XSs1dZ6NdPf7xTs:b-kn1ltq) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Client.Models/CHANGELOG_Client.md#L15)):*
> ```Markdown
> 
> ### 1.5.0
> // TODO
> ```

There is no need for version 1.6.0, so you can put your changes into 1.5.0 changelog
___
*[`Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj` line 8 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5jj4712m-RbFHB7S:-NDb5jj4712m-RbFHB7T:b1lbaie) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj#L8)):*
> ```XML
>         <OutputPath>bin/</OutputPath>
>         <LangVersion>latest</LangVersion>
>         <VersionPrefix>1.6.0</VersionPrefix>
> ```

No need for version 1.6.0 as current version in production is 1.4
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 13 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5s9J0jU0ENpgBoKK:-NDb5s9K8KMlBlRqQKSQ:b-e1rfxv) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L13)):*
> ```Markdown
> ## Versions
> 
> ### 1.6.0
> ```

Your changes would be 1.5.0
___
*[`Atlas.MatchPrediction.Test.Validation/local.setting.template.json` line 10 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb644h37n1xktsHKbE:-NDb644h37n1xktsHKbF:brdcbuk) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.MatchPrediction.Test.Validation/local.setting.template.json#L10)):*
> ```JSON
>     "OutgoingMatchPredictionRequests:RequestBatchSize": 1000,
>     "OutgoingMatchPredictionRequests:RequestUrl": "http://localhost:7085/api/BatchMatchPredictionRequests",
>     "MatchPredictionRequests:ResultsSubscription": "override-this",
> ```

We can store subscription name in this file as it is not a secret

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/814)* status: all files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.Client.Models/Atlas.Client.Models.csproj` line 5 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5FBiCvyZgTrTCP-R:-NDbkxHh7b9QdKXmtkHq:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Client.Models/Atlas.Client.Models.csproj#L5)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Current version deployed to production is 1.4, so there is no need to change version to 1.6.0
</blockquote></details>

Done.
___
*[`Atlas.Client.Models/CHANGELOG_Client.md` line 15 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5XSs1dZ6NdPf7xTr:-NDbl34R0plqjvTmc2-T:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Client.Models/CHANGELOG_Client.md#L15)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

There is no need for version 1.6.0, so you can put your changes into 1.5.0 changelog
</blockquote></details>

Done.
___
*[`Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj` line 8 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5jj4712m-RbFHB7S:-NDblltu8nGYyaqVMnJs:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj#L8)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

No need for version 1.6.0 as current version in production is 1.4
</blockquote></details>

Done.
___
*[`Atlas.Functions.PublicApi/CHANGELOG_Atlas.md` line 13 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb5s9J0jU0ENpgBoKK:-NDblmljByv2TmDYrWLE:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.Functions.PublicApi/CHANGELOG_Atlas.md#L13)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Your changes would be 1.5.0
</blockquote></details>

Done.
___
*[`Atlas.MatchPrediction.Test.Validation/local.setting.template.json` line 10 at r2](https://reviewable.io/reviews/anthony-nolan/atlas/814#-NDb644h37n1xktsHKbE:-NDblnh5024_NRam36ft:b-qeyi92) ([raw file](https://github.com/anthony-nolan/atlas/blob/d734f69c541b3d2d56635c54862a75b1a1a42571/Atlas.MatchPrediction.Test.Validation/local.setting.template.json#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

We can store subscription name in this file as it is not a secret
</blockquote></details>

true, but as there is no existing subscription defined in the terraform script, this is something that has to be created manually by the dev that runs this test project, and they then need to set the name they chose here

This is documented in the README for manual testing

**Review by daria-sorokina-da — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/814)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
