### PR TITLE
feature: CBT-1477: Send search tracking events for match prediction

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: all files reviewed, 7 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Functions/local.settings.template.json` line 30 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZJfR8RXjtfoEUorD:-O7nZJfR8RXjtfoEUorE:b2gxxaf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L30)):*
> ```JSON
>     "AtlasFunction:MessagingServiceBus:SearchResultsTopic": "search-results-ready",
>     "AtlasFunction:MessagingServiceBus:SearchResultsDebugSubscription": "debug",
>     "AtlasFunction:SearchTrackingServiceBus:ConnectionString": "override-this",
> ```

Why do we need these settings twice?
___
*[`Atlas.Functions/local.settings.template.json` line 63 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZNdK1d84st8164sg:-O7nZNdK1d84st8164sh:b2gxxaf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L63)):*
> ```JSON
>     "NotificationsServiceBus:NotificationsTopic": "notifications",
> 
>     "SearchTrackingServiceBus:ConnectionString": "override-this",
> ```

Why do we need these settings twice?
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 90 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZdafAh1n2GPJQELD:-O7nZdafAh1n2GPJQELE:by8wgnm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L90)):*
> ```Smalltalk
>             );
> 
>             await matchPredictionSearchTrackingDispatcher.ProcessPrepareBatchesEnded(new Guid(matchingResultsNotification.SearchRequestId));
> ```

I think we need to place this under the "Uploading match prediction requests" bit as the upload also takes time, and we're not counting it now - it's "between" events
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 106 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZwId4QpkQ_iF_MPK:-O7nZwId4QpkQ_iF_MPL:blgxm9g) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L106)):*
> ```Smalltalk
> 
>         [Function(nameof(RunMatchPredictionBatch))]
>         public async Task<IReadOnlyDictionary<int, string>> RunMatchPredictionBatch([ActivityTrigger] string requestLocation, TaskOptions retryOptions)
> ```

Sorry, what do we need the retryOptions for?
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 59 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7ndKin982Ib-A5Wmwc:-O7ndKin982Ib-A5Wmwd:blq2ubg) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L59)):*
> ```Smalltalk
>             var requestCompletedSuccessfully = false;
>             TimedResultSet<IReadOnlyDictionary<int, string>> matchPredictionResultLocations = null;
>             var failureInfo = string.Empty;
> ```

should be null by default
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 226 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7ne1Kx4Rgv7z8MhJHb:-O7ne1Kx4Rgv7z8MhJHc:b65kn3y) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L226)):*
> ```Smalltalk
>                 requestInfo.StageReached = "Orchestrator";
>                 await SendFailureNotification(context, requestInfo);
>                 failureInfo = e.Message;
> ```

Let's do the same we did for the MatchingAlgorithm - collect failure info type, message and exception stacktrace
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 240 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7neRRzCZiAqLt6Utwg:-O7neRRzCZiAqLt6Utwh:b-bznj3v) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L240)):*
> ```Smalltalk
>                         FailureInfoJson = failureInfo,
>                         DonorsPerBatch = matchPredictionProcessingBatchSize,
>                         TotalNumberOfBatches = matchPredictionResultLocations != null ?
> ```

I don't think we should calculate the number of batches here - instead, please return the exact number from RunMatchPredictionAlgorithm and use it here

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: all files reviewed, 7 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.Functions/local.settings.template.json` line 30 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZJfR8RXjtfoEUorD:-O7nf_fTEAWxuN0QBWS2:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L30)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Why do we need these settings twice?
</blockquote></details>

Done.
___
*[`Atlas.Functions/local.settings.template.json` line 63 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZNdK1d84st8164sg:-O7nfe1Q57qc4cGQ9S94:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L63)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Why do we need these settings twice?
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 90 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZdafAh1n2GPJQELD:-O7ngZa_Bi3CVDawqKCn:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L90)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think we need to place this under the "Uploading match prediction requests" bit as the upload also takes time, and we're not counting it now - it's "between" events
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs` line 106 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZwId4QpkQ_iF_MPK:-O7ngg9f4oNzsEvAufho:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs#L106)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Sorry, what do we need the retryOptions for?
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 59 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7ndKin982Ib-A5Wmwc:-O7nh35c4ld3OkciDdkn:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L59)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

should be null by default
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 226 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7ne1Kx4Rgv7z8MhJHb:-O87A7xyE2OO4JqZeUL8:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L226)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's do the same we did for the MatchingAlgorithm - collect failure info type, message and exception stacktrace
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 240 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7neRRzCZiAqLt6Utwg:-O87b_US9uz5KqV-i81m:bbdq07h) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L240)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I don't think we should calculate the number of batches here - instead, please return the exact number from RunMatchPredictionAlgorithm and use it here
</blockquote></details>

Done, not sure if there's a better way though

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: all files reviewed, 5 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Functions/local.settings.template.json` line 30 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZJfR8RXjtfoEUorD:-O8BfmfMBJsNzt1yf8sZ:bt65mdf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L30)):*
<details><summary><i>Previously, pchenery wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still see the settings twice - `AtlasFunction:SearchTrackingServiceBus:ConnectionString` and `SearchTrackingServiceBus:ConnectionString`, i.e.
___
*[`Atlas.Functions/local.settings.template.json` line 63 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZNdK1d84st8164sg:-O8BffnT8NQgI7NPlTIO:bt65mdf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L63)):*
<details><summary><i>Previously, pchenery wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still see the settings twice - `AtlasFunction:SearchTrackingServiceBus:ConnectionString` and `SearchTrackingServiceBus:ConnectionString`, i.e.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 39 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8Beyk91l5QH5aFJff8:-O8Beyk91l5QH5aFJff9:b-bnkqj7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3be051f6f930cfe4dadb26426942e76ac625def8/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L39)):*
> ```Smalltalk
>         private readonly SearchLoggingContext loggingContext;
>         private readonly int matchPredictionProcessingBatchSize;
>         private int matchPredictionNumberOfBatches;
> ```

This should not be a field of the class as this number is specific to the operation 
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 313 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8BeQGW4Q6oRt2fHukH:-O8BeQGX2SQHht-sw0FS:b-ga5sf9) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3be051f6f930cfe4dadb26426942e76ac625def8/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L313)):*
> ```Smalltalk
>                 matchPredictionRequestLocations.ResultSet.Select(r => RunMatchPredictionForDonorBatch(context, r)).ToList();
>             var matchPredictionResultLocations = new List<KeyValuePair<int, string>>();
>             matchPredictionNumberOfBatches = matchPredictionRequestLocations.ResultSet.Count;
> ```

this won't be the number of batches, but instead it will be the total number of results, right?

what you need to do is:
```
var matchPredictionTaskBatches = matchPredictionTasksList.Batch(matchPredictionProcessingBatchSize > 0
                         ? matchPredictionProcessingBatchSize
                         : matchPredictionRequestLocations.ResultSet.Count);
var matchPredictionNumberOfBatches = matchPredictionTaskBatches.Count;
foreach (var matchPredictionTaskBatch in matchPredictionTaskBatches) ...
```
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 313 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8Bf5px094PF-KK2v77:-O8Bf5px094PF-KK2v78:bhrpj2h) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3be051f6f930cfe4dadb26426942e76ac625def8/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L313)):*
> ```Smalltalk
>                 matchPredictionRequestLocations.ResultSet.Select(r => RunMatchPredictionForDonorBatch(context, r)).ToList();
>             var matchPredictionResultLocations = new List<KeyValuePair<int, string>>();
>             matchPredictionNumberOfBatches = matchPredictionRequestLocations.ResultSet.Count;
> ```

Instead of defining matchPredictionNumberOfBatches globally, you ned to return this value from RunMatchPredictionAlgorithm.

You can use syntax like this:
```
private async Task<(TimedResultSet<IReadOnlyDictionary<int, string>> TimedResultSets, int MatchPredictionNumberOfBatches)> RunMatchPredictionAlgorithm(
            TaskOrchestrationContext context,
            FailureNotificationRequestInfo requestInfo,
            TimedResultSet<IList<string>> matchPredictionRequestLocations
        )
```

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: all files reviewed, 5 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.Functions/local.settings.template.json` line 30 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZJfR8RXjtfoEUorD:-O8BgMYf-AKR0E7k3VWz:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L30)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Still see the settings twice - `AtlasFunction:SearchTrackingServiceBus:ConnectionString` and `SearchTrackingServiceBus:ConnectionString`, i.e.
</blockquote></details>

Done.
___
*[`Atlas.Functions/local.settings.template.json` line 63 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O7nZNdK1d84st8164sg:-O8BgRoDCSM3E1moMpff:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/cd56c058209413faf1953b3e623723a3c8a19446/Atlas.Functions/local.settings.template.json#L63)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Still see the settings twice - `AtlasFunction:SearchTrackingServiceBus:ConnectionString` and `SearchTrackingServiceBus:ConnectionString`, i.e.
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 39 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8Beyk91l5QH5aFJff8:-O8Bge-vERz3nOSX_AuT:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3be051f6f930cfe4dadb26426942e76ac625def8/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L39)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This should not be a field of the class as this number is specific to the operation
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 313 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8BeQGW4Q6oRt2fHukH:-O8Bi3zf6RYBArHpksNt:b-cl2j9a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3be051f6f930cfe4dadb26426942e76ac625def8/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L313)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

this won't be the number of batches, but instead it will be the total number of results, right?

what you need to do is:
```
var matchPredictionTaskBatches = matchPredictionTasksList.Batch(matchPredictionProcessingBatchSize > 0
                         ? matchPredictionProcessingBatchSize
                         : matchPredictionRequestLocations.ResultSet.Count);
var matchPredictionNumberOfBatches = matchPredictionTaskBatches.Count;
foreach (var matchPredictionTaskBatch in matchPredictionTaskBatches) ...
```
</blockquote></details>

Wasn't convinced about this but when I tested, the number of results was 1000 and number of batches was 1, have changed to this though.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 313 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8Bf5px094PF-KK2v77:-O8CPa3M9iXH1NRnZLHh:b-1bly4u) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3be051f6f930cfe4dadb26426942e76ac625def8/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L313)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Instead of defining matchPredictionNumberOfBatches globally, you ned to return this value from RunMatchPredictionAlgorithm.

You can use syntax like this:
```
private async Task<(TimedResultSet<IReadOnlyDictionary<int, string>> TimedResultSets, int MatchPredictionNumberOfBatches)> RunMatchPredictionAlgorithm(
            TaskOrchestrationContext context,
            FailureNotificationRequestInfo requestInfo,
            TimedResultSet<IList<string>> matchPredictionRequestLocations
        )
```
</blockquote></details>

Thanks, very neat

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: all files reviewed, 4 unresolved discussions (waiting on @pchenery)

___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 59 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D6l8MEoPlHZhqWR_2:-O8D6l8N1LPtwizFRTja:b-436m1a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L59)):*
> ```Smalltalk
>             var orchestrationStartTime = context.CurrentUtcDateTime;
>             var requestCompletedSuccessfully = false;
>             var matchPredictionResultLocations = (timedResultSet: default(TimedResultSet<IReadOnlyDictionary<int, string>>), matchPredictionNumberOfBatches: 0);
> ```

Let's have two separate variables:
```
TimedResultSet<IReadOnlyDictionary<int, string>> matchPredictionResultLocations = null;
int? matchPredictionNumberOfBatches = null;
```
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 93 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D7-yb76Bi_ErTk1Tr:-O8D7-yb76Bi_ErTk1Ts:buwmnnb) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L93)):*
> ```Smalltalk
>                         SearchInitiated = orchestrationStartTime,
>                         MatchingResultsNotification = notification,
>                         MatchPredictionResultLocations = matchPredictionResultLocations.Item1
> ```

Please make the parts of the tuple names, so that instead of Item1, Item2 we could use names
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 179 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D76xK5qaVMgzoIqqt:-O8D76xK5qaVMgzoIqqu:b-436m1a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L179)):*
> ```Smalltalk
>             var requestCompletedSuccessfully = false;
>             var orchestrationStartTime = context.CurrentUtcDateTime;
>             var matchPredictionResultLocations = (timedResultSet: default(TimedResultSet<IReadOnlyDictionary<int, string>>), matchPredictionNumberOfBatches: 0);
> ```

Let's have two separate variables:
```
TimedResultSet<IReadOnlyDictionary<int, string>> matchPredictionResultLocations = null;
int? matchPredictionNumberOfBatches = null;
```
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 346 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D7HoeAxtgqOv7Ibp6:-O8D7HoeAxtgqOv7Ibp7:bb9z4zx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L346)):*
> ```Smalltalk
>             });
> 
>             return new ValueTuple<TimedResultSet<IReadOnlyDictionary<int, string>>, int>
> ```

can we just do 
```
var timedResultSet  = new TimedResultSet<IReadOnlyDictionary<int, string>>
                {
                    ResultSet = MoreLinq.Extensions.ToDictionaryExtension.ToDictionary(matchPredictionResultLocations),
                    ElapsedTime = totalElapsedTime ?? TimeSpan.MaxValue
                };
return (timedResultSet, matchPredictionNumberOfBatches);
```

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: all files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da)

___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 59 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D6l8MEoPlHZhqWR_2:-O8GT_jv6C3by8fKoOx6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L59)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's have two separate variables:
```
TimedResultSet<IReadOnlyDictionary<int, string>> matchPredictionResultLocations = null;
int? matchPredictionNumberOfBatches = null;
```
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 93 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D7-yb76Bi_ErTk1Tr:-O8H-Pty2kM_J3Bi6PhE:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L93)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Please make the parts of the tuple names, so that instead of Item1, Item2 we could use names
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 179 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D76xK5qaVMgzoIqqt:-O8GTtLX2a9nJWfyZZvR:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L179)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's have two separate variables:
```
TimedResultSet<IReadOnlyDictionary<int, string>> matchPredictionResultLocations = null;
int? matchPredictionNumberOfBatches = null;
```
</blockquote></details>

Done.
___
*[`Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs` line 346 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370#-O8D7HoeAxtgqOv7Ibp6:-O8GUe1N45eO0ILOpFyv:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3a37ce695326bf78d07e7143156bb3c2c3a411a3/Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs#L346)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

can we just do 
```
var timedResultSet  = new TimedResultSet<IReadOnlyDictionary<int, string>>
                {
                    ResultSet = MoreLinq.Extensions.ToDictionaryExtension.ToDictionary(matchPredictionResultLocations),
                    ElapsedTime = totalElapsedTime ?? TimeSpan.MaxValue
                };
return (timedResultSet, matchPredictionNumberOfBatches);
```
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)

**Pull request merged**
