### PR TITLE
feature: CBT-1476: Send Matching Algorithm core matching started event

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 95 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358#-O4GkYRXCqhBP3v1LhJz:-O4GkYRXCqhBP3v1LhK-:b-9nsng7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30ca816e9a3bf5d5746e964cc5ce48b95befe181/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L95)):*
> ```Smalltalk
>                 matchingAlgorithmSearchTrackingContextManager.Set(context);
>                 await matchingAlgorithmSearchTrackingDispatcher.DispatchInitiationEvent(enqueuedTimeUtc.LocalDateTime, searchStartTime.UtcDateTime);
>                 await matchingAlgorithmSearchTrackingDispatcher.DispatchMatchingAlgorithmAttemptTimingEvent(
> ```

Did it start here though? I think we need to add this code into MatchingService.GetMatches - because this is where we actually do the matching.

But we need to be clever there because there can be multiple sub-searches.
I think we're good to just send an event for each sub-search because:
1) all sub-searches will start at the same time, so even if the date gets updated by the next call, we're good, they'll be close to each other
2) sub-searches will be finishing at different times, but here we're also good as we want to know the LATEST date, so the value will be overridden by the latest date, and that's OK

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 94 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358#-O4GnYjcCd9regme2BGY:-O4GnYjcCd9regme2BGZ:b-gfmzje) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30ca816e9a3bf5d5746e964cc5ce48b95befe181/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L94)):*
> ```Smalltalk
> 
>                 matchingAlgorithmSearchTrackingContextManager.Set(context);
>                 await matchingAlgorithmSearchTrackingDispatcher.DispatchInitiationEvent(enqueuedTimeUtc.LocalDateTime, searchStartTime.UtcDateTime);
> ```

Don't think changing local to UTC is correct though as both dates should be in UTC. Why do we need this change?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 94 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358#-O4GnYjcCd9regme2BGY:-O4GoS8x1hG0dXZOImCi:bu5dbf4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30ca816e9a3bf5d5746e964cc5ce48b95befe181/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L94)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Don't think changing local to UTC is correct though as both dates should be in UTC. Why do we need this change?
</blockquote></details>

Sorry, my message is incorrect, correction below:
* Don't think changing UTC to local is correct though as both dates should be in UTC. Why do we need this change?

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 94 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358#-O4GnYjcCd9regme2BGY:-O4K72de7Tp47RGx0KsU:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30ca816e9a3bf5d5746e964cc5ce48b95befe181/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L94)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

I think the problem is that in 
```
[SuppressMessage(null, SuppressMessage.UnusedParameter, Justification = SuppressMessage.UsedByAzureTrigger)]
[Function(nameof(RunSearch))]
public async Task RunSearch(
    [ServiceBusTrigger(
        "%MessagingServiceBus:SearchRequestsTopic%",
        "%MessagingServiceBus:SearchRequestsSubscription%",
        Connection = "MessagingServiceBus:ConnectionString")]
    IdentifiedSearchRequest request,
    int deliveryCount,
    DateTime enqueuedTimeUtc)
{
    await searchRunner.RunSearch(request, deliveryCount, enqueuedTimeUtc);
}
```
an implicit conversion happens between enqueuedTimeUtc (which is a DateTime) and DateTimeOffset and smth is wrong there.

Probably we need to specify the date time kind for this date as UTC for the conversion to happen correctly.

```
enqueuedTimeUtc= DateTime.SpecifyKind(enqueuedTimeUtc, DateTimeKind.Utc);
```
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 95 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358#-O4GkYRXCqhBP3v1LhJz:-O4Kdnrb1Wq1j7cJFZm_:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30ca816e9a3bf5d5746e964cc5ce48b95befe181/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L95)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Did it start here though? I think we need to add this code into MatchingService.GetMatches - because this is where we actually do the matching.

But we need to be clever there because there can be multiple sub-searches.
I think we're good to just send an event for each sub-search because:
1) all sub-searches will start at the same time, so even if the date gets updated by the next call, we're good, they'll be close to each other
2) sub-searches will be finishing at different times, but here we're also good as we want to know the LATEST date, so the value will be overridden by the latest date, and that's OK
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
