### PR TITLE
docs: Update changelog for v1.6.0

### PR DESCRIPTION
**Pull request by zabeen**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130)

### CODE REVIEW

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da and @tjogrady1982)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130#-NjnZq4o3BDkiMocmZcL:-NjnZq4o3BDkiMocmZcM:b-qeqnvk) (no related file):*
@tjogrady1982 @daria-sorokina-da raised PR to ask for a check on the feature flag ADR

___

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130)* status: all files reviewed, 1 unresolved discussion (waiting on @tjogrady1982)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130)* status: all files reviewed, 1 unresolved discussion (waiting on @tjogrady1982)

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130)* status: all files reviewed, 1 unresolved discussion (waiting on @tjogrady1982)

**Pull request merged**
