### PR TITLE
feature: #994: Capture outcomes from WMDA Parallel Run

### PR DESCRIPTION
**Pull request by IgorKupreychik**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998)* status: all files reviewed, 14 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.ManualTesting/Functions/WmdaParallelRunOutcomesFunctions.cs` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtOPZlEoyYWtOcVE2y:-NXtOPZlEoyYWtOcVE2z:b-51mnr6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Functions/WmdaParallelRunOutcomesFunctions.cs#L10)):*
> ```Smalltalk
> namespace Atlas.ManualTesting.Functions
> {
>     public class WmdaParallelRunOutcomesFunctions
> ```

Please make name more generic, as we can use this function for any purpose not just wmda parallel run

e.g., `SearchOutcomesFunctions`



_Code quote:_
```Smalltalk
WmdaParallelRunOutcomesFunctions
```
___
*[`Atlas.ManualTesting/Functions/WmdaParallelRunOutcomesFunctions.cs` line 12 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtObwu7UFHZcVMx4xF:-NXtObwu7UFHZcVMx4xG:bhwnc45) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Functions/WmdaParallelRunOutcomesFunctions.cs#L12)):*
> ```Smalltalk
>     public class WmdaParallelRunOutcomesFunctions
>     {
>         private readonly IWmdaParallelRunResultsHandler wmdaParallelRunResultsHandler;
> ```

suggest: ISearchOutcomesProcessor

`Handler` is a keyword that's usually associated with event handler methods



_Code quote:_
```Smalltalk
IWmdaParallelRunResultsHandler
```
___
*[`Atlas.ManualTesting/Functions/WmdaParallelRunOutcomesFunctions.cs` line 19 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtOkPQ8kl5tobRA0La:-NXtOkPQ8kl5tobRA0Lb:by6y5i2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Functions/WmdaParallelRunOutcomesFunctions.cs#L19)):*
> ```Smalltalk
>         }
> 
>         [FunctionName(nameof(GetWmdaParallelRunOutcomes))]
> ```

suggest: GetSearchOutcomes



_Code quote:_
```Smalltalk
GetWmdaParallelRunOutcomes
```
___
*[`Atlas.ManualTesting/Models/PeekRequest.cs` line 21 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtOtox0Vq1g5798-JH:-NXtOtox0Vq1g5798-JI:b-qjny0j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Models/PeekRequest.cs#L21)):*
> ```Smalltalk
>     }
> 
>     public class WmdaParallelSearchInfoPeekRequest : PeekRequest
> ```

rename to: SearchOutcomesPeekRequest



_Code quote:_
```Smalltalk
WmdaParallelSearchInfoPeekRequest
```
___
*[`Atlas.ManualTesting/Models/WmdaParallelRunFailedSearch.cs` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtOzSKD-m_9J4zPy1I:-NXtOzSKD-m_9J4zPy1J:bdxhq6b) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Models/WmdaParallelRunFailedSearch.cs#L3)):*
> ```Smalltalk
> namespace Atlas.ManualTesting.Models
> {
>     public class WmdaParallelRunFailedSearch
> ```

rename to: FailedSearch



_Code quote:_
```Smalltalk
WmdaParallelRunFailedSearch
```
___
*[`Atlas.ManualTesting/Models/WmdaParallelRunResult.cs` line 5 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtP2o15zzLzC51EZ6d:-NXtP2o29KXFoBCIIJdZ:b-p83gqw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Models/WmdaParallelRunResult.cs#L5)):*
> ```Smalltalk
> namespace Atlas.ManualTesting.Models
> {
>     public class WmdaParallelRunPerformanceInfo
> ```

rename to: SearchPerformanceInfo



_Code quote:_
```Smalltalk
WmdaParallelRunPerformanceInfo
```
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 17 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtPc2r-se90IFnigxb:-NXtPc2r-se90IFnigxc:bqeiud7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L17)):*
> ```Smalltalk
>     public interface IWmdaParallelRunResultsHandler
>     {
>         Task<(string PerformanceInfoFileName, string FailedSearchesFileName)> Handle(WmdaParallelSearchInfoPeekRequest request);
> ```

Rename to ProcessSearchMessages



_Code quote:_
```Smalltalk
Handle
```
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 66 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtQnga56kc0wOBSbNC:-NXtQnga56kc0wOBSbND:bnrnfmk) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L66)):*
> ```Smalltalk
>                     resultItem.MatchingQueueDuration = matchingAlgorithmResultsLog.RequestPerformanceMetrics.StartTime - matchingAlgorithmResultsLog.RequestPerformanceMetrics.InitiationTime;
>                     resultItem.MatchingRequestDuration = matchingAlgorithmResultsLog.RequestPerformanceMetrics.Duration;
>                     resultItem.MatchingInitiationTime = matchingAlgorithmResultsLog.RequestPerformanceMetrics.InitiationTime;
> ```

suggest moving to a new method, "SetMatchingPerformanceInfo", take in resultItem and pass back same object with updated props



_Code quote:_
```Smalltalk
                    var matchingAlgorithmResultsLog = await blobDownloader.Download<SearchLog>(azureStorageSettings.MatchingAlgorithmResultsBlobContainer, logFilename);

                    resultItem.MatchingQueueDuration = matchingAlgorithmResultsLog.RequestPerformanceMetrics.StartTime - matchingAlgorithmResultsLog.RequestPerformanceMetrics.InitiationTime;
                    resultItem.MatchingRequestDuration = matchingAlgorithmResultsLog.RequestPerformanceMetrics.Duration;
                    resultItem.MatchingInitiationTime = matchingAlgorithmResultsLog.RequestPerformanceMetrics.InitiationTime;
```
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtQJ3kEtoFp-7B96oU:-NXtQJ3kEtoFp-7B96oV:b-k6eu8g) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L68)):*
> ```Smalltalk
>                     resultItem.MatchingInitiationTime = matchingAlgorithmResultsLog.RequestPerformanceMetrics.InitiationTime;
>                 }
>                 catch { }
> ```

we should throw the error, then at least the user running func locally knows something went wrong
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 76 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtRF4E2nolzdpavGVi:-NXtRF4E2nolzdpavGVj:bq2hr5k) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L76)):*
> ```Smalltalk
>                     resultItem.MatchPredictionQueueDuration = searchResultsLog.RequestPerformanceMetrics.StartTime - searchResultsLog.RequestPerformanceMetrics.InitiationTime;
>                     resultItem.MatchPredictionRequestDuration = searchResultsLog.RequestPerformanceMetrics.Duration;
>                     resultItem.MatchPredictionCompletionTime = searchResultsLog.RequestPerformanceMetrics.CompletionTime;
> ```

as above, suggest moving to a new method, "SetMatchPredictionPerformanceInfo", take in resultItem and pass back same object with updated props



_Code quote:_
```Smalltalk
                    var searchResultsLog = await blobDownloader.Download<SearchLog>(azureStorageSettings.SearchResultsBlobContainer, logFilename);

                    resultItem.MatchPredictionQueueDuration = searchResultsLog.RequestPerformanceMetrics.StartTime - searchResultsLog.RequestPerformanceMetrics.InitiationTime;
                    resultItem.MatchPredictionRequestDuration = searchResultsLog.RequestPerformanceMetrics.Duration;
                    resultItem.MatchPredictionCompletionTime = searchResultsLog.RequestPerformanceMetrics.CompletionTime;
```
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 78 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtQWeN5G4vAi9tW5yx:-NXtQWeN5G4vAi9tW5yy:b-6pcbto) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L78)):*
> ```Smalltalk
>                     resultItem.MatchPredictionCompletionTime = searchResultsLog.RequestPerformanceMetrics.CompletionTime;
>                 }
>                 catch { }
> ```

same as above: throw error
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 91 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtRSI7BbkTsm3A5X6o:-NXtRSI7BbkTsm3A5X6p:b25r6tc) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L91)):*
> ```Smalltalk
>             (string performanceInfoFileName, string failedSearchesFileName) = (null, null);
> 
>             var targetDirectory = request.Directory ?? Directory.GetCurrentDirectory();
> ```

q: would this mean it writes to the Atlas build dir?



_Code quote:_
```Smalltalk
Directory.GetCurrentDirectory();
```
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 103 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtS2wf-BxA00uPaLMy:-NXtS2wf-BxA00uPaLMz:bbdpe74) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L103)):*
> ```Smalltalk
>                 performanceInfoResults.ForEach(r => performanceInfoCsv.AppendLine(
>                     $"{r.SearchRequestId},{r.WasSuccessful},{r.MatchingQueueDuration},{r.MatchingRequestDuration},{r.MatchPredictionQueueDuration},{r.MatchPredictionRequestDuration},{r.MatchingInitiationTime},{r.MatchPredictionCompletionTime},{r.DonorCount}"));
>                 await File.WriteAllTextAsync(performanceInfoFileName, performanceInfoCsv.ToString());
> ```

suggest moving to new method, WritePerformanceInfo, returns filename



_Code quote:_
```Smalltalk
                if (!Directory.Exists(targetDirectory))
                    Directory.CreateDirectory(targetDirectory);

                performanceInfoFileName = Path.Combine(targetDirectory, $"search-info_{request.FromSequenceNumber}-{request.MessageCount}_performance-info.csv");
                var performanceInfoCsv = new StringBuilder(
                    "request ID,was successful,matching queue duration,matching request duration,match prediction queue duration,match predition request duration,matching initiation time,match prediction completion time,donor count\n");
                performanceInfoResults.ForEach(r => performanceInfoCsv.AppendLine(
                    $"{r.SearchRequestId},{r.WasSuccessful},{r.MatchingQueueDuration},{r.MatchingRequestDuration},{r.MatchPredictionQueueDuration},{r.MatchPredictionRequestDuration},{r.MatchingInitiationTime},{r.MatchPredictionCompletionTime},{r.DonorCount}"));
                await File.WriteAllTextAsync(performanceInfoFileName, performanceInfoCsv.ToString());
```
___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 111 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtS8ss4SxCPuIFzQHP:-NXtS8ss4SxCPuIFzQHQ:b-8l3myu) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L111)):*
> ```Smalltalk
>                 var failedSearchesCsv = new StringBuilder("request ID,failure info\n");
>                 failedSearchResults.ForEach(r => failedSearchesCsv.AppendLine($"{r.SearchRequestId},{r.FailureInfo}"));
>                 await File.WriteAllTextAsync(failedSearchesFileName, failedSearchesCsv.ToString());
> ```

suggest moving to new method, WriteFailureInfo, returns filename



_Code quote:_
```Smalltalk
                failedSearchesFileName = Path.Combine(targetDirectory, $"search-info_{request.FromSequenceNumber}-{request.MessageCount}_failed-searches.csv");
                var failedSearchesCsv = new StringBuilder("request ID,failure info\n");
                failedSearchResults.ForEach(r => failedSearchesCsv.AppendLine($"{r.SearchRequestId},{r.FailureInfo}"));
                await File.WriteAllTextAsync(failedSearchesFileName, failedSearchesCsv.ToString());
```

**Comment by IgorKupreychik** [comment]
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtQJ3kEtoFp-7B96oU:-NXtYHbtDsEIG7qJjmGv:bc3k5vc) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L68)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

we should throw the error, then at least the user running func locally knows something went wrong
</blockquote></details>

This try-catch block is mostly to cover cases when some of the log files don't exist (for example, for failed searches), if we throw exception here - we will stop processing and won't build any csv (i.e. won't return any results). Considering this is a test tool, I'd rather prefer to have some results (even though some of them would may be missing some fields). This is just my opinion, please confirm if you believe we need to throw exception here either way and I'll make the change.

**Comment by IgorKupreychik** [comment]
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 91 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtRSI7BbkTsm3A5X6o:-NXtZpuX5HCjGsuwM6rL:bl10vbb) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L91)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

q: would this mean it writes to the Atlas build dir?
</blockquote></details>

yes, currently it's 'Atlas.ManualTesting\bin'

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998)* status: all files reviewed, 14 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs` line 68 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998#-NXtQJ3kEtoFp-7B96oU:-NXt_OMO3o2Ctnk7XLvl:b-a9oamo) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3bf0e7e8ea6010e2745328240e949fdc2ce2b9b6/Atlas.ManualTesting/Services/WmdaParallelRunResultsHandler.cs#L68)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

This try-catch block is mostly to cover cases when some of the log files don't exist (for example, for failed searches), if we throw exception here - we will stop processing and won't build any csv (i.e. won't return any results). Considering this is a test tool, I'd rather prefer to have some results (even though some of them would may be missing some fields). This is just my opinion, please confirm if you believe we need to throw exception here either way and I'll make the change.
</blockquote></details>

make sense

but search log should always be written even in a failed search - so if the downloader cannot find the log file, that is serious enough to inform the user about.

in catch block, I would capture name of the log file, and the exception message, and then after all notifications have been processed, write the collection to a third text file: $"search-info_{request.FromSequenceNumber}-{request.MessageCount}_log-file-errors.csv"

**Review by zabeen — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/998)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)

**Pull request merged**
