### PR TITLE
fix: #962: Don't try to save original search results, if they are alr…

### PR DESCRIPTION
**Pull request by SergeyEzh**
…eady present in db

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 124 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-Nsm9XhN5VmPKdv1j9g-:-Nsm9XhN5VmPKdv1j9g0:b-kpoam4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L124)):*
> ```Smalltalk
>     SELECT null 
> END CATCH
> ";
> ```

I am not sure this is best practice. I think it would be better to first run a select statement to see if a set exists for that search id; if yes, then return early (and log trace message that set already exists), and if not, then run the insert statement. 

Issue with this general try/catch approach is any exception will lead to returning early, not just duplicate exception



_Code quote:_
```Smalltalk
BEGIN TRY
    INSERT INTO {CanonicalResultSet.QualifiedTableName}
    ({nameof(CanonicalResultSet.OriginalSearchRequestId)})
    VALUES(@{nameof(searchRequestId)});

    SELECT CAST(SCOPE_IDENTITY() as int);
END TRY
BEGIN CATCH
    SELECT null
END CATCH
";
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 124 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-Nsm9XhN5VmPKdv1j9g-:-NsmCXIJ7pMHsC_mngE3:bjdxjpa) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L124)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I am not sure this is best practice. I think it would be better to first run a select statement to see if a set exists for that search id; if yes, then return early (and log trace message that set already exists), and if not, then run the insert statement. 

Issue with this general try/catch approach is any exception will lead to returning early, not just duplicate exception
</blockquote></details>

I would propose something like that then. If we just check early if record exists, it may be added by other transaction after this check. And then we'll get the exception again. To prevent this we will have to set transaction isolation level to serializable which will lead to excessive locking in Sql Server. Which may degrade performance or cause deadlocks.

```
BEGIN TRY
    INSERT INTO {CanonicalResultSet.QualifiedTableName}
    ({nameof(CanonicalResultSet.OriginalSearchRequestId)})
    VALUES(@{nameof(searchRequestId)});

    SELECT CAST(SCOPE_IDENTITY() as int);
END TRY
BEGIN CATCH
    if exists (select id from RepeatSearch.CanonicalResultSets where OriginalSearchRequestId = @searchRequestId)
        select null
    else
    throw
END CATCH


```

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 124 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-Nsm9XhN5VmPKdv1j9g-:-NsmJDUo0fg_OLRqch77:b-ig0ff5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L124)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

I would propose something like that then. If we just check early if record exists, it may be added by other transaction after this check. And then we'll get the exception again. To prevent this we will have to set transaction isolation level to serializable which will lead to excessive locking in Sql Server. Which may degrade performance or cause deadlocks.

```
BEGIN TRY
    INSERT INTO {CanonicalResultSet.QualifiedTableName}
    ({nameof(CanonicalResultSet.OriginalSearchRequestId)})
    VALUES(@{nameof(searchRequestId)});

    SELECT CAST(SCOPE_IDENTITY() as int);
END TRY
BEGIN CATCH
    if exists (select id from RepeatSearch.CanonicalResultSets where OriginalSearchRequestId = @searchRequestId)
        select null
    else
    throw
END CATCH


```
</blockquote></details>

On call, we decided this is best approach.

@SergeyEzh to add explanatory comments

**Review by zabeen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)* status: all files reviewed, 3 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 45 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-Nsmkcch0U2RTANoOyG0:-NsmkcciCH2Ydv5-MDNC:b-kv90oh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L45)):*
> ```Smalltalk
>             {
>                 var resultSetId = await TryCreateResultSetEntity(searchRequestId);
>                 if (resultSetId is null)
> ```

Add comment line that `null` means the result set already exists



_Code quote:_
```Smalltalk
if (resultSetId is null)
```
___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 111 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-NsmkHmm8UaMlTClbKSV:-NsmkHmm8UaMlTClbKSW:btnnlc) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L111)):*
> ```Smalltalk
>         }
> 
>         private async Task<int?> TryCreateResultSetEntity(string searchRequestId)
> ```

Suggest rename to `CreateResultSetIfNotExists` and then add comment to `<return />` docs that `null` will be returned if the result set entity already exists



_Code quote:_
```Smalltalk
 TryCreateResultSetEntity
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 45 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-Nsmkcch0U2RTANoOyG0:-NssT5d49n30ED-ROse_:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L45)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Add comment line that `null` means the result set already exists
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 111 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-NsmkHmm8UaMlTClbKSV:-NssT6G77mzUbtYy4w_r:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L111)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Suggest rename to `CreateResultSetIfNotExists` and then add comment to `<return />` docs that `null` will be returned if the result set entity already exists
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs` line 124 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258#-Nsm9XhN5VmPKdv1j9g-:-NssT6yv9RmqgE93h2ir:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/30d29165bc61c1db1adbce0924ae2a093fe76b8a/Atlas.RepeatSearch.Data/Repositories/CanonicalResultSetRepository.cs#L124)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

On call, we decided this is best approach.

@SergeyEzh to add explanatory comments
</blockquote></details>

Done.

**Review by zabeen — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
