### PR TITLE
feat: #1142: Add file name to alert "Donor Ids file was present but i…

### PR DESCRIPTION
**Pull request by SergeyEzh**
…t was empty"

- - -
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152)

### CODE REVIEW

**Review by zabeen — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152)* status: all files reviewed, 4 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs` line 80 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXFOg7_fLsDIIESrn:-NlZXFOg7_fLsDIIESro:b-84ktza) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs#L80)):*
> ```Smalltalk
>             catch (EmptyDonorFileException)
>             {
>                 await LogFileErrorAndSendAlert("Donors file was present but it was empty.", $"Donors file: {file.FileLocation}");
> ```

Donor info checker file



_Code quote:_
```Smalltalk
Donors file
```
___
*[`Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs` line 80 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXIOw8qqRV6tbNtHb:-NlZXIOw8qqRV6tbNtHc:b-84ktza) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs#L80)):*
> ```Smalltalk
>             catch (EmptyDonorFileException)
>             {
>                 await LogFileErrorAndSendAlert("Donors file was present but it was empty.", $"Donors file: {file.FileLocation}");
> ```

Donor info checker file



_Code quote:_
```Smalltalk
Donors file
```
___
*[`Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs` line 170 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXV2ME2Vwgo0EPeQV:-NlZXV2N16LfvViWVXGq:b-84ktza) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs#L170)):*
> ```Smalltalk
>             await donorInfoChecker.CompareDonorInfoInFileToAtlasDonorStore(file);
> 
>             await notificationSender.Received().SendAlert("Donors file was present but it was empty.", $"Donors file: name-of-the-file.ext", Priority.Medium, Arg.Any<string>());
> ```

Donor info checker file



_Code quote:_
```Smalltalk
Donors file
```
___
*[`Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs` line 170 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXXsJC46tGHBWiSQN:-NlZXXsJC46tGHBWiSQO:bqokh42) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs#L170)):*
> ```Smalltalk
>             await donorInfoChecker.CompareDonorInfoInFileToAtlasDonorStore(file);
> 
>             await notificationSender.Received().SendAlert("Donors file was present but it was empty.", $"Donors file: name-of-the-file.ext", Priority.Medium, Arg.Any<string>());
> ```

Donor info checker



_Code quote:_
```Smalltalk
Donors file
```

**Review by SergeyEzh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs` line 80 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXFOg7_fLsDIIESrn:-NlcJr7d4BYkulb_RiuE:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs#L80)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Donor info checker file
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs` line 80 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXIOw8qqRV6tbNtHb:-NlcJrhB5LMfHE9zOlyG:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport/Services/DonorChecker/DonorInfoChecker.cs#L80)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Donor info checker file
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs` line 170 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXV2ME2Vwgo0EPeQV:-NlcJsHvDUaPPRrPjqbk:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs#L170)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Donor info checker file
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs` line 170 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152#-NlZXXsJC46tGHBWiSQN:-NlcJsZs27n604as1aO6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/0a69b99d30d32d78e6b5363e410cc531b06373a5/Atlas.DonorImport.Test/Services/DonorChecker/DonorInfoCheckerTests.cs#L170)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Donor info checker
</blockquote></details>

Done.

**Review by zabeen — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152)* status: all files reviewed, 1 unresolved discussion (waiting on @SergeyEzh)

**Review by zabeen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1152)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
