### PR TITLE
docs: #713: Add configuration readme, detailing which parts of Atlas …

### PR DESCRIPTION
**Pull request by benbelow**
…can be configured along with their effects

---
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/720)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/720)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @IgorZhuravlevDataArt)

___
*[README_Configuration.md, line 83 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/720#-N-33c0g4diHi0igDBk8:-N-33c0h5u0hshpRdzjd:b-1lujm3) ([raw file](https://github.com/anthony-nolan/atlas/blob/acbd6d834aa3032c14c1340f1937befbb5205c74/README_Configuration.md#L83)):*
> ```Markdown
> | Terraform Setting          | Functions App Name                 | Functions App Setting Name | Description                |
> | -------------------------- | ------------------                 | -------------------------- | -----------                | 
> | MAX_CONCURRENT-ACTIVITY-FUNCTIONS | ATLAS-FUNCTIONS | AzureFunctionsJobHost--extensions--durableTask--maxConcurrentActivityFunctions | *Per instance*, dictates the number of parallel match prediction batches that can be run. It is recommended that this stay very small (ideally 1), as match prediction is a very memory intensive process - and allowing more concurrent processes significantly increases the risk of hitting out of memory exceptions, causing match prediction to slow down significantly (or worse, never finish) |
> ```

Shouldn't we have - after MAX instead of _?

**Review by benbelow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/720)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @daria-sorokina-da and @IgorZhuravlevDataArt)

___
*[README_Configuration.md, line 69 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/720#-N-341Pe-WzosLtJpZ0H:-N-3xQgWA0myywxBiKET:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/acbd6d834aa3032c14c1340f1937befbb5205c74/README_Configuration.md#L69)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

shouldn't we have - after BATCH, instead of _? 
</blockquote></details>

Done.
___
*[README_Configuration.md, line 83 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/720#-N-33c0g4diHi0igDBk8:-N-3xR5K14IEMQ-0QBoC:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/acbd6d834aa3032c14c1340f1937befbb5205c74/README_Configuration.md#L83)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Shouldn't we have - after MAX instead of _?
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorZhuravlevDataArt)

**Review by benbelow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/720)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorZhuravlevDataArt)

*[a discussion](https://reviewable.io/reviews/anthony-nolan/atlas/720#-N-7R-nn-iXLKS-sF82d:-N-7R-nn-iXLKS-sF82e:bmkaehc) (no related file):*
Blocking comment on @mmelchers review of this document

---

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/720)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorZhuravlevDataArt)

**Comment by benbelow** [comment]
@mmelchers FYI we're going to merge this documentation change now to reduce the risk of it being left indefinitely. 

If you get a chance to review this and would like any further changes, please comment on the PR or the issue #713 and we can make any changes post-merge

**Pull request merged**
