### PR TITLE
chore: Peek searchable donor update topic by Atlas donor ID.

### PR DESCRIPTION
**Pull request by zabeen**
Change to non-production, manual testing/debug project on Atlas, allows dev to filter audit sub of topic by atlas donor ID

- - -
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/815)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/815)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.Functions.PublicApi.Test.Manual/Services/SearchableDonorUpdatesPeeker.cs` line 16 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/815#-NE5VfEd0tGeyiDypDTT:-NE5VfEd0tGeyiDypDTU:b-ftg8nm) ([raw file](https://github.com/anthony-nolan/atlas/blob/3e1822fd8e78d825e5be581fa880ec6de79a9124/Atlas.Functions.PublicApi.Test.Manual/Services/SearchableDonorUpdatesPeeker.cs#L16)):*
> ```Smalltalk
>     }
> 
>     internal class SearchableDonorUpdatesPeeker : ISearchableDonorUpdatesPeeker
> ```

Atlas should not work with NOVA topics directly - there is Atlas Adapter project for that https://github.com/Anthony-Nolan/Nova.AtlasAdapter.
It takes messages from updated-searchable-dnors topic and sends it to Atlas

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/815)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`Atlas.Functions.PublicApi.Test.Manual/Services/SearchableDonorUpdatesPeeker.cs` line 16 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/815#-NE5VfEd0tGeyiDypDTT:-NE5WCeT0os0iZcp9QBT:b-pb1ruo) ([raw file](https://github.com/anthony-nolan/atlas/blob/3e1822fd8e78d825e5be581fa880ec6de79a9124/Atlas.Functions.PublicApi.Test.Manual/Services/SearchableDonorUpdatesPeeker.cs#L16)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Atlas should not work with NOVA topics directly - there is Atlas Adapter project for that https://github.com/Anthony-Nolan/Nova.AtlasAdapter.
It takes messages from updated-searchable-dnors topic and sends it to Atlas 
</blockquote></details>

Or is this project only used for testing?

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/815)* status: all files reviewed, 1 unresolved discussion (waiting on @zabeen)

___
*[`Atlas.Functions.PublicApi.Test.Manual/local.settings.template.json` line 10 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/815#-NE5Wn3s2R2hmiSY3gkl:-NE5Wn3s2R2hmiSY3gkm:b-4qnrfq) ([raw file](https://github.com/anthony-nolan/atlas/blob/3e1822fd8e78d825e5be581fa880ec6de79a9124/Atlas.Functions.PublicApi.Test.Manual/local.settings.template.json#L10)):*
> ```JSON
>     "Matching:RequestsTopic": "matching-requests",
>     "Matching:RequestsSubscription": "audit",
>     "Matching:DonorManagement:Topic": "updated-searchable-donors",
> ```

Is there terraform for this project? If so, we need to update it with these new settings
___
*[`Atlas.Functions.PublicApi.Test.Manual/Services/SearchableDonorUpdatesPeeker.cs` line 16 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/815#-NE5VfEd0tGeyiDypDTT:-NE5WXoD5NmKNifl-r7D:beezx4k) ([raw file](https://github.com/anthony-nolan/atlas/blob/3e1822fd8e78d825e5be581fa880ec6de79a9124/Atlas.Functions.PublicApi.Test.Manual/Services/SearchableDonorUpdatesPeeker.cs#L16)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

yes, but even so, it is not looking at anything nova
</blockquote></details>

Ok, got it

**Review by zabeen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/815)* status: all files reviewed, 1 unresolved discussion (waiting on @daria-sorokina-da)

___
*[`Atlas.Functions.PublicApi.Test.Manual/local.settings.template.json` line 10 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/815#-NE5Wn3s2R2hmiSY3gkl:-NE5XAf-9K5dKHQCYUQZ:b-q99otu) ([raw file](https://github.com/anthony-nolan/atlas/blob/3e1822fd8e78d825e5be581fa880ec6de79a9124/Atlas.Functions.PublicApi.Test.Manual/local.settings.template.json#L10)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Is there terraform for this project? If so, we need to update it with these new settings
</blockquote></details>

no terraform, all code in "manual testing" project is designed to be run locally for testing/debugging

**Review by daria-sorokina-da — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zabeen)

**Pull request merged**
