### PR TITLE
fix: #667: Fix donor import failure in the case of donor deletion wit…

### PR DESCRIPTION
**Pull request by IgorZhuravlevDataArt**
…h null HLA

---
This change is [Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/668)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/668)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @IgorZhuravlevDataArt)

___
*[Atlas.DonorImport/Services/DonorImportFileParser.cs, line 102 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/668#-Ms0Exlk0uoe5t3OmpBJ:-Ms0Exlk0uoe5t3OmpBK:b-csfwi0) ([raw file](https://github.com/anthony-nolan/atlas/blob/9d063acdc882a34bb92b5be859e266564039c761/Atlas.DonorImport/Services/DonorImportFileParser.cs#L102)):*
> ```Smalltalk
>                                     ParsedDonorCount++;
>                                     LastSuccessfullyParsedDonorCode = donorOperation.RecordId;
>                                     if (donorOperation.Hla == null && donorOperation.ChangeType != ImportDonorChangeType.Delete)
> ```

are there unit tests for the parser that need update?

**Review by IgorZhuravlevDataArt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/668)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @daria-sorokina-da)

___
*[Atlas.DonorImport/Services/DonorImportFileParser.cs, line 102 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/668#-Ms0Exlk0uoe5t3OmpBJ:-Ms0by5X0eRHCpODysnT:bksqz4c) ([raw file](https://github.com/anthony-nolan/atlas/blob/9d063acdc882a34bb92b5be859e266564039c761/Atlas.DonorImport/Services/DonorImportFileParser.cs#L102)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

are there unit tests for the parser that need update?
</blockquote></details>

All existing tests are passed

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/668)* status: all files reviewed, 1 unresolved discussion (waiting on @benbelow and @IgorZhuravlevDataArt)

___
*[Atlas.DonorImport/Services/DonorImportFileParser.cs, line 102 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/668#-Ms0Exlk0uoe5t3OmpBJ:-Ms0eqWAAFluFsymY4jA:b-v4c02d) ([raw file](https://github.com/anthony-nolan/atlas/blob/9d063acdc882a34bb92b5be859e266564039c761/Atlas.DonorImport/Services/DonorImportFileParser.cs#L102)):*
<details><summary><i>Previously, IgorZhuravlevDataArt wrote…</i></summary><blockquote>

All existing tests are passed
</blockquote></details>

Let's add new tests to Atlas.DonorImport.Test.Services DonorImportFileParserTests?

ImportDonorFile_WithChangeTypeDelete_WithNullHla_DoesNotThrow
and 
ImportDonorFile_WithChangeTypeNotDelete_WithNullHla_Throws?

**Review by IgorZhuravlevDataArt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/668)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @benbelow and @daria-sorokina-da)

___
*[Atlas.DonorImport/Services/DonorImportFileParser.cs, line 102 at r1](https://reviewable.io/reviews/anthony-nolan/atlas/668#-Ms0Exlk0uoe5t3OmpBJ:-Ms0k4Yj1OA6GDQv7ktG:b-896fix) ([raw file](https://github.com/anthony-nolan/atlas/blob/9d063acdc882a34bb92b5be859e266564039c761/Atlas.DonorImport/Services/DonorImportFileParser.cs#L102)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's add new tests to Atlas.DonorImport.Test.Services DonorImportFileParserTests?

ImportDonorFile_WithChangeTypeDelete_WithNullHla_DoesNotThrow
and 
ImportDonorFile_WithChangeTypeNotDelete_WithNullHla_Throws?
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/anthony-nolan/atlas/668)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @benbelow)

**Pull request merged**
