### PR TITLE
feature: #1274: CBT-1475: Send search tracking events

### PR DESCRIPTION
**Pull request by pchenery**
This change is [Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)

### CODE REVIEW

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: all files reviewed, 2 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 57 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0nIRzrBxzVbx1xYRyK:-O0nIRzrBxzVbx1xYRyL:b-qukwwv) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/578ec98f6d90c5db57cc7e21bffd2cffc1036afe/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L57)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task DispatchSearchTrackingEvent_WhenSearchRequested_DispatchesEventWithSearchRequested()
> ```

Let's make this test check the event that's sent to the searchTrackingServiceBusClient
___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs` line 60 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0nJGyE98xxiuakKhV4:-O0nJGyFAcigCP2Cqw_-:b-m2m2lj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/578ec98f6d90c5db57cc7e21bffd2cffc1036afe/Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs#L60)):*
> ```Smalltalk
>                 OriginalSearchRequestId = new Guid(repeatSearchRequest.OriginalSearchId),
>                 RepeatSearchCutOffDate = repeatSearchRequest.SearchCutoffDate.Value.UtcDateTime,
>                 RequestJson = JsonConvert.SerializeObject(repeatSearchRequest.SearchRequest.SearchHlaData),
> ```

Let's serialize the whole repeatSearchRequest, not just repeatSearchRequest.SearchRequest.SearchHlaData

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: all files reviewed, 3 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs` line 52 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0nKOcZ2tv1SZFWw-tx:-O0nKOcZ2tv1SZFWw-ty:be3pini) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/310b7eb598f3ad9d0f86053fa8072a7e1992b87a/Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs#L52)):*
> ```Smalltalk
>         }
> 
>         public async Task DispatchSearchTrackingEvent(RepeatSearchRequest repeatSearchRequest, string id)
> ```

Do we have a unit test for RepeatSearchDispatcher? Please add check of the object sent to the searchTrackingServiceBusClient

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: 14 of 18 files reviewed, 3 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 57 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0nIRzrBxzVbx1xYRyK:-O0ni7272eagkPP614ch:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/578ec98f6d90c5db57cc7e21bffd2cffc1036afe/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L57)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's make this test check the event that's sent to the searchTrackingServiceBusClient
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs` line 60 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0nJGyE98xxiuakKhV4:-O0nXo3P6-I-GKsPZB0G:b-wmns70) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/578ec98f6d90c5db57cc7e21bffd2cffc1036afe/Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs#L60)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's serialize the whole repeatSearchRequest, not just repeatSearchRequest.SearchRequest.SearchHlaData
</blockquote></details>

Good spot, thanks!
___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs` line 52 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0nKOcZ2tv1SZFWw-tx:-O0nw8Oa7ElKSdS72gwX:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/310b7eb598f3ad9d0f86053fa8072a7e1992b87a/Atlas.RepeatSearch/Services/Search/RepeatSearchDispatcher.cs#L52)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Do we have a unit test for RepeatSearchDispatcher? Please add check of the object sent to the searchTrackingServiceBusClient
</blockquote></details>

Done.

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: all files reviewed, 4 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test/Atlas.MatchingAlgorithm.Test.csproj` line 20 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0rbxs4AH-BbBK3EsUx:-O0rbxs59WWleViMyIQA:b2piwin) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7c0de231550b39628a71fd834398ffaf04df8d02/Atlas.MatchingAlgorithm.Test/Atlas.MatchingAlgorithm.Test.csproj#L20)):*
> ```XML
>       <ProjectReference Include="..\Atlas.MatchingAlgorithm\Atlas.MatchingAlgorithm.csproj" />
>       <ProjectReference Include="..\Atlas.MatchingAlgorithm.Data.Persistent\Atlas.MatchingAlgorithm.Data.Persistent.csproj" />
>       <ProjectReference Include="..\Atlas.RepeatSearch\Atlas.RepeatSearch.csproj" />
> ```

No need to introduce this reference
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/RepeatSearchDispatcherTests.cs` line 23 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0rc0fu5ZNQ4dhU7g2g:-O0rc0fu5ZNQ4dhU7g2h:b-i13qa5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7c0de231550b39628a71fd834398ffaf04df8d02/Atlas.MatchingAlgorithm.Test/Services/Search/RepeatSearchDispatcherTests.cs#L23)):*
> ```Smalltalk
> {
>     [TestFixture]
>     public class RepeatSearchDispatcherTests
> ```

The RepeatSearchDispatcher lives in Atlas.RepeatSearch project, so I would expect the tests for it to be in Atlas.RepeatSearch.Test
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/RepeatSearchDispatcherTests.cs` line 100 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0rcH3A1A2MM3kaJkW-:-O0rcH3A1A2MM3kaJkW0:b-o1npt8) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7c0de231550b39628a71fd834398ffaf04df8d02/Atlas.MatchingAlgorithm.Test/Services/Search/RepeatSearchDispatcherTests.cs#L100)):*
> ```Smalltalk
>             await searchTrackingServiceBusClient.Received()
>                 .PublishSearchTrackingEvent(Arg.Is<SearchRequestedEvent>(x =>
>                         x.SearchRequestId == expectedSearchRequestedEvent.SearchRequestId &&
> ```

Instead of doing a field-by-field equality check, can we use Arg.Do to get the actualSearchRequested, and then use `actualSearchRequested.Should().BeEquivalentTo`, see 
https://github.com/Anthony-Nolan/Nova.Aspire.Forms/blob/develop/Nova.Aspire.Forms.Test/Services/CbuRequestFormServiceTests.cs#L76
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 81 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0rd9im9nFmoSDtuVQM:-O0rd9im9nFmoSDtuVQN:b-o1npt8) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/7c0de231550b39628a71fd834398ffaf04df8d02/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L81)):*
> ```Smalltalk
> 
>             await searchTrackingServiceBusClient.Received()
>                 .PublishSearchTrackingEvent(Arg.Is<SearchRequestedEvent>(x =>
> ```

Instead of doing a field-by-field equality check, can we use Arg.Do to get the actualSearchRequested, and then use `actualSearchRequested.Should().BeEquivalentTo`, see 
https://github.com/Anthony-Nolan/Nova.Aspire.Forms/blob/develop/Nova.Aspire.Forms.Test/Services/CbuRequestFormServiceTests.cs#L76

**Review by daria-sorokina-da — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: all files reviewed, 4 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 69 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sOdOr3f8fVT4SdT77:-O0sOdOr3f8fVT4SdT78:b7qbf2s) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L69)):*
> ```Smalltalk
>             SearchRequestedEvent actualSearchRequestedEvent = null;
> 
>             var expectedSearchRequestedEvent = new SearchRequestedEvent
> ```

This is a bad way to create expected data, because you are not checking the helpers you use for generating it.

Also, please don't use searchRequest for constructing the expectedSearchRequestedEvent.

Let's do the following:
1) Create a builder for SearchRequestedEvent
2) Don't use SearchTrackingEventHelper.GetSearchCriteria - provide the expected string
3) Don't use searchRequest.SearchDonorType.ToString - provide the expected string
4) Use DateTime.UtcNow for RequestTimeUtc
5) I'd also prefer not to use JsonConvert.SerializeObject - as, again, you don't see the expected value - let's use a string
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 88 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sPMxd6IjvK5Mq4iwf:-O0sPMxd6IjvK5Mq4iwg:b-9ldfxx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L88)):*
> ```Smalltalk
> 
>             actualSearchRequestedEvent.Should().BeEquivalentTo(expectedSearchRequestedEvent,
>                 x => x.Excluding(s => s.RequestTimeUtc));
> ```

Instead of excluding the RequestTimeUtc, you can use BeCloseTo

```
actualSearchRequestedEvent.ShouldBeEquivalentTo(expectedSearchRequestedEvent, options =>
{
    options.Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation)).WhenTypeIs<DateTime>();
    return options;
});
```
___
*[`Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs` line 85 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sPpuX4sQhTg0saCJY:-O0sPpuX4sQhTg0saCJZ:blkqrka) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs#L85)):*
> ```Smalltalk
>             SearchRequestedEvent actualSearchRequestedEvent = null;
> 
>             var expectedSearchRequestedEvent = new SearchRequestedEvent
> ```

Same here - this is a bad way to create expected data, because you are not checking the helpers you use for generating it.

Also, please don't use repeatSearchRequest for constructing the expectedSearchRequestedEvent.

Let's do the following:
1) Create a builder for SearchRequestedEvent
2) Don't use SearchTrackingEventHelper.GetSearchCriteria - provide the expected string
3) Don't use repeatSearchRequest.SearchDonorType.ToString - provide the expected string
4) Use DateTime.UtcNow for RequestTimeUtc
5) I'd also prefer not to use JsonConvert.SerializeObject - as, again, you don't see the expected value - let's use a string
6) Create a variable `var originalSearchId = "11111111-2222-3333-4444-555555555555"`
Instead of `new Guid(repeatSearchRequest.OriginalSearchId)`, use `new Guid(originalSearchId )`
7) RepeatSearchCutOffDate - please provide a specific date
___
*[`Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs` line 104 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sQhz51TPpblQ1hnQv:-O0sQhz51TPpblQ1hnQw:b-9ldfxx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs#L104)):*
> ```Smalltalk
> 
>             actualSearchRequestedEvent.Should().BeEquivalentTo(expectedSearchRequestedEvent,
>                 x => x.Excluding(s => s.RequestTimeUtc));
> ```

Instead of excluding the RequestTimeUtc, you can use BeCloseTo

```
actualSearchRequestedEvent.ShouldBeEquivalentTo(expectedSearchRequestedEvent, options =>
{
    options.Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation)).WhenTypeIs<DateTime>();
    return options;
});
```

**Review by pchenery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: 16 of 20 files reviewed, 4 unresolved discussions (waiting on @daria-sorokina-da and @SergeyEzh)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 69 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sOdOr3f8fVT4SdT77:-O0xCfFc4nYvVDHRAeAl:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L69)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

This is a bad way to create expected data, because you are not checking the helpers you use for generating it.

Also, please don't use searchRequest for constructing the expectedSearchRequestedEvent.

Let's do the following:
1) Create a builder for SearchRequestedEvent
2) Don't use SearchTrackingEventHelper.GetSearchCriteria - provide the expected string
3) Don't use searchRequest.SearchDonorType.ToString - provide the expected string
4) Use DateTime.UtcNow for RequestTimeUtc
5) I'd also prefer not to use JsonConvert.SerializeObject - as, again, you don't see the expected value - let's use a string
</blockquote></details>

Done.
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs` line 88 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sPMxd6IjvK5Mq4iwf:-O0xCm8oAbOUl9W9CN7b:bb70t73) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.MatchingAlgorithm.Test/Services/Search/SearchDispatcherTests.cs#L88)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Instead of excluding the RequestTimeUtc, you can use BeCloseTo

```
actualSearchRequestedEvent.ShouldBeEquivalentTo(expectedSearchRequestedEvent, options =>
{
    options.Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation)).WhenTypeIs<DateTime>();
    return options;
});
```
</blockquote></details>

Neat
___
*[`Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs` line 85 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sPpuX4sQhTg0saCJY:-O0xCrsVCMn67ExPiSaw:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs#L85)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Same here - this is a bad way to create expected data, because you are not checking the helpers you use for generating it.

Also, please don't use repeatSearchRequest for constructing the expectedSearchRequestedEvent.

Let's do the following:
1) Create a builder for SearchRequestedEvent
2) Don't use SearchTrackingEventHelper.GetSearchCriteria - provide the expected string
3) Don't use repeatSearchRequest.SearchDonorType.ToString - provide the expected string
4) Use DateTime.UtcNow for RequestTimeUtc
5) I'd also prefer not to use JsonConvert.SerializeObject - as, again, you don't see the expected value - let's use a string
6) Create a variable `var originalSearchId = "11111111-2222-3333-4444-555555555555"`
Instead of `new Guid(repeatSearchRequest.OriginalSearchId)`, use `new Guid(originalSearchId )`
7) RepeatSearchCutOffDate - please provide a specific date
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs` line 104 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328#-O0sQhz51TPpblQ1hnQv:-O0xCtiM2qbPsK_NSvEi:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/ed4a0f5ed0bdc25ce8711cde6c3dbeb4d003cddd/Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs#L104)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Instead of excluding the RequestTimeUtc, you can use BeCloseTo

```
actualSearchRequestedEvent.ShouldBeEquivalentTo(expectedSearchRequestedEvent, options =>
{
    options.Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation)).WhenTypeIs<DateTime>();
    return options;
});
```
</blockquote></details>

Done.

**Review by daria-sorokina-da — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1328)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)

**Pull request merged**
